### ISSUE TITLE
VsVim highlight search color has bad contrast when using the VS 2012 dark theme (or any dark background color scheme)

### ISSUE THREAD

**Issue by ianwjhalliday** [VsVim/VsVim#1002]
The search results are highlighted in a bright color, making it hard to read the text when it is in a light foreground color, as most of it is when the background is dark.

There doesn't appear to be a way to change the highlight color, despite a "VsVim Highlight Incremental Search" display item in the Fonts and Colors options dialog.

It looks like this item just changes a very thin border color around the search highlight.

**Comment by S-Bartfast** [comment]
"It looks like this item just changes a very thin border color around the search highlight."

How did you manage that?
This is exactly what I am wanting to achieve.  I use a dark background with a light font and used to have my incremental search put a 'golden frame' around searched words, which I really liked.  I started working on a new machine and the "Item foreground" color of my "VsVim Highlight Incremental Search" is disabled.

Anyone know how I can re-enable it?
