### ISSUE TITLE
ReSharper Live Templates keeps going into command mode

### ISSUE THREAD

**Issue by ThatRendle** [VsVim/VsVim#1024]
I'm not sure what's changed, but since a couple of days ago, whenever I'm filling out the variables in a R# live template (e.g. prop TYPE Type) VsVim goes into command mode as the variables are selected. I have to hit 'c' to enter edit mode and change the variables.

This may be an incompatibility with another extension; has anybody else had this problem?

**Comment by alexeyzimarev** [comment]
The issue is back in R# 9 :(

**Comment by jaredpar** [comment]
@alexeyzimarev R# 9.0 changed their template definition just enough to break the functionality.  The source code was updated a few weeks ago to incorporate the new definitions.  If you grab the latest drop off of AppVeyor it will include that change.

**Comment by alexeyzimarev** [comment]
@jaredpar Great, thanks, will do this

**Comment by Chris-E-J-Ellis** [comment]
We recently acquired R# 9.0 licences and this popped up to bite me this morning, grabbed the latest build from AppVeyor, problem solved. Much appreciated!
