### ISSUE TITLE
Using Russian layout

### ISSUE THREAD

**Issue by eluck** [VsVim/VsVim#1026]
I'm trying to use vsvim with Russian layout and in insert mode everything seems to be ok. But whenever I enter normal mode I have to switch layout to English to make VsVim understand commands.

Vanilla VIM supports the following command:
set keymap=russian-jcukenwin
The command adds Russian layout and makes is possible to switch between English and Russian layouts with Ctrl+^ hotkey.

VsVim doesn't recognize this command.

Is there any other way to use Russian layout in normal mode?

**Comment by melihovv** [comment]
I have the same problem. I'm not very familiar with vim configs. eluck, can you write what you put in your .vimrc?

**Comment by eluck** [comment]
@melihovv I switched from Visual Studio to Webstorm and feel happy now :) I'm not sure I can find my old vim config, sorry.

**Comment by d-chirkov** [comment]
1. Install autohotkey (or any other alternative)
2. Configure Windows from control panel, make CTRL+1 always switch to english layout
3. Create autohotkey script for mapping ESC to CTRL+1 (~Escape::^1)
4. Run this script

This approach should works for all vim implementations in windows.
