### ISSUE TITLE
Support % macro in command line 

### ISSUE THREAD

**Issue by zarucki** [VsVim/VsVim#1038]
I added couple custom tools to the visual studio (Tools->External Tools...). 

In particular:
- command to open current file in gVim when VsVim is not enough ;) (if there's an easier way to do this please let me know, unfortunately % doesn't seem to have a current file path when running :!vim %)
- command to run Kdiff3 on current file against base from repository

The order tools are defined in External Tools... dialog is mapped to the commands in visualstudio:
- First command is Tools.ExternalCommand1, second is Tools.ExternalCommand2

When I press ctrl+/ and enter "> Tools.ExternalCommand1" it works correctly, but when I run :vsc Tools.ExternalCommand1 nothing happens. It could be related to the context, the command is run in. Maybe when running commands through :vsc it doesn't know which file is the current one?

**Comment by ricksladkey** [comment]
This feature was implemented in PR #2229.
