### ISSUE TITLE
How to uninstall vsVim? 

### ISSUE THREAD

**Issue by zdd** [VsVim/VsVim#1064]
Since Ctrl + Shift + F12 does not work, I need to uninstall it.

**Comment by chapgaga** [comment]
@jaredpar in fact i cannot find vsvim in extensions and updates after i installed vsvim, what's wrong?
i am using vs 2013 on win7 x64

**Comment by LexGear** [comment]
Yeah I'm honestly in the exact same position. I installed this. And now I can't find it to remove it.

**Comment by jaredpar** [comment]
If VsVim is installed it should be visible in the Extensions and Updates menu.  Make sure that the *Installed* section is selected on the LHS of the dialog.  VsVim should be at the bottom of the list.

**Comment by eazypeazy46** [comment]
Same case with me too. I cannot even see the extension in Extensions and Updates in Visual Studio. There is no such thing as "Installed" section. I am using VS 2015 Enterprise edition.

Am I stuck with this unless I uninstall and reinstall VS? :-1:

**Comment by allender** [comment]
Your window should look similar to the following.  This is VS2015 community edition but is basically the same for other versions of visual studio.  Extensions that are installed are under the 'installed' rolldown area and then you might have to scroll in the middle window to find vsvim.

![image](https://cloud.githubusercontent.com/assets/1638265/15976203/e05ccfca-2f16-11e6-84ad-5e40bf3c6a5e.png)

**Comment by eazypeazy46** [comment]
Ah, so I had to check under Tools -> Extensions and Updates. I was looking under Tools -> Options -> Extensions and Updates by mistake. Thanks for sharing the screenshot, allender.

**Comment by ChristianBernhard** [comment]
CTRL + SHIFT + X to get to your Extensions. Simply klick on the edit-symbol and klick disable. You maybe need to restart VSC. You can Enable it there again aswell.
