### ISSUE TITLE
Support command line cursor movement by mappings

### ISSUE THREAD

**Issue by roryokane** [VsVim/VsVim#1103]
I have a mapping that types text into the command line and then moves the cursor using the arrow keys.

``` vim
" substitute
nnoremap <Leader>s :%s//g<left><left>
" in visual mode, the range '<,'> is typed automatically
vnoremap <Leader>s :s//g<left><left>
```

When I trigger the mapping, the text `%s//g` gets typed properly into the command line, but the cursor does not appear. I am still in the mode where what you type gets added to the end. After the mapping runs, I must press Left three times to get into the intended state.

Fixing #1102 might automatically fix this bug, depending on how you implement it.

**Comment by ricksladkey** [comment]
This still does not work correctly. Executing the mapping causes two garbage characters to be appended rather than moving the caret. I'm guessing that characters are ASCII NUL.
