### ISSUE TITLE
:echo expand('%:p:h') returns parse error

### ISSUE THREAD

**Issue by alanstevens** [VsVim/VsVim#1113]
This mapping:

```
map <Leader>e :e <C-R>=expand("%:p:h")<CR>
```

Results in "Illegal characters in path".

:echo expand('%:p:h') returns 'parse error"

Source for mapping: http://vim.wikia.com/wiki/Easy_edit_of_files_in_the_same_directory

**Comment by jtbm37** [comment]
I don't think expand is a supported command either
