### ISSUE TITLE
Ctrl-U doesn't scroll up and it is not in the conflict key list. (with default VS2012 key settings)

### ISSUE THREAD

**Issue by sosxisang** [VsVim/VsVim#1129]
Hi, This is my steps.
1. install VsVim 1.4.1.1 from VS2012 Extensions and Updates. Restart VS2012.
2. press "option" button to solve conflict keys.
3. then I tried Ctrl-U, it doesn't work, but change uppercase letter to lowercase letter instead, which means Ctrl-U is handled by VS2012.
4. again I press "option" button to see if I missed this conflict key, but Ctrl-U is not there?puzzled.
5. finally I removed Ctrl-U shortcut from VS2012, then Ctrl-U works (scroll up).
Am I the only one have this problem? I do searched a lot and found nothing about this.
Thank you.

**Comment by ricksladkey** [comment]
Closing stalled investigation.
