### ISSUE TITLE
Tab and Shift+Tab should indent/unindent selection

### ISSUE THREAD

**Issue by pckujawa** [VsVim/VsVim#1133]
I don't know what the default vim behavior is for Tab when in visual selection mode, but it's nice to have VS's default of having the selection be indented on tab and unindented on shift+tab (at least when `set vsvim_useeditordefaults` is in my vimrc file).

**Comment by mattklein999** [comment]
This was my first hit in Google for "vsvim shift tab insert mode", so here is what worked for me for insert mode (not visual mode):

`:inoremap <S-Tab> <C-d>`

p.s. Thanks for the awesome plugin!

**Comment by cphillips83** [comment]
I know this is a closed issue but just wanted to put out that when hitting tab in visual mode it then removes the visual mode selection so you have to reselect to do move more than one tab. Is there a way around this?

**Comment by idealist1508** [comment]
To restore Selection after Tab/Shift Tab you can use following bindings:
```
vmap <Tab> >gv
vmap <S-Tab> <gv
 ```

**Comment by cphillips83** [comment]
This fixes the losing selection issue, thanks.

**Comment by idealist1508** [comment]
You don't need the first two lines in your .vsvimrc file.  Lines 3 and 4 overwrites it. 
I don't know if it works with `:` at begin. I have following lines in my .vsvimrc
```
" Un-\Ident in Normal mode with Shift\Tab
nnoremap <Tab> >>
nnoremap <S-Tab> <<
" Un-\Ident in Insert mode with Shift\Tab
inoremap <Tab> <C-t>
inoremap <S-Tab> <C-d>
" Un-\Ident in Visual mode with Shift\Tab
vmap <Tab> >gv
vmap <S-Tab> <gv

```  
and it works almost perfect 😄

**Comment by cphillips83** [comment]
Ah, wasn't sure if they were some how chained together or not. I'm still fairly new to vim. It does work with the `:` at the front though, I'll update my comment, thanks.

**Comment by nassaleh** [comment]
After putting the code that idealist1508 mentioned, it seems to have disabled the Tab Autocompletion thats built into Visual Studio. It just indents the line instead of inserting a tab
