### ISSUE TITLE
Resharper with Normal/Visual mode: pressing enter while in a string (un)helpfully splits it with a newline.

### ISSUE THREAD

**Issue by nbergen** [VsVim/VsVim#1148]
![image](https://f.cloud.github.com/assets/436882/890560/fe94ebc4-fa37-11e2-93d0-8b544fc8394b.png)

Then, after pressing enter:

![image](https://f.cloud.github.com/assets/436882/890580/54bbc3f6-fa38-11e2-83db-20e416fd87c1.png)

I suspect a conflict with Resharper, which has persisted through several R# versions (I haven't tried 8).

This was a conflict with viemu the last time I used it as well (see: http://youtrack.jetbrains.com/issue/RSRP-200918
and possibly https://github.com/jaredpar/VsVim/issues/651
).

It seems to happen only in my javascript, but I wouldn't expect this behavior at all while in normal/visual mode.

![image](https://f.cloud.github.com/assets/436882/890693/44d5d816-fa3b-11e2-8966-ffcd3a282759.png)

**Comment by benrhughes** [comment]
This is happening for me with typescript files now - js seems ok though. I'm using:
* vsvim 2.0.1 
* VS2013 update 4
* R# 8.2
