### ISSUE TITLE
Ctrl + [ is not working in Visual Studio 2013

### ISSUE THREAD

**Issue by leemuro** [VsVim/VsVim#1193]
I use Ctrl + [ instead of escape in Vim.  I made sure I setup VsVim to handle Ctrl + [ instead of visual studio in the options and have restarted visual studio. It seems to me that Ctrl + [ is still being handled by visual studio since its asking for the second half of a chord instead of the expected Vim behavior.  Any Ideas?

**Comment by kuri65536** [comment]
I have Japanese environment, and solved this issue.

1. Download and Install ENU Language pack.
2. Launch VS2013
3. Change "tool >> options >> environment >> internationalization" to English mode.
4. Restart VS2013
5. Remove keyboard shortcut Ctrl+[ ("Solution Explorer" will appear with English mode)
6. Restore internationalization.

**Comment by cosmoslx** [comment]
@kuri65536  your solution also works in VS2015 with Simplified Chinese language
@lookforit you can try it.

**Comment by lookforit** [comment]
@cosmoslx 
yes,that's the point.
Actually,I posted the solution last year:
https://github.com/jaredpar/VsVim/issues/1309

**Comment by TKYIT** [comment]
@lookforit  @kuri65536  
aslo worked for VS 2019 community japanese .
Thanks

**Comment by justty32** [comment]
@lookforit  @kuri65536 
also worked for VS 2019 community traditional chinese
thanks

**Comment by gendloop** [comment]
Thanks a lot, and I made a summary

**Q: Fail to use `Ctrl + [`**
> Env: Visual Studio 2017 community

1. Set Visual Studio language to English: 
    Tools => Options => Environment => International Settings => English
    ![image](https://github.com/VsVim/VsVim/assets/50388405/a3b08e5b-1cd8-47ba-9b98-a1f647978650)

2. Restart VS
    
3. Delete the keyboard mapping related to `Ctrl + [` 
  a. Enter Page Tools => Options => Environment => Keyboard 
  b. Delete `SolutionExplorer.OpenFilesFilter` 
      ![image](https://github.com/VsVim/VsVim/assets/50388405/73ff27ba-0a54-4db9-adbd-634f6970e4cb)
  c. Delete `SolutionExplorer.PendingChangesFilter` 
      ![image](https://github.com/VsVim/VsVim/assets/50388405/ed1eb958-b228-413d-b6eb-970422031aec)

4. Set the language of VS to the default language, restart VS
