### ISSUE TITLE
\d matches d instead of digit in very magic mode.

### ISSUE THREAD

**Issue by poizan42** [VsVim/VsVim#1238]
This:

```
/\v\d
```

Matches the character 'd' instead of digits, in contrast to vim where \d matches digits for both no magic, magic and very magic mode.

EDIT: actually this seems to be a problem for all the shortcuts to character classes.

VsVim version: 1.5.0.0

**Comment by Chris-E-J-Ellis** [comment]
This behaviour still seems broken for me as of VsVim version 1.8.0. Just checking this isn't some duff config on my side.

**Comment by pleppert** [comment]
I am still seeing this behavior as well, as of VsVim version 2.0.1.0. Specifically, this regex to remove whitespace at the end of each line:
    `:%s:\v\s+$::`
this should match one or more whitespace characters before the end of the line, but instead it matches one or more 's' characters before the end of the line.
    `:%s:\s\+$:: `
this is the equivalent magic mode regex, which seems to work correctly.
