### ISSUE TITLE
Escape cannot close Peek Definition window

### ISSUE THREAD

**Issue by wangzq** [VsVim/VsVim#1316]
According to http://msdn.microsoft.com/en-us/library/dn160178.aspx we should be able to use Escape to close the Peek Definition window; it seems after installing VsVim it no longer works, probably due to the way VsVim has to hook the Escape key.

Reproduced in 1.6.

I have verified in a new user profile that has never installed VsVim and it is able to close the Peek Definition window by using Escape.

There are only 3 commands related to peek window: Edit.PeekDefinition, Edit.PeekForward, Edit.PeekBackward; so I cannot define my own shortcut to close the window.

**Comment by Saftur** [comment]
I've been using VsVim in Visual Studio for a few months now, and it worked pretty well. But I recently updated Visual Studio and pressing escape doesn't close the peek window anymore. I also installed an extension, but it is literally only for syntax highlighting in GLSL files, so it shouldn't be causing this issue. I don't have any other extensions installed.
