### ISSUE TITLE
Chaining _vsvimrc to _vimrc to *real* _vimrc

### ISSUE THREAD

**Issue by farmergreg** [VsVim/VsVim#1355]
I'm running the latest (1.6.0.2). Note, my "real" _vimrc lives in ~/dotfiles/_vimrc which is a git repo. Here's the setup that I initially tried (doesn't work with vsvim):
### ~/_vsvimrc:

```
set vsvim_useeditordefaults
so ~\_vimrc
```
### ~/_vimrc:

```
"For windows computers... fix problems caused by using mklink
"and editing/saving $MYVIMRC by creating a dummy vimrc that points
"to the real one
let $MYVIMRC='~/dotfiles/_vimrc'
so $MYVIMRC
```

As a workaround, I changed _vsvimrc to skip using ~/_vimrc. Then everything works the way it should...:
### ~/_vsvimrc:

```
set vsvim_useeditordefaults
so ~\dotfiles\_vimrc
```

**Comment by ricksladkey** [comment]
Type `:vimhelp :let-environment` for details on how this works.
