### ISSUE TITLE
Select range issue when using mouse

### ISSUE THREAD

**Issue by i-e-b** [VsVim/VsVim#1406]
Version 1.6.x :
When selecting with `v`,_n_`l` both VsVim and gVim include the character under the caret in the selection range.

When making a visual selection with the mouse, gVim includes the character under the caret in the selection range, but VsVim does not.

i.e.
![mouseselectvsvim](https://cloud.githubusercontent.com/assets/576220/3655225/7e5a70e4-1176-11e4-9f11-b099144f9e3f.Gif)

**Comment by Chiel92** [comment]
I still experience this issue. It seems to be related to where on the cursor you have the mouse when you release it. If you look at the gif below, you see that the last `e` in `license` is selected depending on where the mouse is on the cursor. If its more to the right, it is not selected, and if its more to the left, it is.

![asdf](https://cloud.githubusercontent.com/assets/1030961/13433381/e7a30d2e-dfd1-11e5-9905-91271fae1ec2.gif)

Having the last character not selected results in the same issue as in the OP. I'm running VsVim version 2.0.1.0 in Visual Studio 2015.
