### ISSUE TITLE
Double-Click selects an extra character

### ISSUE THREAD

**Issue by Banger** [VsVim/VsVim#1465]
With the latest update, when I double click on a word to select it, it selects an extra character.

I had to disable VSVim because I use the double click a little too much :(

**Comment by DouglasLivingstone** [comment]
I've got a similar issue where an extra character gets selected after double-click dragging.

For example:

    method(foo, bar)

Double clicking on foo or bar by themselves will select just those words, but double clicking on foo then dragging over bar will select the trailing ")" too. (It isn't quite a double click, the specific action is press the mouse down on "o" in foo, release the mouse, press down again on "o", then drag the mouse over to the "a" in bar, then release. This starts a "word selection" mode, where the selection ends in the same place that it would end if you'd double clicked on the last word instead. Handy for selecting all the arguments to a function or selecting a chained property access, eg, foo.bar.baz by dragging out the second half of the double click.)
