### ISSUE TITLE
hlsearch highlighting doesn't match search matches because of universe negation

### ISSUE THREAD

**Issue by kalebpederson** [VsVim/VsVim#1471]
Reproduce case:
1. Issue: `:set hlsearch`
2. Create a file as follows: Hello[Enter]World[Enter]

> Hello
> World
1. Hit escape to go into normal mode
2. Execute the following search: `/o[^o]\+W`
3. Note that VsVim reports "Pattern not found"
4. Note that `hlsearch` caused the o in hello and the W in World to be highlighted:

![image](https://cloud.githubusercontent.com/assets/233827/4720584/1b3018d0-5932-11e4-8309-24e2243448c7.png)

And here's a similar case:
1. With the search completed, delete all the file content
2. Re-add the content: Hello[Enter]World[Enter]
3. Note that the same text as previously shown is highlighted

In case it matters I have R# 8.2 installed. I'm using the latest VsVim at the time of reporting the issue and am running VS 2013 Premium.

**Comment by ricksladkey** [comment]
The bug here is that in vim (unlike .Net Regex), `[^o]` is not supposed to match a line break unless preceded with `\_` as in `\_[^o]`.
