### ISSUE TITLE
nmap <Enter> :vsc Edit.GoToDefinition<CR> is not working

### ISSUE THREAD

**Issue by umitkablan** [VsVim/VsVim#1477]
It is documented to be working but as I press Enter on a symbol I get: "Command requires one argument." error popup. VS 2013 Version 12.0.21005.1 REL.

**Comment by ricksladkey** [comment]
This problem can be solved by mapping `<Enter>` to the native VsVim "Go To Definition" (`<C-]>`) which correctly handles the extra argument required by the C++ Language Service. As a result, this issue can be closed.

**Comment by Wagk** [comment]
I'm sorry; @ricksladkey do you mind providing an example of that workaround? I'm unsure how to write your solution out in my `.vsvimrc`.

**Comment by ricksladkey** [comment]
@Wagk In vim if you want `<Enter>` to perform the same function as `<C-]>` in normal mode, you can add this command to your rc-file:

```
nnoremap <Enter> <C-]>
```

and the same command works for VsVim.
