### ISSUE TITLE
New line indentation

### ISSUE THREAD

**Issue by lleaff** [VsVim/VsVim#1499]
Is there any way to make new line insert be on the correct indentation?
This is the [behavior](http://gfycat.com/MenacingQuaintBeagle) I currently have.
I tried anything I could think of (set novsvim_useeditorindent to on and off) but I couldn't get it to work like it does without vsvim (the editor puts the cursor on the correct indentation even though there aren't any real {tabs} characters until you start writing).
Thank you for the help.

**Comment by madsystem** [comment]
test

**Comment by madsystem** [comment]
Unfortunately cc does not start at the propper indentation level if the line was empty for example an new line added with o (and then switched directly to normal mode). Here is an gif explaining it a little better.

http://giphy.com/gifs/yoJC2EkaGPvMzsHK36

Im using pure visual studio indentation/tab settings. Changing them to my gvim settings did not help. Any tips, workarounds?


Btw thanks for this really great plugin :)


Cheers, Kris

**Comment by jaredpar** [comment]
@madsystem thank you for taking the time to create that GIF.  

I tried out a similar repro to what you had there in gVim and I'm getting the same behavior.  In short I

- Created a new line with <kbd>o</kbd>
- Hit <kbd>Esc</kbd> to enter normal mode
- Executed <kbd>cc</kbd>

At that point the mode was insert and I was in column 0 (both gVim and VsVim).  

Is there perhaps a setting that differs between us that changes the behavior?

**Comment by madsystem** [comment]
Hi there! With my gvim settings I will get to the right indentation level in gvim.

Here is a antoher gif how gvim behaves for me :D.
http://giphy.com/gifs/3xz2BRjFm9mexsDGXC

Here are my gvim settings:
set number
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set laststatus=2
set autoindent
set backspace=indent,eol,start
set ruler
set showcmd
set colorcolumn=80
set autochdir
if has('mouse')
    set mouse=a
endif

**Comment by jaredpar** [comment]
@madsystem it appears this is a c language specific behavior.  If I run the code in a non-C file I get caret at position 0, in a C language file it goes to the indent.  I believe this is because `indentexpr` is set to `GetVimIndent` for C but not the other case.  

At the moment I don't have any support for `indentexpr`.  Issue #881 is tracking this particular behavior though.

**Comment by madsystem** [comment]
Ok thx then ill just have to wait :) Thanks for the help!
