### ISSUE TITLE
Add a UI option to disable VsVim

### ISSUE THREAD

**Issue by FarmerBob** [VsVim/VsVim#1545]
It is so rare that I need to disable VsVim I have to search online each time to remember Ctrl+Shift+F12 combination.  It would be convenient it there was a button to do so on the Options menu.  It would also help when pairing and so that the other person who's not a vim user can quickly switch without knowing the shortcut.

**Comment by jaredpar** [comment]
That's a good suggestion.  I will try and get that added.

**Comment by dsschnau** [comment]
+1, I always end up turning the whole thing off and restarting VS because it takes as long as looking up the hotkey

**Comment by jaredpar** [comment]
Curious, where are you all envisioning this UI option would live?  Essentially which menu would it be under or is it just under the Options page?

**Comment by FarmerBob** [comment]
I was thinking just a "Suspend" button under the Options page.

**Comment by jaredpar** [comment]
@FarmerBob that lines up with my thinking.

**Comment by c0ffeeartc** [comment]
I'd like to see it under `Tools` menu, so pressing `Alt+T, V` would toggle `VsVim`

**Comment by albertdev** [comment]
Maybe the command provided for #1690 could also be added to a menu without too much trouble?

Mind you, I already have a `Vim` command in the External tools list of the `Tools` menu, don't know if other people would also have the `v` accelerator in use. Then again, I could always change it...

**Comment by jaredpar** [comment]
@albertdev it should be easy enough to add to the Tools menu.  I just need to add the correct entry.
