### ISSUE TITLE
Vim gd or Go To Definition Shortcut not functioning as expected

### ISSUE THREAD

**Issue by inkadnb** [VsVim/VsVim#1593]
It looks like the go to definition (gd) command is not the same as Visual Studio's implementation (F12).

gd gives this error in some cases, whereas Visual Studios F12 does not:
![image](https://cloud.githubusercontent.com/assets/349044/7246482/dea9ccdc-e7c3-11e4-92a7-eba3a43ee3f1.png)

It's including the \* in this case, not sure why.

**Comment by jaredpar** [comment]
Thanks for reporting.  Yeah that looks like a bug that the `*` is included.  I will get that looked at.

**Comment by shmup** [comment]
I can make a new issue, but in case you'd prefer not, I'll mention: a clean install of VS2017 and VsVim and `gd` isn't doing anything at all.

**Comment by jnothstine** [comment]
Are you using ReSharper?  There is some setting in ReSharper that broke gd a year or so ago.  Changed the setting in ReSharper and that fixed it.  Unfortunately, I don’t remember the setting.  Gd does work for me in VS 2017.

**Comment by shmup** [comment]
> Are you using ReSharper?  There is some setting in ReSharper that broke gd a year or so ago.  Changed the setting in ReSharper and that fixed it.  Unfortunately, I don’t remember the setting.  Gd does work for me in VS 2017.

@jnothstine sorry I wasn't quick enough, I deleted my comment 10 seconds after posting it, ha.

Discovered there's an open issue for my exact VsVim / VS2017 problem. And no, not using ReSharper, but interesting that it _is_ working for you, hm.

Referring to this open issue, by the way: https://github.com/jaredpar/VsVim/issues/1931

**Comment by ricksladkey** [comment]
Closing because this is the same issue as #1931 and that was closed in https://github.com/VsVim/VsVim/commit/4f5e59dffdf265fa0aecef608c0d3a39bdf5bca8.
