### ISSUE TITLE
Find in files without using the mouse?

### ISSUE THREAD

**Issue by aikeru** [VsVim/VsVim#1620]
I think it would be awesome to be able to use something like `:vimgrep` to search for things across the solution and then select the file without having to use the mouse (the vim way!).

Right now I use Ctrl+Shift+F (Find in files) then have to select what I want using the mouse.

Thanks for this awesome plugin!

**Comment by jaredpar** [comment]
Thanks for the suggestion.  I typically use <kbd>Ctrl+,</kbd> for this scenario.  Will look into `vimgrep` as a more vim solution. 

Glad you're enjoying the plugin!

**Comment by aikeru** [comment]
Also, apparently there is a ```:find``` command in vim. You probably know this, but while ```:vimgrep``` would search in the content of the files and put in the quickfix list, ```:find``` just searches the filenames and supports wildcards. If there's a way to enumerate filenames in the solution and open one from ```:find``` that would similarly be really cool.

**Comment by Kazark** [comment]
This is a good idea.

**Comment by aikeru** [comment]
So, I cloned VsVim and started digging into the code to see how hard it might be to implement the ```:find``` command, or at least make some progress on it. I'm not an F# person, but I was able to make out how functions like "pwd" are invoked.

Looks like ```_vimHost```, when run in Visual Studio, is of type ```Vim.VisualStudio.VimHost```. I don't know how to cast it to its original type or to check if it's that type in F#. Maybe the abstraction ```_vimHost``` should provide something for search through files of the host. Maybe in non-Visual Studio it should report it's not implemented?

Anyway, as you might already know...
You can track down through the Visual Studio Vim Host to ```DTE.Solution.Projects``` which I expect you could enumerate over and then find the files inside. As a complete F# newbie I was fumbling through watch and Immediate Window. That's about where I gave up! :)

**Comment by arunbalachandran** [comment]
I just changed my keybindings.json file and added the
`{ "key": "ctrl+f",
  "command": "actions.find",
  "when": "editorTextFocus && vim.active && vim.use<C-f> && !inDebugRepl" }`

**Comment by ricksladkey** [comment]
My solution is to search with `<C-S-f>` and then use `:cnext` and `:cprevious` (or `<F8>` and `<S-F8>`) to navigate through the matches.

**Comment by ricksladkey** [comment]
Closing this because the Visual Studio interface for "Find in Files" is much more feature rich than anything we could hope to duplicate and can be operated entirely with the keyboard.
