### ISSUE TITLE
'gd' now throws Parse Error in VS2015

### ISSUE THREAD

**Issue by anaisbetts** [VsVim/VsVim#1643]
Not sure if this is a bug in the latest version or in VS2015, but I've always been able to use 'gd' to Go to Definition in VS2013 in C# projects, but in VS2015 with latest VsVim I see "Parse Error" instead. 'gD' seems to work as expected

**Comment by jaredpar** [comment]
Hmm, that's strange.  Can you take a look at your _vimrc file and see if you have any mappings around `gD`.  It's possible the vimscript support improved and started processing an existing `gD` mapping that it had previously ignored.

**Comment by ljani** [comment]
I'm on VS2015 with ReSharper 10 EAP and `gd` seems to be mapped to go to next usage and `gD` is previous usage. `g` it appears in the statusbar of VsVim when pressed. I wonder how to fix this?

**Comment by ljani** [comment]
Hmm, resetting all keyboard bindings, applying ReSharper keyboard scheme and finally setting VsVim to handle all the keybindings got me this exception:

```
  <entry>
    <record>1074</record>
    <time>2015/10/20 12:50:32.224</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))&#x000D;&#x000A;   at EnvDTE.Command.set_Bindings(Object pVar)&#x000D;&#x000A;   at Vim.VisualStudio.Extensions.SafeSetBindings(Command command, IEnumerable`1 commandBindings)&#x000D;&#x000A;   at Vim.VisualStudio.Implementation.OptionPages.KeyboardSettingsControl.UpdateKeyBindings()&#x000D;&#x000A;   at Vim.VisualStudio.Implementation.OptionPages.KeyboardSettingsControl.Apply()</description>
  </entry>
```

**Comment by ljani** [comment]
It seems [ReSharper 10 has changed the functionality](http://blog.jetbrains.com/dotnet/2015/11/02/welcome-resharper-ultimate-10-rtm/) (Usage-aware Go to Declaration). I'm not really sure if this is working as intented with VsVim.

**Comment by jnothstine** [comment]
Go to ReSharper/Options
Under Environment/Search & Navigation
Uncheck "Enable 'Smart go to declaration'

That fixed the problem for me.

**Comment by ljani** [comment]
@jnothstine Thanks for verifying and the workaround, it fixed the problem for me.

Though I wouldn't mind if this worked correctly with VsVim. Should I open another issue for this, @jaredpar?

**Comment by jaredpar** [comment]
@ljani yes, please open a bug

**Comment by ricksladkey** [comment]
The `gd` command could only cause a parse error if it was a mapping.
