### ISSUE TITLE
problem with delete/replace/change commands using semicolon as delimiter

### ISSUE THREAD

**Issue by darkpotpot** [VsVim/VsVim#1656]
Hi,

I have a problem when using the semicolon with delete/replace/change command

If I have this line: `std::string getCurrentWorkingDirectory();`
Using vim, if I type **_dt;**_, everything is deleted up to the semicolon (not included).
However, with vsvim it does nothing. Typing **_dt)**_ works, so it's only a problem with the semicolon.
Typing **_df;**_ also doesn't work.

**Comment by jaredpar** [comment]
@darkpotpot thanks for reporting.  I will take a look at that.  The behavior does seem strange.

**Comment by jaredpar** [comment]
I just checked and this behavior works on my machine.  Is it possible that you have a key mapping for <kbd>;</kbd> that VsVim is incorrectly interpreting here?

**Comment by darkpotpot** [comment]
Oh, indeed you might be right. It seems my **;** key is acting like my **.** key. Don't know why though since I didn't remap it. I'll investigate

**Comment by darkpotpot** [comment]
So I removed everything from my _vsvimrc file without any luck (I also deleted the _vsvimrc file). I even put a **nnoremap ! ;** and hitting *dt!* has the same result, the **!** acts like **.**. Typing :map command after loading also only show the map I did between ! and ;. It's really weird

**Comment by jhamm** [comment]
Is it possible that you also have a `.vimrc` or `_vimrc` that also has that map? One way to check could be to disable the VimRc File loading from Tools > Options > VsVim; and switch it to "No vsvimrc or vimrc files" or "vsvimrc files only".

**Comment by jhamm** [comment]
What does vsvim display when you run the command `:map`?

**Comment by jaredpar** [comment]
@jhamm it will display the contents of all mappings.  In the past I've found that content vimrc files confuse the vimrc logic and end up with errant key mappings defined.  Or at least key mappings that VsVim doesn't support: primarily pointing to functions. 

This is the code that controls it.  

https://github.com/jaredpar/VsVim/blob/master/Src/VimCore/Interpreter_Interpreter.fs#L626

**Comment by jhamm** [comment]
I would like to help with this issue.

@jaredpar what is your "definition of done" for this one?

**Comment by jhamm** [comment]
I created a _vsvimrc based on the files _vimrc.vim  and _vsvimrc  from https://github.com/darkpotpot/mysettings/tree/master/Vim.

Before and after loading the _vsvimrc, I was able to successfully change/delete/replace a line upto ';'.

:map! " returns correctly
i    jj <Esc>
c    w!! w<Space>!sudo<Space>tee<Space>%<Space>>/dev/null

:map " seems to return correctly as well

With "VimRc Error Reporting" enabled, the lines that reported errors in the config were expected.

I loaded up a spf13 vimrc, which seems pretty complex. The lines it was able to parse set to expected values in :set , :map : and :map! .

One thing I found was that if the :map extends beyond the window, the scroll wheel can scroll up and down, but there is no other visual indication that there is more in the text box.

I am having difficulty reproducing the issue, can you provide an example?

**Comment by darkpotpot** [comment]
Hi,

sorry for the late answer. Typing :map displays this :

n    <Tab> :vsc<Space>View.NavigateForward<CR>
n    <C-O> :vsc<Space>View.NavigateBackward<CR>
n    ,/ :nohlsearch<CR>
n    ,> :%s#<Bslash>s*<Bslash>r<Bslash>?$##<CR>:nohlsearch<CR>
n    ,B :vsc<Space>Build.BuildSolution<CR>
n    ,N :vsc<Space>View.PreviousError<CR>
n    ,S :vsc<Space>Debug.StopDebugging<CR>
v    ,cc :vsc<Space>Edit.CommentSelection<CR>
v    ,cu :vsc<Space>Edit.UncommentSelection<CR>
n    ,n :vsc<Space>View.NextError<CR>
n    ,s :vsc<Space>Debug.Start<CR>
n    gm m
n    j gj
n    k gk

But without any map I'm still having the issue.

Maybe it has something to do with my keyboard layout (it is a french one, azerty).

**Comment by darkpotpot** [comment]
So I switched to an English keyboard layout and it works well. The problem only occurs with a french keyboard layout (. and ; are on the same key).

**Comment by jhamm** [comment]
There are two other issues that are similar #1751 and #73. 

Which specific keyboard layout are you using? Is it French (France) > Keyboard > French?
![rundll32_2016-04-12_09-05-12](https://cloud.githubusercontent.com/assets/98657/14460852/d1c932da-008d-11e6-89ac-0fe400bd5611.png)

**Comment by darkpotpot** [comment]
Indeed, I have Visual Assist. And the layout in the image is the one I'm using.

**Comment by jhamm** [comment]
Does the issue continue to happen when you are using the AZERTY layout with Visual Assist disabled?

**Comment by darkpotpot** [comment]
The issue is still here when I disable Visual Assist using their menu. However, I did not try to uninstall it, maybe something is still present. I'll test when I'll have time.

**Comment by jhamm** [comment]
I applied the French(France) keyboard. The `change/delete/replace a line upto ';'` actions worked fine.

I came across an option I had not noticed before under Tools > Options > Environment > International Settings.  It may be worth a try to use the setting "Same As Microsoft Windows".

Or another option could be the Windows Locale setting changing back to English. On the English keyboard, the `,` is on the French key `;`. One keyboard shortcut to toggle the keyboard layouts is Alt+Shift. [StackOverflow: Visual Studio Appears to Randomly adopt American Keyboard Layout](http://stackoverflow.com/questions/484248/visual-studio-appears-to-randomly-adopt-american-keyboard-layout).

**Comment by darkpotpot** [comment]
So I tried the International Settings and no change. Since my OS is in English (only the keyboard is french), it makes sense.

And it's neither a problem with the windows locale setting. I'm always displaying the Input Method in the taskbar to easily detect this kind of issue and it's FRA (france).

PS : I even tested something easier like the replace command `r;` and the result is a `.`

**Comment by darkpotpot** [comment]
New test on an old visual studio 2010. With Visual Assist installed, the issue is present. Without Visual Assist (I uninstalled it), the issue is gone. If I try to only disable Visual Assist within Visual Studio, the issue is here... So it really seems there is a conflict between those 2 plugin :/

**Comment by jhamm** [comment]
The VsVimShared\VisualAssitKeyProcessor.cs PreviewKeyDown method may have something to do with this. I will take a closer look this week.

**Comment by jhamm** [comment]
That method is where the `.` is replacing the `;`. This is using `args.Key == Key.OemPeriod`. On the English key layout, the comma key returns `Key.OemComma`. On the French key layout, it returns `Key.OemPeriod`.

The comment in this method is very helpful. This seems very similar to the issue found in #1762. If we can get that one fixed, maybe the PreviewKeyDown override may not be needed and this issue may go away at the same time.

**Comment by ricksladkey** [comment]
Closing stalled investigation.
