### ISSUE TITLE
Brace matching fails in. C++ files, if string constants contain braces 

### ISSUE THREAD

**Issue by MartinL0815** [VsVim/VsVim#1662]
In the current version string constants contain incomplete brace pairs,  than the brace matching gets confused and matches braces within the string constants.

**Comment by jaredpar** [comment]
Interesting.  It seems that vim recognizes string / character constants as special entities and won't match braces / parens / etc ... which occur inside them.  Unless the cursor is on the brace / paren inside the string.  But it will consider brace / paren which occur inside comments.  Interesting behavior.

**Comment by MartinL0815** [comment]
Interesting behavior? Yes!

I don't care often about this behavior, but maintaining our simulation environment programming editor is sometimes anyoing with this interesting behavior.
Working at other "normal" files, I don't see this behavior!

**Comment by ricksladkey** [comment]
This was fixed in PR #2163.

**Comment by ricksladkey** [comment]
Closing fixed issue.
