### ISSUE TITLE
Is it possible to define key map based on command availability?

### ISSUE THREAD

**Issue by wangzq** [VsVim/VsVim#1761]
I am currently facing an issue which is probably caused by R# instead of VsVim:

I have mapped `gd` to `Edit.GoToDefinition`, which works without R# enabled. Once R# is enabled, and used "Visual Studio" as its keyboard scheme, then when I use `gd` or even using command window to directly invoke `Edit.GoToDefinition`, it will behave like `Go to next usage of the variable`.

As I mentioned above, this is probably because R# intercepted this command, so there is not much to do from VsVim's side. However, while reading another extension Ref12's source code, I realized it has added a new command called `EditorContextMenus.CodeWindow.GoToDefinitionNative` which preserves the old behavior before overriding the `Edit.GoToDefinition`, and I found that mapping `gd` to this command does work correctly with both R# and Ref12 loaded.

However, since I share my .vsvimrc across multiple computers which may not have R# and Ref12 installed, I want to conditionally map `gd` to either `Edit.GoToDefinition` or `EditorContextMenus.CodeWindow.GoToDefinitionNative`, is it possible to do that from .vsvimrc? Maybe check if the latter command exists or not?

Thanks

**Comment by jaredpar** [comment]
Does ReSharper have a named command for Go to definition?  I wonder if I should just change `gd` to use that one when ReSharper is installed vs. using the VS version.

**Comment by wangzq** [comment]
I haven't tried to peek into related R# code to verify it is also overriding the Edit.GotoDefinition command, but the behavior does suggest it should be; I am also not able to find a similar R# command for that. 

However, I still feel like if we could use vsvimrc to map the same keys to different commands then it would be great. One idea is to just write multiple mapping lines in order, and if the mapped command is not available then the mapping is ignored:

    nnoremap gd :vsc Edit.GoToDefinition<CR>
    nnoremap gd :vsc EditorContextMenus.CodeWindow.GoToDefinitionNative<CR>

In above example, if the second command is available then `gd` will be remapped, otherwise the first mapping will take effect.

I have tested that in current VsVim the second mapping will always be in effective even though I haven't installed/enabled Ref12 (that is, the command is not available). Do you think if it is feasible to evaluate if the command is available when parsing the .vsvimrc file?

Thanks

**Comment by ricksladkey** [comment]
This is not workable because at the time the vim rc file is loaded, other extensions might not have loaded, so we cannot validate Visual Studio commands until we execute them.
