### ISSUE TITLE
Parse error on "let @g='/}^M'" vimrc

### ISSUE THREAD

**Issue by DanielKeogh** [VsVim/VsVim#1781]
There is an error when trying to parse macro's in .vimrc containing newline characters. (Specifically the special newline character made from CTRL+V CTRL+M)

My .vimrc contains this:

let @g='/}^M'

**Comment by jaredpar** [comment]
This is a form of `let` I haven't added support or yet.  I'll look into adding it.

**Comment by ricksladkey** [comment]
Control characters (especially `^M`) are problematic for VsVim and many other editors. Vim supports a syntax to avoid having to include them in the `.vimrc` file:

```
let @g="/}\<CR>"
```

which works in both vim and VsVim.

**Comment by ricksladkey** [comment]
Closing because there is a suitable workaround.
