### ISSUE TITLE
Cannot get CTRL + [ to work for the life of me

### ISSUE THREAD

**Issue by ryanlewis** [VsVim/VsVim#1882]
Using VS 2015, ReSharper.

I just cannot get `CTRL-[` to work - at all. I've followed all steps including that in the FAQ to try and resolve this, including removing all bindings that match CTRL-[ within the keyboards menu. If I input CTRL-[ with the keyboard options, it does not show any commands bound to that stroke. However, within the vsvim -> keyboard menu, VsVim still says CTRL-[ is still bound to 4 commands. If I check each of these commands manually, they no longer have any bindings. VsVim obviously thinks VS is still got commands bound to CTRL-[ although VS keyboards panel suggests otherwise.

Not sure if relevant, but when pressing CTRL-[, I get a square bracket within the command palette. Double-pressing [ ([ [) takes me to the opening declaration.

**Comment by jaredpar** [comment]
Can you try the following:

- Tools -> Options -> Keyboard
- Put the focus in "Press shortcut keys"
- Type Ctrl-[

Does anything show up in the box below?  If so can you list it.

**Comment by ryanlewis** [comment]
I followed the instructions in the FAQ and eliminated all commands that were listed for CTRL-[, of which there is now none listed.

<img width="956" alt="screen shot 2016-12-09 at 09 44 23" src="https://cloud.githubusercontent.com/assets/427747/21044492/333b1794-bdf4-11e6-9ab8-63834fef9204.png">

As I mentioned above, VsVim still seems to think that CTRL-[ is handled elsewhere, despite no commands being bound as per the screenshot above.

<img width="541" alt="screen shot 2016-12-09 at 09 45 47" src="https://cloud.githubusercontent.com/assets/427747/21044542/6a22b5f0-bdf4-11e6-92d1-b8f6a9125257.png">

**Comment by ryanlewis** [comment]
So I got a little further, but not all the way there.

After setting C-[ back to Visual Studio within VsVim keyboard settings, I got all the commands appearing within tools -> options -> keyboard again. These have now been removed, and Visual Studio restarted. I no longer see the Ctrl-[ option in VsVim -> Keyboard, which would suggest I've sorted out the bindings, however Ctrl-[ still won't escape from insert or visual mode.

Is there any diagnostics with VsVim which would help me diagnose the issue any further?

**Comment by jaredpar** [comment]
Try the following:

- Open the command Window (believe it's under the View menu item)
- Run the command "VsVim.DumpKeyboard"

That will dump out the keyboard settings as VsVim sees them.  If you post that file somewhere I can take a look and see what is going on there.  

Another possibility is ReSharper conflicts.  Can you try removing the definition from ReSharper and see if that clears up the issue?

**Comment by ryanlewis** [comment]
[Here's a dump of my keyboard.txt](https://gist.github.com/ryanlewis/96e773b0e644560c7f7c9ffc5675186a).

I've tried disabling ReSharper. ReSharper itself uses the standard VS commands interface, and have all now been disabled.

**Comment by jaredpar** [comment]
@ryanlewis did disabling ReSharper work in this case?

**Comment by ryanlewis** [comment]
Finally resolved the issue, after finding #1214. Turns out the issue is with Parallells on the Mac, which has issues with sending the CTRL-[ chord to virtual machines. I've ran the workaround detailed in the link below and all is working now. 

Sorry for wasting your time. Maybe it's worth adding to the FAQ?

http://superuser.com/questions/695945/ctrl-not-working-in-windows-8-or-xp-running-in-parallels-virtual-machine/730239#730239

**Comment by jaredpar** [comment]
@ryanlewis wow, I'm having the exact same issue right now with parallels on my Mac.  So you didn't waste my time, you just solved my problem :smile:

**Comment by ZzAntares** [comment]
Hello @jaredpar, I'm having the exact same problem but in a non-virtualized environment. I already remove all keyboard shortcuts utilizing `CTRL-[` and have all keyboard shortcuts handled by VsVim in the _vsvim -> keyboard_ menu. What could be the cause?

**Comment by ricksladkey** [comment]
@ZzAntares This issue was related to keyboard conflict between Parallels and the guest machine. If you are having a different conflict, feel free to open a new issue.
