### ISSUE TITLE
Configure Key Bindings from vimrc

### ISSUE THREAD

**Issue by exyi** [VsVim/VsVim#1885]
I'd like to configure VsVim's keybinding options (the GUI options) from vimrc, so I could easily transfer them between computers. Setting caret and background color would also be nice.

Is that somehow possible? I could not find it anywhere nor in the code - where are these settings located in the code? Maybe I could craft something myself ;)

**Comment by oysteinkrog** [comment]
Create a .vsvimrc file and source whatever files you want.
I have dedicated files for keybindings etc that I source from both my .vimrc and .vsvimrc.

**Comment by exyi** [comment]
I already use a .vsvimrc file, but I don't know how to configure if the keybinding is handled by Vsvim or VisualStudio. I mean this window: ![image](https://cloud.githubusercontent.com/assets/7894687/21578571/00a9e0be-cf86-11e6-87ea-afc8ab7046fb.png)

**Comment by jaredpar** [comment]
Right now there is no way to do this.  Actually the first time I've gotten this request.  Let me think about it a bit.

**Comment by ricksladkey** [comment]
Although this issue is older, I'm closing it as a duplicate of #1921.
