### ISSUE TITLE
Make `Ctrl-[` work like `Esc` to dismiss "Navigate To" and other VS windows

### ISSUE THREAD

**Issue by m0tive** [VsVim/VsVim#1897]
It is possible to dismiss "Navigate To..." (i.e. Ctrl-`,`) using Esc but not using Ctrl-[

This breaks the "flow" when trying to use Ctrl-[ instead of Esc.

I think it's a general issue that you can "dismiss" focus from a window in VS using Esc to return to text editor. It would be great if you could use Ctrl-[ in all these cases.

**Comment by jaredpar** [comment]
Had not considered that scenario.  Will look into that.  Need to figure out a good way to understand if we are in a "Navigate To" mode.  Given that the bug fix should be straight forward.

**Comment by kkorus** [comment]
@m0tive  I use CAPS LOCK as Esc, try it.

**Comment by ricksladkey** [comment]
As convenient as this might be, if it can be done at all, it would likely be very VS version specific and completely unrelated to the reset of VsVim. In other words, it could easily be a separate extension. I think it would be overreach for VsVim to try to take on this task.

For example, in Visual Studio you can choose Tools -> Options using the menu and then type `<Esc>` to dismiss the options window. The requested feature would require enabling `<C-[>` to dismiss this and related modal windows. But Visual Studio does not provide any extension points to do this kind of thing and so any solution would be hacky and fragile. One hack might be needed for the goto window and another for the options window.

I do appreciate that in the spirit of vim this it is a reasonable desire, and a genuinely good idea, but my opinion is that it is too ambitious for VsVim.
