### ISSUE TITLE
VsVim copy does not include syntax highlighting

### ISSUE THREAD

**Issue by dfbrown** [VsVim/VsVim#1920]
I'm currently using Visual Studio 2012 and VsVim 2.2.0

When copying using Ctrl-C (which I have set to be handled by visual studio), the syntax highlighted and formatted text is copied, but when copying using VsVim it only copies the raw text.

For example in visual studio my code looks like this:
![image](https://cloud.githubusercontent.com/assets/235135/23088520/16df89ac-f532-11e6-9491-94bfdf3ae91d.png)

If I copy it using Ctrl-C (handled by visual studio) and paste it into outlook it looks like this:
![image](https://cloud.githubusercontent.com/assets/235135/23088529/22634cc8-f532-11e6-81d9-ef94beac85ec.png)

But if I copy it using `y` it isn't colored and looks like this:
![image](https://cloud.githubusercontent.com/assets/235135/23088536/29bd3bdc-f532-11e6-9565-372aedc6bca7.png)

Not a serious issue, but a minor annoyance of mine. Thanks for all your work on this excellent plugin :)

**Comment by DHowett-MSFT** [comment]
The fix here works if `clipboard=unnamed`, but it _doesn't_ work for `"*y`, which also fills the system clipboard.

**Comment by ricksladkey** [comment]
@DHowett-MSFT Can you create a new issue? Thanks a bunch!

**Comment by DHowett-MSFT** [comment]
Gladly!

**Comment by DHowett-MSFT** [comment]
Split off #2767.
