### ISSUE TITLE
Deleting a visual line selection of folded code omits the last fold

### ISSUE THREAD

**Issue by mfrischknecht** [VsVim/VsVim#1936]
Given this code:

```
using System;
class Foo
{
    void Bar()
    {
        Console.WriteLine("Bar");
    }
    void Baz()
    {
        Console.WriteLine("Baz");
    }
}
```

If both methods are collapsed, selecting them using `Vj` and then deleting them (`d`) leaves the last folded method body in the file. Consequently, the only line of the last method that will be pasted later (`p`) will be its signature.

The result of `1GzM2Gza4GVjd`  thus is the following code. Deleting a single folded method is still possible when using `dd` (which behaves properly).

```
using System;
class Foo
{
    {
        Console.WriteLine("Baz");
    }
}
```

**Comment by orccrusher99** [comment]
Somewhat related issue/bug: 
selecting a fold of _n_ lines plus the line afterwards deletes _2n_ lines total.
```
void lines5() {     // 1
                    // 2
                    // 3
                    // 4
}                   // 5
                    // 6
void lines4() {     // 7
                    // 8
                    // 9
                    // 10
}                   // 11
                    // 12
                    // 13
                    // 14
                    // 15

```

Line-wise selecting lines 1-6, when `lines5` is folded, deletes lines 1-12. 

The same number of lines are deleted with or without the comments, though with the comments allows selecting lines 1-5, which similarly deletes lines 1-8 instead.
