### ISSUE TITLE
VS2017 - TextBox in Edit.GoTo.GoToAll looses focus when 'Use preview tab' is checked

### ISSUE THREAD

**Issue by karkianish** [VsVim/VsVim#1951]
In VS2017,  when using GoTo (Edit.Goto.GoToAll) feature with 'Use preview tab' option checked, as we type search text, visual studio loads the first matching file in a new tab. This causes VsVim to set the caret position on the top of the file and not on the search text box. As you continue to type the search text, you will end up typing on the file instead. You may need to type slower than usual so that VS loads the selected file in a tab.

There is a workaround though. From Settings option in Go To All modal, uncheck 'Use preview tab'.

**Comment by ricksladkey** [comment]
I cannot reproduce this with VsVim 2.5.0.0 or on the master branch of the repository. There are very few times when VsVim manually adjusts the focus and certainly not when it detects that a file has been opened by Visual Studio. Not only does VsVim not adjust the focus of a new buffer, it doesn't adjust the caret. So I'm stumped for how this could be happening.

If you could perform two experiments, it might be helpful.

1) Try with VsVim disabled, or ideally, with VsVim uninstalled
2) Rename your `.vsvimrc` out of the way and try with an "unmodified" VsVim

**Comment by ricksladkey** [comment]
To clarify, yes, in my testing it does take a couple of seconds for the file to show up in the preview tab. With VS2015 or VS2017, I can slowly arrow up down the list of "Go To" candidates and see them appear in the preview pane, properly scrolled to the identifier being searched for, and the focus never leaves the "Go To" search text box.

**Comment by ricksladkey** [comment]
We can't make progress on this issue unless we can reproduce it.

@karkianish, I'm wondering if you can re-enable the preview tab for 'Go To' results and see if the problem still occurs.

**Comment by ricksladkey** [comment]
The setting is the bottom checkbox here in VS2017 and VS2019:

![image](https://user-images.githubusercontent.com/2680524/58923081-0c771980-870c-11e9-95d3-1ef9b476e16f.png)

**Comment by karkianish** [comment]
@ricksladkey , thank-you for looking into this report. 

I cannot recreate this issue in the current version on my VS2017. This was a while back. Since then I have updated my VS2017. At this time it is working as expected. 

Thank-you again for making time to look into this.
