### ISSUE TITLE
Changing Handling of Keybindings to VsVim doesn't seem to work correctly

### ISSUE THREAD

**Issue by keithn** [VsVim/VsVim#1973]
Setup: VS2017 + Resharper   ( not sure if that causes a problem or not)

When I try to change the Ctrl-E and Ctrl-D to be handled by VsVim and save setting, it hangs for a long time (> 1 minute). It eventually becomes responsive, and it says it is handling it, however 

Ctrl-E binding is wrong, it thinks it's a chord and waits for the second part of the chord.

Ctrl-D is handled correctly

**Comment by mgregory22** [comment]
Resharper definitely isn't the problem because I am experiencing the same thing with Ctrl-E and I don't have Resharper.

**Comment by sqlkoala** [comment]
> Ctrl-E binding is wrong, it thinks it's a chord and waits for the second part of the chord.

I think that's the clue. vsvim seems to have problems with (vistual studio) shortcuts that consist of 2 keystrokes. Like this:
![image](https://user-images.githubusercontent.com/30384885/34911139-c98fbe9c-f8c3-11e7-9418-cadd3623cb4b.png)
I noticed this with Ctrl-R and SSDT ( which introduce a bunch of chords as shortcut that start with ctrl-r in 2017 ).
I think there is way to get these Ctrl-E (or -R) working in vsvim:  delete all chords that start with them. You can do this, by going to: Options -> Env. -> Keyboard   and then press ctrl-e (like in the screenshot) and delete (backspace) all shortcuts that show up.

**Comment by Mrb83** [comment]
Had the same problem. Fresh installation of VsVim, Ctrl-E wouldn't work despite having a) assigned all keys to VsVim in the Tools -> Options -> VsVim -> Keyboard dialog b) made sure Ctrl+E was not used by any other short cuts in the Tools -> Options -> Environment -> Keyboard dialog. Once I followed the suggestion of @ricksladkey and checked the 'Include all scopes' in the VsVim configuration dialog, Ctrl+E then worked properly.
