### ISSUE TITLE
Weird behavior after clicking into an escape sequence

### ISSUE THREAD

**Issue by mfrischknecht** [VsVim/VsVim#2020]
Visual Studio displays non-printable characters in source code using the according terminal escape sequence. A string containing the `SOH` character (`'\1'`) is thus displayed like this:

```
public static class Program
{
    public static void Main()
    {
        var foobar = "foo^Abar";
    }
}
```

The escape sequence (`^A`) is highlighted accordingly. Moving over the escape sequence using `hjkl` in VsVim works great, however if the user clicks into the escape sequence using the mouse, the text cursor will be moved into the sequence and stay in insert mode. All keys pressed are ignored by VsVim and instead inserted between the carret and the according escape character. Trying to move out of such a sequence will thus result in the string looking like this: `"foo^jjjjAbar"`.

**Comment by mfrischknecht** [comment]
I'm not sure if this is related to #1786, so I thought I'd open another issue.

**Comment by ricksladkey** [comment]
@mfrischknecht It's not related to surrogates; it's caused because each control character display is actually a miniature text box! We can change it to a text block so that you cannot give it the focus or otherwise modify its contents.
