### ISSUE TITLE
Slow `<c-[>` and `<Esc>`

### ISSUE THREAD

**Issue by Wagk** [VsVim/VsVim#2177]
While editing I find myself running into situations where I attempt to escape into normal mode but the switch happens slow enough that I begin typing ex- and normal mode commands into insert mode.

Is there a way to make escaping into normal mode mode responsive?

**Comment by jaredpar** [comment]
Escape into normal mode should be quite responsive. It's really a simple mode change and on the VsVim side really doesn't require much processing at all. It sounds like there is a bad interaction here that is causing the issue.

Can you grab a perf trace of this? That will let me see what is going on here and help diagnose the problem. 

https://github.com/dotnet/roslyn/wiki/Recording-performance-traces-with-PerfView

**Comment by ricksladkey** [comment]
Responsiveness aside (important as it is), the symptoms described would seem to require that keystrokes were somehow processed out of order. Typing `<Esc>` should synchronously exit insert mode. No matter how long that takes, the subsequent keystrokes should be processed in, say, normal mode.

**Comment by jaredpar** [comment]
>  No matter how long that takes, the subsequent keystrokes should be processed in, say, normal mode.

Very true.  In this case though if there is a conflict with another extension it's possible they're intercepting <kbd>Esc</kbd> and causing the behavior to appear out of order. That's also why I was interested in the perf trace. The stacks should reveal if another component is getting involved here and interferring with the key strokes.

**Comment by ricksladkey** [comment]
Closing stalled investigation.
