### ISSUE TITLE
Insert mode unicode input

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2285]
Need to implement <kbd>Ctrl-V,u</kbd> and <kbd>Ctrl-V,U</kbd> for insert mode. Found this to be invaluable when i'm tracking down surrogate pair isssues.

**Comment by ricksladkey** [comment]
Along these lines, I tried but failed to update insert mode to use a command runner. I think it would be a good thing and I might have succeeded if I had tried harder, but the job requires more contextual knowledge of the command runner than I have right now. Anyway, the next time we add a multi-key sequence to insert mode might be a good time to upgrade to a command runner.

**Comment by jaredpar** [comment]
I had the same experience trying to add a command runner in the past. I didn't have a ton of motivation at the time though. This feature would seem to add the motivation.

**Comment by ricksladkey** [comment]
I added "normal" `<C-q>` in insert mode in a PR, but didn't realize this feature is related to that one. I'll push some more commits to PR #2531 to add this support. For reference: this is described in vim with `:help i_CTRL-V_digit`:

```
With CTRL-V the decimal, octal or hexadecimal value of a character can be
entered directly.  This way you can enter any character, except a line break
(<NL>, value 10).  There are five ways to enter the character value:

first char	mode	     max nr of chars   max value ~
(none)		decimal		   3		255
o or O		octal		   3		377	 (255)
x or X		hexadecimal	   2		ff	 (255)
u		hexadecimal	   4		ffff	 (65535)
U		hexadecimal	   8		7fffffff (2147483647)
```
