### ISSUE TITLE
Closing a buffer with a keyboard command disables macro recording

### ISSUE THREAD

**Issue by dhmgit** [VsVim/VsVim#2356]
Closing a buffer using a keyboard command such as `ZZ` or `:q<cr>` causes subsequent attempts to record a macro to fail.

The root cause appears to be the MacroRecorder's `_nestingDepth` variable, which fails to decrement to zero when the buffer is closed in this manner.  This is because the buffer's Closed event fires before the KeyInputEnd event.  The MacroRecorder disposes its event handlers on Closed and so does not see the final KeyInputEnd event.  Subsequent attempts to record a macro will fail because `_nestingDepth` is always positive.

**Comment by ricksladkey** [comment]
I am pretty sure this bug was introduced recently by PR #2175, which was intended to fix a different problem, but has this side-effect.

**Comment by dhmgit** [comment]
I played around with this a bit and I had some luck with "pausing" the recording in CommandUtil.RunMacro, as CommandUtil already has a reference to the MacroRecorder.  This prevents VsVim from getting into an unrecoverable state in which it won't record macros.  
However, it still fails to completely record a macro that involves closing a buffer.  So `qaZZq` fills the 'a' register with `Z` instead of `ZZ`.  So I think there is a more general problem surrounding macro recording and closing buffers, due to the order in which buffer events are raised.  I'm reluctant to mess with the event order, however, as I have not attempted to track down every usage of these events -- changing the order could easily break something else.

Perhaps another event should be added to indicate that the buffer is "really" closed and will no longer be raising events (so go ahead and dispose your event handlers)?  This would avoid making a breaking change to the event order, but it seems like a bit of a kludge at first glance.  There is probably a better solution.
