### ISSUE TITLE
Interact with multi-caret selections

### ISSUE THREAD

**Issue by EnCey** [VsVim/VsVim#2362]
Visual Studio 15.8 introduces a new way to create multi-caret selections with `shift + alt + .` to select the next occurrence of the current word, which I find very useful.

This puts VsVim in VISUAL mode, which means `shift + i` and `shift + a` don't work. 

Can this be changed somewhere so that VISUAL BLOCK mode is used instead? Or is it possible to enter block mode while keeping the current selection? (`ctrl + q` on my machine enters block mode but only the original word remains selected)

_(This may be dumb question since I'm not very familiar with vim's visual mode)_

**Comment by ricksladkey** [comment]
This command is called "Insert Next Matching Caret" and is bound to `Edit.InsertNextMatchingCaret`. described [here](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-2017-for-dotnet-developers?view=vs-2017). It is part of the new "Multiple Caret" support.

I haven't been able to find out how this is implemented at the text editor API level, so at the moment we don't even have a way to create multiple carets ourselves or to detect that there are multiple carets. Having this API level access is critical to preventing use from interfering with Visual Studio when it is in this mode or from using it ourselves.

**Comment by ricksladkey** [comment]
OK, some Visual Studio devs pointed me towards [IMultiSelectionBroker Interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.imultiselectionbroker?view=visualstudiosdk-2017). It's probably messy to access this from within VsVim which supports all Visual Studio versions with the same extension, but at least it's a foothold.

**Comment by ricksladkey** [comment]
I closed my first PR as the issues that it raises are bigger than external edit mode gives us out of the box. At this point, I am thinking that the best solution would be to extend select mode to support multiple selections.

The goal of select mode is to simulate Windows selections and so, to the extent that it is possible, we would hopefully support multiple carets / selections without losing control over fine-grained behavior. That might be ambitious, but multiple cursors are all the rage and so it seems worth at least seeing how hard it would be.
