### ISSUE TITLE
Not obvious how to disable or find supported features

### ISSUE THREAD

**Issue by gooddadmike** [VsVim/VsVim#2378]
It should be very obvious how to do 2 things

1. temporarily disable
1. see all the shortcuts

I think there should be a description of how to disable in the extension blurb and a link to Supported Features in both the readme and the blurb that shows up in Visual Studio. It wasn't easy for me to find. 

Maybe the [supported features](https://github.com/jaredpar/VsVim/blob/master/Documentation/Supported%20Features.md) could be merged or moved with/to the [FAQ](https://github.com/jaredpar/VsVim/wiki/FAQ) as well.

Maybe you could link out to your favorite "learn vim" tutorial or "VsVim for Visual Studio" Youtube Demo?

**Comment by ricksladkey** [comment]
Wiki updated with the requested information. Updating the out-of-date supported features created as a separate issue #2541.
