### ISSUE TITLE
Ctrl+V should go to visual block mode

### ISSUE THREAD

**Issue by jasonmalinowski** [VsVim/VsVim#241]
Ctrl+V can be used to switch from normal to visual-block in Vim, but doesn't work in VsVim.

**Comment by EricTetz** [comment]
In Vim `p` is paste, `<c-v>` is visual block mode. Why would you care about preserving CUA bindings in a Vim emulation?

**Comment by ricksladkey** [comment]
@EricTetz All users could just map `Ctrl+V` to VsVim in Tools -> Options -> Keyboard.  This makes `Ctrl+V` from normal mode enter visual block mode and paste from insert mode, just like Windows gvim.

**Comment by wwurjant** [comment]
Does ctrl-Q still work? It goes into Quick launch menu for me

**Comment by wwurjant** [comment]
I figured out to resolve ctrl-Q launching quick launch.
In case anybody else sees the same issue, here is the solution:
In visual studio, select tools->options->visvim->keyboard
There are existing entries, including ctrl+Q
Switch from controlled by visual studio to controlled by visvim

**Comment by ahartschen** [comment]
I don't understand the issues related with Ctrl-V in VSCodeVim Ctrl-V is visual mode in when in normal mode and pastes when in insert mode. That's a pretty effective solution. Is there a limitation with Visual Studio not allowing this functionality?

**Comment by ricksladkey** [comment]
@ahartschen I think you are in the wrong repository. You are looking for https://github.com/VSCodeVim/Vim
