### ISSUE TITLE
Can't enter period in VS2017 search box if not in insert mode.

### ISSUE THREAD

**Issue by BigDub** [VsVim/VsVim#2421]
Repro:
Leave insert mode.
Press Ctrl + F to open the visual studio search search box.
Click inside the search UI's text box and enter period (not on the number pad).

Expected behavior:
A period shows up in the search UI's text box.

Observed behavior:
Repeats last command.

Notes:
It's worth noting that using the period on the number pad does not have this issue, and performs as expected.
If you're in insert mode, it works as expected. Letters seem to enter as text in the search box when not in insert mode instead of performing their corresponding vim command, as far as I can tell it's just the period.

**Comment by ricksladkey** [comment]
@BigDub Do you have VisualAssist installed?

Possibly related issues: #1777 and #1971.

**Comment by BigDub** [comment]
I do have visual assist installed, also ReSharper. Are there known conflicts?

Thanks for the quick response, sorry I didn't return the favor.

**Comment by ricksladkey** [comment]
@BigDub, there was a known problem (and several issues that reported it). See PR #2201. And others have reported that it is fixed. Which version of VsVim are you using? You can use `:version` to check.

**Comment by BigDub** [comment]
I'm using version 2.6.0.0.
Is this fixed in a later version I'm not using?

**Comment by BigDub** [comment]
Ah... It seems Visual Studio automatically updated the plugin for me at
some point and I can no longer reproduce the issue.

**Comment by hamaney** [comment]
I see this in VS2019 with VsVim2.8.0.0. I also have VisualAsset installed
