### ISSUE TITLE
Can't press <Esc> to exit F2-rename window

### ISSUE THREAD

**Issue by msloan** [VsVim/VsVim#2427]
I'm using...
VS 15.9.2
VsVim 2.7.1259

To repro:
1. Attempt to rename a variable through VS context menu or kb shortcut (F2 by default).
2. Press \<Esc\>

Observe that the visual studio rename window remains. If you highlight over the X in the top right corner of the rename window, the tool tip claims that \<Esc\> should close the window.

If I uninstall VsVim, the rename window closes as expected when I press \<Esc\>

**Comment by msloan** [comment]
I just noticed that I can just press Enter instead of Esc which will work just fine for me.

**Comment by ricksladkey** [comment]
@msloan Thanks for the workaround, but it only works when you haven't starting typing the new name. Hitting escape reverts any changes, but hitting return applies them.
