### ISSUE TITLE
VsVim 2.6.0 is broken for Atmel Studio users

### ISSUE THREAD

**Issue by DepthDeluxe** [VsVim/VsVim#2442]
It looks like VsVim 2.6.0 does not work with Atmel Studio which is a variant of Visual Studio 2015.  I get the following error message in the ActivityLog.xml.

```
  <entry>
    <record>459</record>
    <time>2018/12/11 23:59:23.422</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [VsVimPackage]</description>
    <guid>{A284D12C-1E96-451B-A3B0-5486A1BEB6CA}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
```

It looks like some sort of dependency issue?  Downgrading to 2.5.0 fixes the problem.

**Comment by TKumadaki** [comment]
I have confirmed that VsVim 2.7 can be installed on Atmel by the following method.

1. Obtain "Microsoft.VisualStudio.Shell.11.0" from the PC on which Atmle is installed.
This was obtained from the following path
C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.VisualStudio.Shell.11.0\v4.0_14.0.0.0__b03f5f7f11d50a3a 
2. Replace the acquired dll in VsVim's "References\Common".
3. Change the dll version of the project from 11.0.0 to 14.0.0.
**VsVimShared.csproj, VsVim.csproj, VsVimSharedTest.csproj**

**old**
`<Reference Include="Microsoft.VisualStudio.Shell.11.0, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />`

**new**
`<Reference Include="Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" />`

I do not know if this method is correct.
I will wait for  @jaredpar or @ricksladkey reply.

**Comment by ricksladkey** [comment]
@TKumadaki, I will let @jaredpar try to make sense out of how that situation came to be and why it works. For completeness, you could zip up and try to attach the file you obtained to this issue.

**Comment by jaredpar** [comment]
@TKumadaki I have a suspicion on what is going on here. I'm not sure what the exe name is for Atmel Studio but can you grab the exe.config file for the exe? Essentially the equivalent of devenv.exe.config. 

My suspicion is that because they're based on a specific version of the VS shell they lack binding redirects for earlier versions. That is why the change in version number fixes the problem.

**Comment by TKumadaki** [comment]
[atmel.zip](https://github.com/VsVim/VsVim/files/3125612/atmel.zip)

I uploaded the dll and config.
The product name of this dll is Visual Studio 2015.
Meanwhile, the product name of VsVim 2.7 dll is Visual Studio 2012.
config does not have Microsoft.VisualStudio.Shell.11.0.dll.

By the way, congratulations on the transition to the organization!

**Comment by TKumadaki** [comment]
@jaredpar I read your reply and came up with the following fix.

Add the following to AtmelStudio.exe.config.

```
<dependentAssembly>
  <assemblyIdentity name="Microsoft.VisualStudio.Shell.11.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
  <bindingRedirect oldVersion="2.0.0.0-14.0.0.0" newVersion="14.0.0.0"/>
</dependentAssembly>
```

I have confirmed that it works without modifying VsVim by this method.
Of course I think this is not a recommended method.

**Comment by jaredpar** [comment]
@TKumadaki 

Thanks for confirming. This just looks like an omission on their part. Consider they have the following entries:

``` xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.Shell.9.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="2.0.0.0-12.0.0.0" newVersion="14.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.Shell.10.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="2.0.0.0-12.0.0.0" newVersion="14.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.Shell.12.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="2.0.0.0-12.0.0.0" newVersion="14.0.0.0"/>
      </dependentAssembly>
```

Essentially a redirect for 9, 10 and 12 but not 11. Not sure how they generate this file, or why they just didn't take the VS version, but probably need to push on them to fix this.

**Comment by TKumadaki** [comment]
@jaredpar
I wanted to send this to Atmel Studio as an issue.
However, Atmel Studio does not seem to be developed on Github.

**Comment by TKumadaki** [comment]
I do not use Atmel Studio.
If they can, I want that users using VsVim at Atmel Studio send this issue.

**Comment by ricksladkey** [comment]
@TKumadaki I think you have root caused the issue, confirmed that VsVim is unable to fix it, and even provided a workaround. If an Atmel Studio user like @DepthDeluxe would like to report the issue to Atmel Studio, they can link to the research that has been done here.
