### ISSUE TITLE
VsVim seems to cause VS 2019 instability

### ISSUE THREAD

**Issue by thelazydogsback** [VsVim/VsVim#2459]
If I use VsVim with VS2019, VS seems to hang quite often, requiring me to kill it from taskman. (Without VsVim, I have not had an issue so far.)
Sometimes upon restart I get a "Try disabling VsVim extension..." message, sometimes I do not.

=================================================
VsVim 2.6.0.0.

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 2.2
VisualStudio.16.Preview/16.0.0-pre.2.2+28602.52
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   9.0.11128.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   16.0.12095.36948
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   16.0.12095.36948
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.0.12095.36948
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.0.12095.36948
Azure Functions and Web Jobs Tools

C# Tools   3.0.0-beta2-19068-12+231aeb8be8357239499d45c0574e5a9a8c9174f0
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.0.19011.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Node.js Tools   1.5.1228.1 Commit Hash:ed08f6330182b40973804adaef05699c42c82f55
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.0.19011.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.0.19011.1
Conda support for Python projects.

Python - Django support   16.0.19011.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.0.19011.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.0.19011.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61901.07150
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta2-19068-12+231aeb8be8357239499d45c0574e5a9a8c9174f0
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 5f5e68099410f71fc13bb615b9a27abd055da6de.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VsVim   2.6.0.0
VsVim is a Vim emulator for Visual Studio

**Comment by jaredpar** [comment]
Sorry to hear you've seen this behavior. I've been using VsVim in VS2019 at work for several months now and haven't seen this behavior yet. Can you try re-installing VsVim and grabbing a dump file when the hang occurs? That should pinpoint what the issue is. 

https://support.microsoft.com/en-us/help/931673/how-to-create-a-user-mode-process-dump-file-in-windows

**Comment by ricksladkey** [comment]
VS2019 is now past the preview phase. Although the current version of VsVim in the extension gallery does support VS2019, that support will improve with the next version 2.7.0.

If you continue to experience any slowdowns and hangs with the current version of VS2019 and VsVim, and can collect a perf trace or a dump file, please add them to this issue and I'll re-open it.
