### ISSUE TITLE
map visual studio command ExpandSelectiontoContainingBlock

### ISSUE THREAD

**Issue by ntwo1980** [VsVim/VsVim#2470]
The following mapping doesn't work.

```
nmap <Leader>vv :vsc Edit.ExpandSelectiontoContainingBlock<CR>
```
Executing command `:vsc Edit.ExpandSelectiontoContainingBlock` in command line doesn't work either.

The VS version is 15.9.7

**Comment by jaredpar** [comment]
Can you elaborate a bit more on what you expect to happen here? Would help me understand if you had some sample text and explained what you expect this command to do.

**Comment by ntwo1980** [comment]
Edit.ExpandSelectiontoContainingBlock command is a new feature introduced in VS. It's used to selecting the containing block of current cursor.

``` javascript
for (var i = 0; i < lines.length; i++) {
    // Workaround for bounding box of empty lines and spaces
    if (lines[i].length > 0 && mxUtils.trim(lines[i]).length > 0) {
        var text = this.createElement('text');
        // LATER: Match horizontal HTML alignment
        text.setAttribute('x', this.format(x * s.scale) + 3); // changed
        text.setAttribute('y', this.format(cy * s.scale) + this.textOffset);

        mxUtils.write(text, lines[i]);
        node.appendChild(text);
    }

    cy += lh;
}
```

In case of above codes, if cursor is at `node.appendChild(text);`, the `if` block will be selected, if cusor is at `cy += lh;`, the whole `for` block will be selected. It's very useful to change or delete whole containing block.

**Comment by jaredpar** [comment]
Thanks. I see what the problem is.
