### ISSUE TITLE
Update FAQ re: disabling VsVim shortcut clashes

### ISSUE THREAD

**Issue by johnafc** [VsVim/VsVim#2474]
In Visual Studio 2017, the <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd> shortcut clashes with View.NextError's binding. After some searching I found the solution in #1981.

I think it would be helpful to mention this (or a generic "check key bindings" warning) in the [FAQ](https://github.com/jaredpar/VsVim/wiki/FAQ#how-can-i-temporarily-disable-vsvim). I tried editing the wiki page directly but could not find an edit button nor a way to fork it to do a PR against the wiki specifically. Let me know if there is a way for me to do this.

My proposal would be something like:

If the shortcut is not working for you, it is possible the key combination is bound to another command. To see which command is conflicting, and reassign/remove the binding:

1. Go to Tools -> Options -> Environment -> Keyboard.
2. Find a command that does not have a shortcut already assigned.
3. In the "Press shortcut keys" field, press <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd>
4. Check the "Shortcut currently used by" field, copy the name.
5. Paste the command name into the "Show commands containing" field to filter the list of commands.
6. Remove or reassign the key binding from the command.

**Comment by ricksladkey** [comment]
I added your suggested text to the FAQ. Thank you very much for contributing to the wiki.
