### ISSUE TITLE
No Ctrl-I or Ctrl-O option in VsVim keyboard options (VS 2019)

### ISSUE THREAD

**Issue by conormcg13** [VsVim/VsVim#2514]

**Comment by ricksladkey** [comment]
In my case, VsVim (head of master) with VS2019 does show them:

![image](https://user-images.githubusercontent.com/2680524/57034198-eba73a00-6c1c-11e9-9c47-6e8937647527.png)

![image](https://user-images.githubusercontent.com/2680524/57034235-037ebe00-6c1d-11e9-81f9-3a2f96645256.png)

Since VsVim does show them in some circumstances, we have to figure out why it isn't showing them in your circumstance.

Can you confirm that those keys are in fact bound to some other function in Tools -> Options -> Environment -> Keyboard?

**Comment by conormcg13** [comment]
Just checked, they aren't binded to anything. They appeared for me before but that was VS 2017 and I also vaguely remember them not appearing on VS 2017 so I'm not sure what is triggering it.

**Comment by ricksladkey** [comment]
The purpose of the VsVim keyboard configuration is to let you override Visual Studio key bindings that conflict with vim keys. Whether there is a Visual Studio key binding for a particular key depends on many factors. But if there is no Visual Studio binding, there is no conflict. As a result, that key should work correctly in VsVim without any intervention.

However, the most likely reason that you were expecting those keys to be in the VsVim keyboard configuration is that those keys were not working in VsVim as you expected. Do `<C-i>` and `<C-o>` work in VsVim?

**Comment by conormcg13** [comment]
Both keys do nothing in VsVim unfortunately.

**Comment by ricksladkey** [comment]
The keys `<C-o>` and `<C-i>` are definitely implemented in VsVim and should work if they are not bound to any other commands in Visual Studio.

My test sequence is to type `G1G` in any VsVim buffer to populate the jump table. Then typing `<C-o>` jumps to the end of the buffer and further typing `<C-i>` jumps back to the beginning.

At this point I am out of ideas.

**Comment by conormcg13** [comment]
I opened up VS2019 today and tested the keys and it's working as intended (I'm guessing they aren't showing the keys in VsVim because they aren't binded in VS possibly). Scratching my head at this but thank you for taking the time, will close issue.

**Comment by muchcharles** [comment]
@ricksladkey :
> My test sequence is to type `G1G in any VsVim buffer to populate the jump table.`

`ctrl-]` to jump to a definition in another file, followed by ctrl-o to return doesn't work for me.  Is the jump table in VsVim limited to one file?  Or maybe `ctrl-]` maps to a vs jump to definition function that doesn't populate the jump table?  `G1G` followed by `ctrl-o` does work for me, it also works after `gd` jumping to a local definition.
