### ISSUE TITLE
CTRL+WW (Switch Between Panes) broken on Visual Studio 2019

### ISSUE THREAD

**Issue by shuhkla** [VsVim/VsVim#2526]
Ctrl+WW used to work on VS2017, but now it does not work after upgrading to Visual Studio 2019 (16.0.3). Tried with both the stable (2.6.0.0) and the latest build (2.7.99.99 Debug).

**Comment by ricksladkey** [comment]
The <kbd>Ctrl</kbd>+<kbd>W</kbd> family of commands and in particular <kbd>Ctrl</kbd>+<kbd>W</kbd>,<kbd>W</kbd> definitely can work in VS2019; I just retested it with the latest build. The likely problem is that there is still a keyboard conflict with Visual Studio.

I've created a new specific issue for this general problem #2527 and referred to this issue there. Please try the workaround suggested in that issue.
