### ISSUE TITLE
Number increment (Ctrl+A) jumps over decimal numbers to next hex number

### ISSUE THREAD

**Issue by jmegner** [VsVim/VsVim#2529]
If you have a line with decimal and hex numbers....
`1  2  0x3  4  5  0x6  7  8`

Using Ctrl+A to increment numbers will move the cursor to the current/next hex number on the line and increment that hex number.  So, if your cursor is anywhere before the `0x3`, Ctrl+A will increment the 0x3 even if your cursor is at the 1 or 2.  It is impossible to use Ctrl+A to increment the 1, 2, 4, or 5 in the line above as is.  If your cursor is after the last hex number, you can use Ctrl+A to increment decimal numbers that are after the last hex number (thus 7 and 8 can be incremented by Ctrl+A as long as your cursor is after 0x6).

I've encountered this bug in Visual Studio Enterprise 2015 v14.0.25431.01 Update 3 and Visual Studio Enterprise 2017 v15.9.10; I'm using VsVim 2.6.0.0 in both.

**Comment by ricksladkey** [comment]
Ha, ha, I was just in this code the other day and didn't notice that problem. I'll take a look at it right way.

**Comment by jmegner** [comment]
Thank you so much for work on this wonderful tool and your prompt response.  I'm glad I could give a clear bug report.
