### ISSUE TITLE
List of supported features is out-of-date

### ISSUE THREAD

**Issue by ricksladkey** [VsVim/VsVim#2541]
The list of support features that is included in the repository, https://github.com/VsVim/VsVim/blob/master/Documentation/Supported%20Features.md, is out-of-date.

If it were up-to-date, when PRs were proposed that implemented new features, a review could request that it be documented in the list of supported features.

**Comment by sqlkoala** [comment]
Hi @ricksladkey 
I think I can do this (on weekends). Also, I thought about writing an Intro/Setup document ( getting vsvim to run productive after install. Topics: vimrc, keybindings vs visual studio)

**Comment by ricksladkey** [comment]
Wow, @sqlkoala, that would be fantastic.  Thanks for offering to help.

**Comment by jaredpar** [comment]
I think it would be good to get this back up to date and kept up to date going forward. Also think those can be done independently. Seems reasonable to request all PRs going forward keep it up to date with the commands being added in the PR. Separately we can start bringing the doc up to date with features that are missing.

**Comment by sqlkoala** [comment]
I have opened a fork with a branch. You can see my progress here (PR not ready yet):
https://github.com/sqlkoala/VsVim/pull/1

**Comment by sqlkoala** [comment]
I have extracted normal commands and operators from f# source ( wasn't much of a chore with vsvim ;-) and merged that with the document. Also added some paragraphs and edits, that I thought to be useful. I think this is something you can look at.
