### ISSUE TITLE
Suggest using template

### ISSUE THREAD

**Issue by TKumadaki** [VsVim/VsVim#2550]
For example, VsCodeVim has the following template.

**Bug report**
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

<!--
Ensure you are on the latest VSCode + VSCodeVim
You can use "Report Issue" by running "Developers: Show Running Extensions" from the Command Pallette to prefill these.
-->

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**
Add any other context about the problem here.
```
The following template is minimal. Still, I think this will help solve the problem.

```
**Environment (please complete the following information):**

- Visual Studio version:
- VsVim version:
- Programming Language:
- ReSharper is Installed:
- Visual Assist is Installed:
```

**Comment by jaredpar** [comment]
I agree we should add this and link to it from our CONTRIBUTING.md file. Thinking a short bit I think I'd go with the following template:



**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

- Visual Studio version:
- VsVim version:
- Programming Language:
- Check any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
Add any other context about the problem here.

**Comment by TKumadaki** [comment]
Checkboxes are useful if available.
:-)

**Comment by ricksladkey** [comment]
@jaredpar I think @TKumadaki means an issue template that is enforced in the same way as other GitHub projects, e.g.

- https://github.com/VSCodeVim/Vim/issues/new/choose

I don't have permission to adjust the VsVim repository settings and so I don't think I could take care of this by myself.

**Comment by TKumadaki** [comment]
I did not explain in detail.
What I would like to suggest is what @ricksladkey  is saying.

**Comment by ricksladkey** [comment]
I've never had to set up any issue templates, but apparently it isn't ultimately configured through the project settings, but through the presence of certain files within the repository itself as described [here](https://help.github.com/en/articles/creating-issue-templates-for-your-repository). That article describes a "wizard" like process, but all it does it create a PR with the files.

So the trick for any contributor to suggest issue templates is to turn on issues in their fork of VsVim, go to the repository settings for **their** fork, and then click "Set Up Templates" and choose to create a PR branch. That branch can then be submitted as a PR to the upstream VsVim repository (this one) and the issue templates will take effect when the PR is merged. The upshot is the @TKumadaki can create a PR for this and the discussion of what should be in the issue templates can be a normal discussion on the PR.

**Comment by TKumadaki** [comment]
I understood that thanks to @ricksladkey, I can create a PR for this.
I would like to work on the weekend.
