### ISSUE TITLE
navigation through Intelisense with tab key

### ISSUE THREAD

**Issue by 7c78** [VsVim/VsVim#2555]
Is it possible?

This question is unanswered for 3 years
https://stackoverflow.com/questions/35127328/cycle-visual-studio-intellisense-context-menu-using-tab

**Comment by ricksladkey** [comment]
I don't think this is currently possible in Visual Studio without writing an extension. Nor is it currently possible in VsVim, and I don't think there is any comparable capability in gvim that we are missing. I do think it is technically possible, but outside the VsVim's mission. But if you were to write an extension that accomplished it, it would be an impressive feat!
