### ISSUE TITLE
Format paragraph does not respect unix line endings

### ISSUE THREAD

**Issue by Loffe** [VsVim/VsVim#2561]
Using `gq` to format a block of text inserts windows line endings (CRLF), even though the file is in unix encoding (LF).

Expected behavior is to use the current line ending character.

Related issues: #621 #333

**Comment by ricksladkey** [comment]
I can reproduce this bug.

**Comment by ricksladkey** [comment]
Other operations that attempt, but may fail, to use the correct line endings:

- sort
- filter
- replace selection with character
- Putting text at the end of a buffer without a final newline
-

**Comment by ricksladkey** [comment]
To clarify, this actually works correctly if the line endings are being strictly enforced by an editor config setting.

For example, if there is an applicable [EditorConfig](https://editorconfig.org/) configuration file that says:

```
# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
```

Then the following code will properly set: `DefaultOptions.NewLineCharacterOptionId` and as a result, VsVim `EditorUtil.NewLine` will return `"\n"`:

* https://github.com/editorconfig/editorconfig-visualstudio/blob/master/src/EditorConfig.VisualStudio/Logic/Settings/LocalSettings.cs
