### ISSUE TITLE
Unit tests pause for several minutes after completing

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2563]
The unit tests will pause for around ~5 minutes after completion. Specifically what happens is we get to the summary line of xunit but the process won't exit for several more minutes after.

```
=== TEST EXECUTION SUMMARY ===
   Vim.Core.UnitTest  Total: 7, Errors: 0, Failed: 0, Skipped: 0, Time: 3.063s
```

Debugged into this a bit and what is happening is xunit is stuck unloading the `AppDomain` which was used for testing. The `AppDomain` won't exit because threads currently executing in that `AppDomain` are still running. Specifically the [following code](https://github.com/VsVim/VsVim/blob/master/Src/VimTestUtils/Utilities/StaContext.cs#L49) in `StaContext` is still executing:

```
Dispatcher.Run();
```

What is truly odd though is that eventually this exits. The underlying message pump is torn down after a few minutes. I can't find an explanation of why that happens and none of the runtime guys I asked can explain it either. 

Options I've tried that will not work:

- Call `Dispatcher.BeginInvokeShutdown` in `AppDomain.CurrentDomain.DomainUnload`. By this time the underylying `HWND` handle has been finalized hence the internal message calls fail.
- Use `StaContext.Dispose` to tear down the `Dispatcher`. This doesn't work either because this value is not disposed in time.

I'm looking into other ways of terminating the `Dispatcher` gracefully here. Probably need to find another xunit extensibility point to hook. 

Simplest possible repo for this I've found is the following:

> Tools\xunit.console.x86.exe Binaries\Debug\VimCoreTest\net472\Vim.Core.UnitTest.dll -class Vim.UnitTest.AdhocOutlinerTest

Note: Discussion on this originally began on #2557.

**Comment by jaredpar** [comment]
One potential approach is leveraging the `ITestFramework` extensibility point. This allows us to hook xunit at the most fundamental level. The implementation can be done though by essentially deriving from the standard xunit implementation and forwarding all the method calls to it. The one change we'd need to make is shutdown the `Dispatcher` in the `Dispose` method before calling into the base implementation. 

This approach has a couple of downsides to consider:

- Have to mark each of our test assemblies with a `[TestFramework]` attribute (trivial)
- Have to maintain some more xunit plumbing code (appears pretty small) 
- This breaks the ability to discover unit tests by name. That means in order for tests to show up in test explorer we'd have to complete a build. 

The last part is the most significant. My for own uses of Test Explorer that's not going to be a blocker. But I also haven't done this yet so I don't have any direct experiences with the flow here. 

Example implementation you can look at is available here: https://github.com/josetr/VsixTesting/blob/3cc0e356cbeca90e5e280fc9854edabed1621726/src/VsixTesting.Xunit/VsTestFramework.cs

**Comment by ricksladkey** [comment]
Thanks for filing this issue. I was fully intending to look into this myself, but after the 2.7.0 release, which I didn't want to delay.

The one thing I do have to add to your collection of symptoms above is that if the debugger and you have exceptions turned on, you will see a ThreadTerminateException (or whatever it is). My assumption was that some one or something has a timeout of that long before it kills it. I was guessing it is XUnit but we don't see any XUnit in the call stack because of the app domains.

It did not occur to me at the time to enable mixed-mode debugging, but it seems you already tried that and determined that it is not XUnit that is timing out.

**Comment by jaredpar** [comment]
I was able to figure out how to fix this. The root problem is that the `Dispatcher` instance needs to be shutdown gracefully in order to tear down the message loop, HWND and the STA thread object. The `ITestFramework` gave the appropriate hook for making that happen.

I'm still unsure why the ~5 minute hang was happening. Asked around and it stumped everyone else as well. The most straight forward implementation is somewhere in Win32 or .NET there is a timeout inserted for message loop where the HWND is destroyed. But I also can't find any evidence something like that occurs. 

Either way though this problem appears to be fixed now with the change.
