### ISSUE TITLE
% motion failing if there's an ' on the same line as a match

### ISSUE THREAD

**Issue by spaceyjase** [VsVim/VsVim#2566]
Seems like vsvim % motion is confused by this:

```
            if (done)
            { // we're done
		Done();
            }
```

Place the cursor on the opening brace, hit % and it'll jump to the match. Hit % again and it won't jump back. Remove the ' in "we're" and it's fine. Also works if the comment is on a new line.

If this is in further context, it'll gradually jump out to the parent (and beyond).

**Comment by jaredpar** [comment]
Thanks for reporting. Can confirm this behavior and deviation from gVim.

**Comment by ricksladkey** [comment]
I reworked the token matching code not too long ago and so I know this is clearly meant to be a supported case. I'll try to get to the bottom of this.
