### ISSUE TITLE
Possible exception calling Caret.ContainingTextViewLine

### ISSUE THREAD

**Issue by ricksladkey** [VsVim/VsVim#2583]
I have encountered numerous occurrences of Visual Studio 2019 exception reports such as the following:

```xml
  <entry>
    <record>1354</record>
    <time>2019/05/31 01:39:46.151</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
System.InvalidOperationException: Unable to get TextViewLine containing insertion point.&#x000D;&#x000A;
   at Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.get_ContainingTextViewLine()&#x000D;&#x000A;
--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
    </description>
  </entry>
```

Because the stack trace is so truncated it is impossible to say whether the exceptions are caused by VsVim (see related [Visual Studio bug](https://developercommunity.visualstudio.com/content/problem/566964/exceptions-caught-and-handled-by-extensions-are-st.html)).

In order to determine whether VsVim is in fact the cause, all cases of calls to this method should either be eliminated or instrumented to show definitively whether VsVim was in the call stack when an exception like the above is reported in the activity log.

**Comment by ricksladkey** [comment]
For the record, `ICaret.ContainingTextViewLine` does in fact eventually call `ITextView.GetTextViewLineContainingBufferPosition` which is documented to possibly result in the text view performing a layout. As an isolated call there is no harm in this side effect, but in the context of working with several text view lines at the same time (as VsVim does during scrolling), it can invalidate (i.e. `Dispose`) any other text view lines that we have references to.

As a result, it is much safer to call `ITextViewLineCollection.GetTextViewLineContainingBufferPosition` with the position of the caret (which is always safe to retrieve). Unlike the identically named method on `ITextView`, this method simply returns null if there is no text view line that contains the point. Furthermore, it never causes a layout.

The moral of this story is that [numerous bugs](https://github.com/dotnet/fsharp/issues/6056) in Visual Studio itself are ultimately due to misunderstanding this difference and the attendant risks in calling either `ICaret.ContainingTextViewLine` or `ITextView.GetTextViewLineContainingBufferPosition`.

From the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.editor.iwpftextview.gettextviewlinecontainingbufferposition?view=visualstudiosdk-2019) for the latter:

> #### Remarks
> This method returns an IWpfTextViewLine if it exists in the view.
> 
> If the line does not exist in the cache of formatted lines, it will be formatted and added to the cache.
> 
> **The returned IWpfTextViewLine could be invalidated by either a layout by the view or by subsequent calls to this method.**

(emphasis added)

**Comment by jaredpar** [comment]
> Because the stack trace is so truncated it is impossible to say whether the exceptions are caused by VsVim (see related Visual Studio bug).

I'm hopeful this problem will be fixed soon in Visual Studio. I've been following the bug and PRs to fix it are in progress. Hoping they will make it out soon.
