### ISSUE TITLE
v2.7.0.0 - vimrc errors reported despite setting being off

### ISSUE THREAD

**Issue by philipmat** [VsVim/VsVim#2585]
**Describe the bug**
VsVim reports vsvimrc errors in Visual Studio 2019 despite "VimRc Error Reporting" being False in settings.

**To Reproduce**

0. Ensure "VimRc Error Reporting" is set to False
1. Load Visual Studio 2017, 2019 with a project
2. Open file from the Solution Explorer
3. VsVim reports errors in sourced `vimrc`

or

0. Ensure "VimRc Error Reporting" is set to False
1. Ensure a file is open in Visual Studio 2017, 2019
2. Close and reopen Visual Studio 
3. Notice the bottom bar reports errors in sourced `vimrc`

**Expected behavior**
Expected the errors to not be reported because of the "VimRc Error Reporting" settings being False.

**Screenshots**
![20190531-124505 599_%pn](https://user-images.githubusercontent.com/709928/58724824-3397b900-83a3-11e9-96de-06d9b5a3fd06.png)

**Environment (please complete the following information):**

- Visual Studio version: 2019 - v16.1.1 and 2017 - v15.9.10
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note that this doesn't seem to happen with VsVim v2.6.0.0.

**Comment by ricksladkey** [comment]
Oops, @philipmat, that was my bad. I didn't even know about that option! I will get that fixed.

**Comment by ricksladkey** [comment]
But, I hope you like the line numbers in the errors!

**Comment by philipmat** [comment]
I really did like that. Any chance on expanding the other message to include the line number?

    Unknown option on line 23: numberwidth

**Comment by ricksladkey** [comment]
@philipmat I thought I had gotten all the places where an error was generated but apparently not. Admittedly I wasn't testing on a large rc file with plenty of errors!
