### ISSUE TITLE
Imap to delete <del> does not work (anymore)

### ISSUE THREAD

**Issue by sqlkoala** [VsVim/VsVim#2608]
Hi, I noticed a small glitch.

**Describe the bug**
I used to map Ctrl+L to Delete in insert mode. In 2.7, this does not work anymore.

**To Reproduce**
Do
`inoremap <c-l> <del>`
It does not work as expected. Mapping c-l to backspace works, so i think it is specific to del key.

**Environment (please complete the following information):**
- Visual Studio version: 2017 Community
- VsVim version: 2.7

**Additional context**
My guess is that happened with this PR
https://github.com/VsVim/VsVim/pull/2438/

Because up till now I used the build from here, where it worked
https://github.com/VsVim/VsVim/pull/2437/commits
And the oldest build on appveyor that I still can get (Jan 2019) has it too.

**Comment by sqlkoala** [comment]
Hi @ricksladkey  ;-)
btw. I dont get the issue/problem in (#2313).
A simple 
`noremap nn $`
will do, I see no need for this complicated right hand side of the map.

**Comment by ricksladkey** [comment]
@sqlkoala, the problem in issue #2313 is that VsVim behaved differently than vim. Even though the simpler RHS is undeniably clearer and in every way a better mapping, vim allows the more complicated mapping and so must we.

**Comment by ricksladkey** [comment]
@sqlkoala, I am sorry about introducing a regression trying to fix another problem that was arguably not that important!

In any case, as you are a long-time user with a sharp eye and a close connection with the project, I would be very grateful it if you would subscribe the vsixgalley feed. That way, if you notice a regression, it will be much more obvious which PR caused it. In this particular case you did the legwork to identify the PR that introduced the problem, and your analysis was in fact correct, but having more users using the nightly builds can only improve the less frequent periodic releases.

**Comment by sqlkoala** [comment]
Hi @ricksladkey 
Thanks for the quick fix, I dl'ed the build and it works. Don't feel bad about the regression, you have added many powerful features that help me daily.
I will use latest builds from vsixgallery on my home system.
