### ISSUE TITLE
VS 2019 : Exception on start

### ISSUE THREAD

**Issue by QM-OSchwab** [VsVim/VsVim#2646]
Hey all,

VsVim is not working on my VS 2019 installation.
At startup, VS displays a SystemArgumentException banner.

Log file contains several time the same error :

1830 | ERROR | **System.ArgumentException: <Plug> is an invalid key notation** Nom du paramètre : **data**   à Vim.KeyNotationUtil.StringToKeyInput(String data)   à <StartupCode$Vim-Core>.$Interpreter_Parser.inner@1627-32(Parser x, StringBuilder builder, Boolean afterEscape)   à Vim.Interpreter.Parser.ParseStringConstant()   à Vim.Interpreter.Parser.ParseSingleExpression()   à Vim.Interpreter.Parser.ParseExpressionCore()   à Vim.Interpreter.Parser.ParseLet()   à <StartupCode$Vim-Core>.$Interpreter_Parser.doParse@2460-36.Invoke(Unit unitVar)   à <StartupCode$Vim-Core>.$Interpreter_Parser.doParse@2412(Parser x, LineRangeSpecifier lineRange, String name)   à Vim.Interpreter.Parser.ParseSingleLine()   à Vim.Interpreter.Parser.ParseSingleCommand()   à Vim.Interpreter.ConditionalParser.Parse()   à Vim.Interpreter.Parser.ParseIf(Expression expr)   à Vim.Interpreter.ConditionalParser.Parse()   à Vim.Interpreter.Parser.ParseIf(Expression expr)   à Vim.Interpreter.Parser.ParseFunction(FSharpOption`1 functionDefinition)   à Vim.Interpreter.Parser.ParseSingleCommand()   à Vim.Interpreter.ConditionalParser.Parse()   à Vim.Interpreter.Parser.ParseIf(Expression expr)   à Vim.Interpreter.VimInterpreter.RunScript(String[] lines)   à Vim.Interpreter.VimInterpreter.Vim-Interpreter-IVimInterpreter-RunScript(String[] lines)   à Vim.Vim.LoadVimRcCore()   à Vim.Vim.LoadVimRc()   à Vim.Vim.MaybeLoadFiles()   à Vim.Vim.GetWindowSettingsForNewBuffer()   à Vim.Vim.TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer& vimBuffer)   à Vim.Vim.Vim-IVim-TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer& vimBuffer)   à Vim.UI.Wpf.Implementation.MarkGlyph.MarkGlyphTaggerSourceFactory.Microsoft.VisualStudio.Text.Tagging.IViewTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer textBuffer)   à Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.InstantiateViewTagger(ITextView textView, Lazy`2 factory, ITextBuffer textBuffer, IList`1 newTaggers)

Going in Tools->Options ->VsVim->Keyboard displays a  blank page with error message.

**Environment :**

- Visual Studio version: 2019 Pro
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
Windows base language is french ; added english US as additional language for display; VS is in french

Thanks by advance for help

**Comment by ricksladkey** [comment]
This is probably caused by a line like this in vim rc file:

```
let variable = "\<Escape>"
```

or some other variety of invalid vim key notation. In this example, the real key name is `<Esc>` and `<Escape>` is not any key.

In this situation vim will use the string value literal string value `<Escape>`, but VsVim mishandles that and throws an exception.

I've fixed the problem in PR #2648 and you can get the fix after that PR is merge by using the nightly builds. Other workarounds could be:

1. Find the offending line in your vm rc file and fix the syntax
2. Add a vsvim rc file and only put commands in it that are appropriate for VsVim

**Comment by QM-OSchwab** [comment]
OK, my bad , I use [spf13-vim](http://vim.spf13.com/) for gvim, and this wasn't causing any problem on my previous PC . So I 
- restored vimrc before spf13 install
- choose 'vsvimrc' as file for vsvim settings

Now all seems OK. Just wonder why spf13 is no longer compatible with vsvim, but I don't have time to dig more for now.

Thanks you very much for help !

**Comment by tankorsmash** [comment]
This solved my issue on VS2013 as well, I had the line

```vim
     execute "normal \<Plug>SumNum"
```

and commenting it out solved the issue for me too. Maybe there's a conditional I can use to check if VsVim is running to disable it there.
