### ISSUE TITLE
Support for :cabbrev command

### ISSUE THREAD

**Issue by sporifolous** [VsVim/VsVim#2652]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [ ] Vim
    - [x] Vim plugin

**Is your feature request related to a problem? Please describe.**
Would love to have support for the [`:cabbrev`](http://vimdoc.sourceforge.net/htmldoc/map.html#:cabbrev) command. There's a certain command I never intentionally use, but sometimes accidentally use due to a mistype, and I'd like to just disabled it essentially by using `:cabbrev` to map it to the intended command.

**Describe the solution you'd like**
The ability to abbreviate a command with `:cabbrev`

**Describe alternatives you've considered**
I've tried `:cmap` but that doesn't really accomplish the same thing (or work at all for my use case)

**Comment by jaredpar** [comment]
Thanks for filing this. Going to fold this into issue #702. That is the more general abbreviations feature but it will include the sub-commands like `cabbrev`. 

Know that issue is fairly old but I've actually recently begun working on it. Hoping to make it a part of the 2.8 release.

**Comment by sporifolous** [comment]
That's awesome to hear. Thanks for your hard work!
