### ISSUE TITLE
Integrated multiple caret support

### ISSUE THREAD

**Issue by ricksladkey** [VsVim/VsVim#2656]
The popularity of multiple cursors appears to have started with (or perhaps gained traction in) the Sublime editor:

- https://www.sublimetext.com/docs/3/multiple_selection_with_the_keyboard.html

Visual Studio Code also provides multiple cursors very much in the style of Sublime:

- https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

Later versions of Visual Studio 2017 and all versions of Visual Studio 2019 support multiple carets and multiple disjoint selections. Visual Studio itself has some limited support for using multiple carets to edit files, specifically the <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>.</kbd> command which adds a new selection at the next occurrence of the current word. In native selection mode, this allows you to type over a new name for multiple separate identifiers at the same time.

Although Vim 8.0 does not have built-in support for multiple cursors, there are many plugins that provide varying versions of this capability, most notably:

- https://github.com/terryma/vim-multiple-cursors

The interesting thing about multiple cursors is that, except for the process of creating them, using them is very intuitive. Any casual Vim user could guess that if you can see multiple cursors and type in a normal mode command, the same command should apply at each of the cursors. Likewise, in insert mode, if you have multiple cursors, the user intuitively expects what is typed to be inserted at each of the cursors.

Some people argue that multiple cursors are unnecessary in Vim because Vim provides a variety of powerful ways to rapidly act on isolated sections of text, most notably but not limited to the repeat command. However, upon reflection, there is one powerful argument for multiple cursors in Vim:

- Any time that the best way to accomplish a text transformation in several places would be to record and use a temporary macro, that same task could be probably be performed more easily and intuitively with multiple cursors

As any one who has ever used Vim macros can tell you, it can be hard to execute the key sequence perfectly during recording, often resulting in several failed attempts before the perfect version that is repeatable so that it achieves the desired effect. And the longer the macro, the more work that is involved and the more likely there is to be a mistake. But, if you could **see** the "macro" playing out in real-time in the other places that you intend to apply the macro, you could bypass this two step process. This rationale does not apply to general-purpose non-temporary macros. For those cases, a macro is the preferred and tried-and-true method.

Whether you think Vim should or should not support multiple cursors, it must be conceded that multiple cursors are wildly popular and quickly becoming a "de rigueur" feature for a modern editor. Even if your editor supports them, you don't have to use them if you don't want to. However, if you do want to use them, your editor has to support them.

N.B.: Vim uses the term "cursor" for the insertion point in the editor, whereas Windows traditionally reserves the word "cursor" for the mouse and uses "caret" for the insertion point. In the VsVim code base the word "caret" is used systematically because all the editor APIs use that terminology. For most purposes, "cursor" and "caret" can be used interchangeably without confusion.

**Comment by jaredpar** [comment]
> Likewise, in insert mode, if you have multiple cursors, the user intuitively expects what is typed to be inserted at each of the cursors.

How does this differ from a block selection with insert? 

> Any casual Vim user could guess that if you can see multiple cursors and type in a normal mode command, the same command should apply at each of the cursors. 

One part that isn't intuitive for me here is how do you exit multiple cursor mode? When there is a multi-select in normal mode, then I execute a command is the result a single selection or multi-selection?

> Later versions of Visual Studio 2017 and all versions of Visual Studio 2019 support multiple carets and multiple disjoint selections. 

How much easier would this feature be if we did away with VS2017 support? Does it make the change significantly easier? 

Not saying we should do that yet. But if it made the change considerably easier then it may be worth considering putting it in VsVim 3.0 and removing VS2015 support at that time.

**Comment by jaredpar** [comment]
BTW. I’m really curious to see how this works implementation wise. The idea of a single caret is fairly hard coded into parts of the code. Not sure the best way to make them support multiple carets

**Comment by ricksladkey** [comment]
> How does this differ from a block selection with insert?

In two ways:

1. The text is inserted "live" at all the carets; it is not delayed until after insert mode ends
2. The carets don't need to vertically aligned or even on adjacent lines

The former is very much like what happens with `F2` rename. You can see for yourself the native capability in VS2019 like this:

- Disable VsVim
- Drop a couple additional carets with shift-alt-click
- Start typing and see new text at all carets
- Remove the carets with escape

> One part that isn't intuitive for me here is how do you exit multiple cursor mode? When there is a multi-select in normal mode, then I execute a command is the result a single selection or multi-selection?

Following the model of Sublime, VSCode, and Visual Studio itself, typing escape cancels multiple cursor mode. For VsVim, typing `<C-c>` in insert, visual or nomral mode cancels multiple cursors or typing `<Esc>` in normal mode also cancels multiple cursors. At least that's how I have it working now. So if you are in insert mode and want to cancel multiple cursors, you can type escape twice or type control c once. In either case you end up in normal mode.

> How much easier would this feature be if we did away with VS2017 support? Does it make the change significantly easier?

The implementation currently accesses multiple cursors via two new get / set methods on `IVimHost`. The existing VsSpecific assemblies handle multiple Visual Studio versions with no real complication. Once VS2015 support is dropped, all of that re-vectoring code can go away and the only VimCore code that changes is a couple of methods in common operations.

**Comment by ricksladkey** [comment]
> BTW. I’m really curious to see how this works implementation wise. The idea of a single caret is fairly hard coded into parts of the code. Not sure the best way to make them support multiple carets

I've include some documentation to give you an overview. I will continue adding to it. It's basically done!

- [Documentation/Multiple Selections.md](https://github.com/VsVim/VsVim/blob/3db809d04d7232e1edd6cd360684a1ba93029b94/Documentation/Multiple%20Selections.md)

**Comment by ricksladkey** [comment]
It turns out that VSCodeVim supports multiple cursors:

- https://github.com/VSCodeVim/Vim/pull/811

It looks like most of the design choices are the same as what we ended up with in my PR.
