### ISSUE TITLE
Caret sized incorrectly at end of line following Code Lens annotation Visual Studio 2019

### ISSUE THREAD

**Issue by IvanNazarov** [VsVim/VsVim#2657]
The caret is sized incorrectly in Visual Studio 2019 if the cursor is placed at the end of a line that precedes a Code Lens annotation:
![VsVimCursorBug](https://user-images.githubusercontent.com/22483501/60079424-91b38400-9736-11e9-9408-b46b1cd2b2cc.JPG)

VsVim version: 2.8.226

**Comment by ricksladkey** [comment]
Ha, ha, I found an even more giant caret in issue #2649! I hope to fix the problem shortly.

**Comment by ricksladkey** [comment]
P.S. I recommend a darker color for the block caret foreground, which makes the character under the caret easier to see:

![image](https://user-images.githubusercontent.com/2680524/60109991-58304800-9739-11e9-8a1a-33d11b96af1b.png)
