### ISSUE TITLE
Rename keeps focus with the Rename dialog

### ISSUE THREAD

**Issue by philipmat** [VsVim/VsVim#2659]
**Describe the bug**
Rename enters insert more but keeps focus with the Rename dialog. As a result, typing "a" causes the "Apply" button to trigger before typing is complete.

**To Reproduce**

1.  Select a variable and press `F2`
2.  Try renaming to something that contains "a", for example: `fooBar`
3.  The variable gets renamed to `fooB` because the "a" triggers the "Apply" button

**Expected behavior**
Be able to rename variables.

**Environment (please complete the following information):**

- Visual Studio version: 2019 (v16.1.3)
- VsVim version: 2.7.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
Other keys also trigger options on the rename dialog; for example, "c" triggers the rename in comments option.

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by philipmat** [comment]
Could this be related to #2363 and #2427?

**Comment by ricksladkey** [comment]
I cannot reproduce this behavior. It doesn't make sense to me that typing <kbd>a</kbd> would cause "Apply" to be pushed. Normally (and I tested this with the C# rename dialog), you must also press the <kbd>Alt</kbd>, e.g. <kbd>Alt</kbd>+<kbd>A</kbd>. Notice the underlined characters in the dialog:

![image](https://user-images.githubusercontent.com/2680524/60310758-4067e800-9922-11e9-83d3-2ea3994f2d20.png)

As a result, the characters 'c', 's', and 'p' should therefore behave similarly.

I cannot think of a reason that this symptom would only sometimes occur.

**Comment by philipmat** [comment]
A restart seemed to fix it for me. It was odd and it didn't make much sense for me either -- wish I had captured a video of it happening.

Nevertheless, thank you Rick for the great work.
