### ISSUE TITLE
Pressing 'A' when in Visual Block mode moves caret to wrong position

### ISSUE THREAD

**Issue by nosami** [VsVim/VsVim#2667]
**Describe the bug**
The caret should move to the right of the block, not the end of the line.

**To Reproduce**

1.  Select a block of text in Visual Block mode
2.  Press 'A'
3.  The caret is in the wrong position.

**Expected behavior**
![visualblock](https://user-images.githubusercontent.com/667194/60502315-7f48c580-9cb5-11e9-8ea5-79b2644b528a.gif)

**Screenshots**

 ![visualblockVS](https://user-images.githubusercontent.com/667194/60502457-c931ab80-9cb5-11e9-8ebe-d97110289f54.gif)

**Environment (please complete the following information):**

- Visual Studio version: 15.8.7
- VsVim version: 2.7.0.0
- Programming Language: C# but probably any
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by ricksladkey** [comment]
I can reproduce this bug.

For reference, block insert and append are described in this section of the manual:

- `:vimhelp blockwise-operators`
