### ISSUE TITLE
i_CTRL-P, i_CTRL-N only show popup but do not fill completion in VS2019

### ISSUE THREAD

**Issue by tiansh** [VsVim/VsVim#2669]
**Describe the bug**
Hitting <kbd>Ctrl-N</kbd>, <kbd>Ctrl-P</kbd> in insert mode should complete the word without another <kbd>Tab</kbd> required.

**To Reproduce**
```
abcd
abcc
abc
```

1.  Corsur on last character `c`;
2.  Hit <kbd>CTRL-N</kbd>;

**Expected behavior**
Third line should be abcd and a popup to select abcd or abcc;

**Screenshots**
gVim:
![vim-complete](https://user-images.githubusercontent.com/6500326/60648752-eae08d80-9e83-11e9-8038-93fb12021617.png)
VsVim:
![vsvim-complete](https://user-images.githubusercontent.com/6500326/60648753-eb792400-9e83-11e9-918d-6fd709491f49.png)

**Environment (please complete the following information):**

- Visual Studio version: VS2019 (16.1.4)
- VsVim version: 2.7.0.0
- Programming Language: Any (HTML in above example)
- Check(Type 'x') any that are installed: 
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by sqlkoala** [comment]
Hi, this a change you mostly notice with VS2019 ans vsvim 2.7.
It is already solved here:
https://github.com/VsVim/VsVim/pull/2654

If you want, you can try the latest build here. The fix will be included in one day:
http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/
