### ISSUE TITLE
Error writing to unnamed register with let

### ISSUE THREAD

**Issue by orccrusher99** [VsVim/VsVim#2680]
I'm having trouble using the tips from this page (https://vim.fandom.com/wiki/Comfortable_handling_of_registers) on VsVim, and I'm pretty sure this command is the root of the issue:

`:let @"=@a`

When I run just that line in my VsVim, it gives an error:

`Error on line 1: Invalid register name`

Considering that switching the registers works (`let @a=@"`), it seems to be an issue with writing to the unnamed register using the let command in VsVim. Or just an issue/misunderstanding on my end. Can someone else confirm?

**Comment by ricksladkey** [comment]
Thanks for filing a detailed report. This bug was recently fixed in PR #2600. If you want the fix right way you can switch to the nightly build:

- https://github.com/VsVim/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources
