### ISSUE TITLE
Mapping <Left> produces invalid characters

### ISSUE THREAD

**Issue by reavessm** [VsVim/VsVim#2683]
**Steps to reproduce the behavior:**

1.  Paste `inoremap foo <Esc>:%s/bar//g<Left><Left>` in _vimrc
1.  Source, if necessary
1.  In insert mode, type `foo`
1.  See `%s/bar//g[][]` in command window, where [] is an invalid character

**Expected behavior**
We expect to see `%s/bar//g` in the command window with the cursor two spaces from the right

**Environment (please complete the following information):**

- Visual Studio version: 14.0.25420.01
- VsVim version: 2.7.0.1
- Programming Language: X++
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
Thanks for filing this issue! This issue is a duplicate because there is already an older open issue #1103 for the problem. I have already started looking into how to fix this problem and I will hopefully have a PR ready soon.

**Comment by reavessm** [comment]
This is an exact duplicate, sorry about that haha but thanks for working on it!

**Comment by ricksladkey** [comment]
Your issue definitely reminded me that I had thought about (but hadn't solved) the other issue, and so now it has bubbled up to a higher priority!

**Comment by ricksladkey** [comment]
I reopened this issue because it describes a separate problem not reported in the other issue: the invalid characters.
