### ISSUE TITLE
Development builds inadvertently being published to the Open VSIX Gallery

### ISSUE THREAD

**Issue by ricksladkey** [VsVim/VsVim#2685]
For reasons that I don't fully understand, some development builds, that is builds not merged into the VsVim master branch, are being published to the Open VSIX Gallery. As a result, using the Open VSIX Gallery VsVim feed no longer ensures that you get the build corresponding to the head of the master branch.

Here is an example of a build that was published to the Open VSIX Gallery that was not merged into the master branch:

- https://dev.azure.com/VsVim/VsVim/_build/results?buildId=271&view=logs

In fact, the corresponding unit test jobs failed for that build.

**Comment by jaredpar** [comment]
That definitely shouldn't be happening. Attempted to account for that when I moved us to Azure DevOps but looks like I didn't get it quite right. Looking into it.

**Comment by ricksladkey** [comment]
Closed by #2686
