### ISSUE TITLE
Use of `%` with interpolated strings in c#

### ISSUE THREAD

**Issue by canro91** [VsVim/VsVim#2691]
In an interpolated string , when hitting `%` in the opening `"` it goes to the opening `{`, instead of going to the closing `"` 

**To Reproduce**

Given this line of code `$"{someVar}"`

In normal mode:
1.  Go to the first `"`: `f"`
2.  Hit `%`
3.  It places the cursor in `{`, instead of the closing `"`

**Expected behavior**
After hitting `%`, VsVim should place the cursor in the closing `"`

**Environment:**

- Visual Studio version: 16.1.1
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
It relates to #2666

**Comment by ricksladkey** [comment]
In Vim (and VsVim), the `%` command does not operate on double quote characters. Quoting from `:vimhelp %`:

```
							*%*
%			Find the next item in this line after or under the
			cursor and jump to its match. |inclusive| motion.
			Items can be:
			([{}])		parenthesis or (curly/square) brackets
					(this can be changed with the
					'matchpairs' option)
			/* */		start or end of C-style comment
			#if, #ifdef, #else, #elif, #endif
					C preprocessor conditionals (when the
					cursor is on the # or no ([{
					following)
```

Unless I am misunderstanding the situation, VsVim behaves exactly like Vim for the specific interpolated string that you use as an example, which doesn't depend on the fact that it is an interpolated string.

Vim does have support for double-quote as matched tokens using, e.g., `vi"` or `va"`, but even those operators work the same in VsVim as in Vim for this example.
