### ISSUE TITLE
Cursor / Caret missplaced highlighted Char

### ISSUE THREAD

**Issue by Adrian-Grimm** [VsVim/VsVim#2697]
**Description**
The blinking cursor hightlight is misplaces in highlighted state.
It's only when the cursor is on a method or function line in the code.

**To Reproduce**
I think it only appears if some lines are smaler than others (plugin to reduce comments in size).
If so...:

1. Place the cursor on a function or method line

**Expected behavior**
Normal blinking cursor/caret effect without missplaced highlighted char.

**Screenshots**
![image](https://user-images.githubusercontent.com/5657002/61719689-ab5fdf80-ad65-11e9-8079-d03651eeeb88.png)

**Environment (please complete the following information):**
- Visual Studio version: 15.9.13
- VsVim version: 2.8.1550
- Programming Language: C#
- Check(Type 'x') any that are installed: 
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
Thank you for filing a detailed bug report. This problem was previously reported in issue #2649 and was fixed in PR #2681.

If you want the fix immediately, you can upgrade to the latest nightly build:

- https://github.com/VsVim/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources

**Comment by Adrian-Grimm** [comment]
> Thank you for filing a detailed bug report. This problem was previously reported in issue #2649 and was fixed in PR #2681.
> 
> If you want the fix immediately, you can upgrade to the latest nightly build:
> 
> * https://github.com/VsVim/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources

Thx for your help - i can confirm - it's working with the nightly =)
