### ISSUE TITLE
nnoremap * *``  has dead loop

### ISSUE THREAD

**Issue by XiaoXiaoLui** [VsVim/VsVim#2699]
**Describe the bug**
" following map seems to be recursive map
nnoremap * *``

**To Reproduce**
1.map * to "``  
  
nnoremap * *`` 
2.press * at a word, and Vs gets stucked.

**Expected behavior**
vsvim start to search word under cursor without jumping to next match.

**Environment (please complete the following information):**
- Visual Studio version: 2019 community
- VsVim version: 2.7.0.0
- Programming Language: cpp

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by ricksladkey** [comment]
Hmm, I cannot reproduce this problem, with either VsVim 2.7.0 or the head of master.

I tested:

```
noremap * *``
```

after which typing `*` produces no visible effect unless the word under the cursor is the last occurrence of the word in the file, in which case it prints in the status line:

```
search hit BOTTOM, continuing at TOP
```

Further use of the motions `n` and `N` do the appropriate thing and typing `/<C-p>` brings up the word being search for.

**Comment by XiaoXiaoLui** [comment]
> Hmm, I cannot reproduce this problem, with either VsVim 2.7.0 or the head of master.
> 
> I tested:
> 
> ```
> noremap * *``
> ```
> 
> after which typing `*` produces no visible effect unless the word under the cursor is the last occurrence of the word in the file, in which case it prints in the status line:
> 
> ```
> search hit BOTTOM, continuing at TOP
> ```
> 
> Further use of the motions `n` and `N` do the appropriate thing and typing `/<C-p>` brings up the word being search for.

I had a try and  coudn't reproduce it either and try to figure out why.  
Sorry, I think I made a mistake yesterday,
 I may have following line  which caused the problem instead of what this title says.
" nnoremap * :keepjumps normal *``<cr>
" keepjumps not supported in vsvim and I delete it to have following map
nnoremap * :normal *``<cr>

The above map  has dead loop in gvim, though gvim can realize it and stop it without being stucked.
This issue can be closed now, sorry for my mistake.

**Comment by ricksladkey** [comment]
I am glad you solved your problem and I thank you for filing a detailed bug report. Good luck!
