### ISSUE TITLE
Arrow keys don't work in intellisense window

### ISSUE THREAD

**Issue by jira-zz** [VsVim/VsVim#2701]
With vsvim arrow key don't work in intellisense window. I have then assigned to Edit.LineDown and Edit.LineUp, but still there is no way to go through the completion list.

VS2019
vsvim 2.7.0.0

**Comment by ricksladkey** [comment]
Can you give more details about what kind of intellisense window you are talking about? Which language service is involved (e.g. C#, C++, Python, etc.) and which keystroke or action brings up the intellesense choices (`<C-n>`, etc.)?

**Comment by ricksladkey** [comment]
For all the examples I tried, the arrow keys work correctly in the intellisense popup window.

**Comment by jira-zz** [comment]
I'm talking about the list of suggestions that comes up automatically as I type. See attached screenshot.
![vs_intellisense](https://user-images.githubusercontent.com/444428/62285509-070d2580-b456-11e9-8982-59a38c0a9996.png)

Without vsVim I can use arrow keys to navigate, with vsVim arrow keys don't work.

**Comment by jaredpar** [comment]
>  I have then assigned to Edit.LineDown and Edit.LineUp, but still there is no way to go through the completion list.

Can you clarify this a bit. Do you mean that you have the arrow keys assigned to those functions in Visual Studio? If so then likely Visual Studio owns those key strokes and VsVim is never seeing them. 

Could you attache the Output Window log when this happens? That will give us a more detailed view of where the key stroke is and isn't going:

1. Tools -> Options -> VsVim -> General 
1. Ensure "Output Window" is set to "True"
1. View -> Output
1. Switch the drop down to VsVim

Then go through your steps, copy the output from that window and paste it here.

**Comment by ricksladkey** [comment]
This is perplexing because it should "just work" and I cannot think of any reason that it **wouldn't** work.

These keys are indeed bound by default by Visual Studio:

![image](https://user-images.githubusercontent.com/2680524/62381890-751b2080-b51a-11e9-9e6c-8858461a68e1.png)

and yet these keys are not reported as conflicting with VsVim in the VsVim keyboard configuration.

**Comment by jira-zz** [comment]
Figured it out. It was my vimrc - I have arrow keys disabled there. When I disable vimrc, arrow keys work. So it was my mistake.

**Comment by ricksladkey** [comment]
@jira-zz Glad you figured it out, but disappointed that I didn't!
