### ISSUE TITLE
Caret is misplaced in lines that display codelens

### ISSUE THREAD

**Issue by LariscusObscurus** [VsVim/VsVim#2709]
**Describe the bug**
When placing the caret on a line that displays codelens information above the caret is shown in the codelens line and not in the actual line of code.
![grafik](https://user-images.githubusercontent.com/3046050/62862768-1ec29480-bd07-11e9-81c5-37e39e49593e.png)

**To Reproduce**

1.  Open a .cs file
2.  Move caret to a property definition or a method definition.
3.  Caret is now in the codelens line.

**Expected behavior**
The caret is placed on the code line.

**Screenshots**

**Environment (please complete the following information):**

- Visual Studio version: 2019
- VsVim version: 2.8.307
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
@LariscusObscurus Thanks, Leonard. I can reproduce this bug. I will try to get it fixed shortly.

**Comment by jonschoning** [comment]
How does one avoid this; will downgrading VsVim help?

**Comment by ricksladkey** [comment]
@jonschoning Sorry, I unfortunately do no know which version this bug was introduced in. If you can wait a few days, I'm working right now on submitting a PR for a fix. Sorry for the delay!

**Comment by Adrian-Grimm** [comment]
Thx for fixing this =)
