### ISSUE TITLE
2.8.0 release

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2721]
https://github.com/VsVim/VsVim/milestone/49

We've added a lot of good content recently and feels like we're overdue for a release. Looking through the 2.8.0 milestone there are six active issues there (one is currently in PR). Are there any of these that we feel are critical for a 2.8.0 release or can they be pushed out to the next one?

**Comment by TKumadaki** [comment]
@dhmgit is reporting a bug [here](https://github.com/VsVim/VsVim/issues/2707).
If users make the following settings, there will be no problems.

`nnoremap yy yyk`

But this issue is also relevant for users who do not use multi caret.
And `yy` is a frequently used command.
I worry that users who are not looking at Github will be in trouble.
If possible, I would like this issue to be added to the 2.8.0 milestone.

**Comment by ricksladkey** [comment]
@TKumadaki Yes, I agree that should be done before 2.8.0. I've modified the milestone as you suggested.

**Comment by ricksladkey** [comment]
I've moved the non-critical issues from the 2.8.0 milestone to a new 2.9.0 milestone. Only three remain, one of which has an open PR. The other two are assigned to me and are critical. Luckily, both are likely to be fairly straightforward and doable.

**Comment by TKumadaki** [comment]
Thank you @ricksladkey.
all the features that will be added in VsVim 2.8.0 are amazing !!

**Comment by ricksladkey** [comment]
I've submitted two PRs (#2734 and #2736) for the two high-priority 2.8.0 release issues. Once those are reviewed and merged, 2.8.0 should be good to go!

**Comment by jaredpar** [comment]
Thanks @ricksladkey!

**Comment by ricksladkey** [comment]
![image](https://user-images.githubusercontent.com/2680524/65481550-be755580-de63-11e9-856c-1a9a81d9f762.png)

:fireworks: :champagne: :v:

**Comment by markau** [comment]
Thank you for the work on this extension ❤️

**Comment by ricksladkey** [comment]
@jaredpar I know a release is a fair amount of work! Hoping we can get this out there. Are there any tasks I can help with to facilitate 2.8.0.0?

**Comment by jaredpar** [comment]
@ricksladkey 

Thanks for the offer of help. I just need to find two hours this week to sit down and get it done. I've blocked off some time to make this happen.

**Comment by ricksladkey** [comment]
@jaredpar 

That's good news. Get ready for the bug reports to come streaming in for the new multiple-cursor support! I'll do my best. 😃
