### ISSUE TITLE
.vimrc is not loaded or setting ":set number=true" does not work

### ISSUE THREAD

**Issue by Adrian-Grimm** [VsVim/VsVim#2738]
**Describtion**
If I place "set number=true" in .vsvimrc or .vimrc file it doe not work. 
Its only working manually typed in VisualStudio ":set number=true".

**To Reproduce**
Yust place .vsvirmrc like this in your user home dir:
![image](https://user-images.githubusercontent.com/5657002/66213684-90dca780-e6c0-11e9-80b1-6b864362b73e.png)
(tried with or without ':')

Settings in VS like:
![image](https://user-images.githubusercontent.com/5657002/66213750-afdb3980-e6c0-11e9-8f52-cc359a552797.png)

**Expected behavior**
Settings of the .vimrc file should be loaded and executed.

**Environment**

- Visual Studio version: 2017
- VsVim version: 2.8.234
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

**Comment by ricksladkey** [comment]
When "Use Visual Studio Settings" is in effect (see below):

![image](https://user-images.githubusercontent.com/2680524/66215783-404e5580-e692-11e9-8baf-c95204bc1880.png)

VsVim will use the line numbering scheme specified in Tools -> Options -> Text Editor that is appropriate for the current type of file being edited. As a result, your Visual Studio line number settings override your VsVim line number settings.

To handle this situation you can either:

1) Turn off Tools -> Options -> VsVim -> Defaults -> Vim Edit Behavior -> Use Visual Studio Settings (and in that case your vim rc file settings will be obeyed)

2) Turn on Tools -> Options -> Text Editor -> All Languages -> Settings -> Line Numbers (and line numbers will apply to all file types in Visual Studio and in VsVim)

**Comment by Adrian-Grimm** [comment]
Thx 👍✔
