### ISSUE TITLE
F1 only works in insert mode

### ISSUE THREAD

**Issue by pythoulon** [VsVim/VsVim#2749]
**Describe the bug**
The F1 context help key does not work unless vsvim is in insert mode.

**To Reproduce**
Open a project file. Position the cursor on a keyword or API element. Hit <esc> to get out of insert mode. Hit F1; nothing happens. Hit 'i' to go to insert mode. Hit F1: the context help opens.

**Expected behavior**
F1 should work whatever the mode.

**Environment (please complete the following information):**

- Visual Studio version: v16.3.8
- VsVim version: 2.7.0.0
- Programming Language: C#

**Comment by ricksladkey** [comment]
This problem is already fixed at the head of master and will be included in VsVim 2.8.0.0 when it is released.
