### ISSUE TITLE
Studio 2019 - when pressing enter to activate command line entry, CCR() is displayed in commandline instead of activating command

### ISSUE THREAD

**Issue by dnickelson** [VsVim/VsVim#2752]
**Describe the bug**
when trying to execute a : command, upon pressing enter, the commandline displays CCR() at the end of the command instead of executing the command.

**To Reproduce**

1.  open a file for editing
2.  type :w
3.  hit the enter key
4.  the commandline displays :wCCR()

**Expected behavior**
Expected behavior would be for the file to save, or an error message

**Screenshots**
![image](https://user-images.githubusercontent.com/6801882/69011782-bc93b400-0933-11ea-9d69-c4933bc125bc.png)

**Environment (please complete the following information):**

- Visual Studio version: 2019 pro
- VsVim version:2.7.0.0
- Programming Language: PHP/generic text file
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by jaredpar** [comment]
@dnickelson sorry to see you're hitting this. 

Can you try looking at your vimrc file to see if you define an mappings for the enter key? Guessing that there is a mapping in your vimrc for `<CR>` that VsVim is mis-handling here.

**Comment by dnickelson** [comment]
You were right.  Had a function defined to handle commandline entries differently based on content.  Disabling the map fixed the issue.  I'll have to figure out how or whether to try recreating the functionality, but thanks for the catch.
