### ISSUE TITLE
Allow disabling middle click paste in settings

### ISSUE THREAD

**Issue by reinux** [VsVim/VsVim#2753]
**Feature category**
    - [ ] Vim
    - [x] Vim plugin

**Is your feature request related to a problem? Please describe.**
When I'm scrolling, I tend to accidentally middle click and cause something to be pasted. Sometimes I don't even notice until there's an issue.

**Describe the solution you'd like**
A menu item in the config to disable middle click paste. 

`:map <MiddleMouse> <Nop>` will do the trick, but it took me a while to find. I suspect a lot of people have this issue, so it would be nice for it to be in the config where it's easy to find.

**Comment by jaredpar** [comment]
@reinux 

> it would be nice for it to be in the config where it's easy to find

Can you elaborate on this a bit? Not sure what you mean by "in the config" here.

**Comment by reinux** [comment]
Oh, sorry, I should have said Options to be clear.

In here:

![image](https://user-images.githubusercontent.com/5127297/69584831-02cfbf80-0f93-11ea-9446-e4cb7475ea46.png)

**Comment by ricksladkey** [comment]
I understand how a GUI option might help but there are in fact a thousand similar GUI options that might be more discoverable thathan t rc file settings, FAQ items, or wiki tips. Correct me if I am wrong, @jaredpar, but I think we should close this as will not implement because we are compatible with gvim already and don't necessarily intend to be more "user friendly" than gvim is.

**Comment by quittenkaes** [comment]
I absolutely agree to everything @jhurdlow wrote. I had the same experience: my source code got corrupted at random locations. It took me while to figure out that it was the content of the clipboard that was randomly pasted into the code. It took me even longer to find out that it was pasted in by a middle mouse click. This happens quite often while scrolling - at least with my mouse. And then it took me really long to figure out that the vsvim plugin was the culprit.

Please disable middle click pasting by default.

**Comment by ppeiwang** [comment]
I guess there are still some people like me to find the solution to disable the paste from mouse middle click. 
Here is my trick:
1. create a file: .vsvimrc in your environment's %USERPROFILE% (just press win+r, and enter with %USERPROFILE%)
2. paste this line into your .vsvimrc file : 
map <MiddleMouse> <Nop>
3. save and reopen your visual studio
