### ISSUE TITLE
VS 2019 16.4.1 Text Editor Focus Regression (Edit.GoToNextLocation)

### ISSUE THREAD

**Issue by NewUser2020** [VsVim/VsVim#2756]
**Describe the bug**

After the latest visual studio update (16.4.1), the text window no longer gets the focus properly, when Edit.GoToNextLocation is performed.

**To Reproduce**

I have the following mappings defined:

```
nnoremap <space>gn :vsc Edit.GoToNextLocation<cr>
nnoremap <space>gu :vsc Edit.FindAllReferences<cr>
```

1. Open a code file.
2. Place the cursor on a method.
3. Find all references: ' gu'
4. Go to next location: ' gn'
   You might have to repeat this command to get the effect.
5. Now the text editor has 'somehow' the focus, but the cursor is not visible.
   Moving with the cursor keys shows me that the text editor has the focus and it is moving around (I have the relative line numbers extension installed).

**Expected behavior**

The cursor should be visible and vim should get the input again.

**Additional context**

The bug is really annoying, because now I have to use the mouse to click into the editor window.

**Environment (please complete the following information):**

- Visual Studio version: VS2019 16.4.1
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment]
A workaround for this problem, at least at the head of master, is to type <kbd>Esc</kbd>. If it doesn't work for you now, you can expect it to be fixed (well, improved) in VsVim 2.8.0.0

**Comment by NewUser2020** [comment]
Ah, I did not mention that ESC does not work.

FYI: I just upgraded to VS 16.4.2, but that also did not help.

This behaviour is so annoying, that it's hard to live with.

Can you give me a rough date when VsVim 2.8 will be released?
Alternatively: Is there a downloadable Version from head (and is it 'safe' to use)?
In the extreme case I will have to roll back VS to 16.4.0...

**Comment by ricksladkey** [comment]
> Can you give me a rough date when VsVim 2.8 will be released?
> Alternatively: Is there a downloadable Version from head (and is it 'safe' to use)?
> In the extreme case I will have to roll back VS to 16.4.0...

Rough date? Soon!

FAQ topic:

https://github.com/VsVim/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources

Feed instructions:

http://vsixgallery.com/guide/feed/

**Comment by ricksladkey** [comment]
I just tried to repro with the nightly builds and cannot cause the problem. Please test and report!

**Comment by NewUser2020** [comment]
VsVim v2.8.405 fixes the problem.

Thanks.

**Comment by ricksladkey** [comment]
@NewUser2020 Thanks for the info. I'm closing this issue!
