### ISSUE TITLE
VS 2019 Community: Cannot activate extension at all

### ISSUE THREAD

**Issue by andrei-datcu** [VsVim/VsVim#2760]
**Describe the bug**
I've initially installed the extension through VS2019's extension manager. After closing the VS instance and running the installation, vsVim was not present in the installed tab of the extension manager. However, when searching for it, it was no longer installable (i.e it had the green checkbox in the top right, marking it is installed). Again, it was nowhere to be found and I couldn't even uninstall it.
I've then went ahead and uninstalled through `vsixinstaller /u:`.

I've reinstalled by double clicking on the .vsix file and now I do see it in the installed extensions tab. However, there's no other indication that the extension is activated. I also get no vsvim tab in Tools->Options...

I've tried uninstalling and reinstalling again (even using `vsixinstaller /admin`) disabling and enabling, restarting the machine etc. No dice. Any hints on how I could debug this?

**To Reproduce**

1.  Double click the *.vsix file downloaded from the marketplace's official site
2.  Proceed to install
3.  Open Visual Studio
4.  Extension isn't working
5.  Go to Tools->Options and notice there's no VsVim option tab.

**Expected behavior**
There should at least be the option tab, I guess.

**Environment (please complete the following information):**

- Visual Studio version: 2019 Community 16.4.2
- VsVim version: 2.8.0.0
- Programming Language: C++
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by jaredpar** [comment]
Sorry to hear this is hitting you. It's likely though this is something specific to your Visual Studio installation though (given that many other users have installed it on 16.4.*). 

Can you try the following steps:

1. Uninstall the extension via `vsixinstaller /u`.
1. Close all Visual Studio instances
1. Run `devenv /resetSettings`
1. Re-install VsVim via the extension manager

If this doesn't work then try the following:
1. Do the same as above but use the `/admin` switch when uninstalling. Generally this should never be needed as VsVim doesn't have any admin capabilities. However given you used it before it's possible this may be needed to undo the installation.
1. Run a repair on the Visual Studio instance. This really shouldn't be necessary but given you're in a state that shouldn't happen it's a step worth trying if nothing else works.

**Comment by andrei-datcu** [comment]
Thanks for the reply. Did 1-4 as you suggested, but I ran with `/admin` from the beginning. Everything works now!
