### ISSUE TITLE
VsVim For Mac: cannot backspace after append

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2764]
In normal mode type `A` to append to the end of a line, then backspace.

Expect: the last character is deleted
Actual: The bell sound

@nosami 

Tx

**Comment by coolbluewater** [comment]
Closing because Vim behaves the same way. The old Vim for Mac addin behaved differently, which informed my expectation.

**Comment by nosami** [comment]
@coolbluewater did you see this comment? https://github.com/VsVim/VsVim/pull/2733#issuecomment-549187752

**Comment by coolbluewater** [comment]
Ah, thanks a lot that really helps.

**Comment by nosami** [comment]
I need to compile this information on the wiki :)
