### ISSUE TITLE
VsVim For Mac: Watch window glitches

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2769]
Entering a watch seems to invoke VsVim within the little text field. Is this by design?

Expect: 
After clicking the "+" button, to directly enter the text I want to watch, and hit Enter to complete, or Tab to complete and focus in the Value field.

Actual:
Need to type `i` to enter insert mode. Hitting Enter to complete the entry does not work but instead creates a new line. Hitting Tab does not work either but instead inserts a tab. Mousing over the Value field and clicking works but is nonintuitive and involves the mouse.

**Comment by nosami** [comment]
> Entering a watch seems to invoke VsVim within the little text field. Is this by design?

No. This isn't by design. I'll fix it.

**Comment by costoda-ey** [comment]
I'm also seeing this issue.

**Comment by nosami** [comment]
Fixed in VsVim 2.8.0.4
