### ISSUE TITLE
Dot (.) key ignores uses of the backspace key.

### ISSUE THREAD

**Issue by Oinkium** [VsVim/VsVim#2772]
**Describe the bug**
When we press the dot (.) key, it should execute the previous action. If the previous action was inserting a string of text, then we should insert this string of text again. If this includes pressing the backspace key, then we should get that behaviour again when we press (.)

**To Reproduce**

1. Start with the text
```
redcar
redtractor
```

2. Navigate to the `c` of `car` and press `i` to enter insert mode. Press
```
<B-s><B-s><B-s>yellow
```
and then press `<Esc>` to exit insert mode so we now have
```
yellowcar
redtractor
```

3. Navigate to the first `t` of `tractor` and press the dot key `.`

**Expected behavior**
The `red` on the second line should be deleted and replaced with `yellow` to leave
```
yellowcar
yellowtractor
```

- Visual Studio version: 2017
- VsVim version: 2.8.0.0
- Programming Language: C++
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [x] Visual Assist

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by sqlkoala** [comment]
Hi, I think this is a vim setting, that vsvim implements correctly.
Can you try this setting?
`set bs=start`

**Comment by Oinkium** [comment]
Yes that works, thanks.
