### ISSUE TITLE
Not able to select text to the right of cursor with shift key pressed

### ISSUE THREAD

**Issue by freetomik** [VsVim/VsVim#2775]
**Describe the bug**
When holding shift key, selecting text after the cursor (to the right) is not possible. 

**To Reproduce**

1.  Press shift key and hold it.
2.  Hit right arrow key several times.
3.  Cursor does not move to the right with selecting them. Only one character  - that below cursor - is selected.

**Expected behavior**
Several characters to the right should be selected.

**Environment:**
- Visual Studio version: 16.4.3
- VsVim version: 2.8.0.0
- Programming Language: C++
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [x] Visual Assist

Disabling Visual Assist, nor SideScroller extensions does not help to resolve the issue.

**Additional context**
Moving down below the cursor is possible, but when then returning back (to the left), cursor jumps by two characters.
Surely there is easy workaround for this - to move with lower case L, or with right arrow without holding shift, but this should work also...

**Comment by kevmal** [comment]
Confirmed in 2,8,0.0. Rolling back to 2.7.0.0 resolves the issue.

**Comment by freetomik** [comment]
It would be good to investigate, which change from 2.7.0.0 to 2.8.0.0 caused the issue and fix it...
Rolling back at the user side is not possible, right? :-)

**Comment by kevmal** [comment]
Another important note is that, at least in my case, 'Shift-Right' is set to be handled by Visual Studio.

> Rolling back at the user side is not possible, right? :-)

Turn off "Automatically update extensions" in Tools->Options->Extenstions. Remove VsVim and install [VsVim 2.7.0.0](https://github.com/VsVim/VsVim/releases/download/VsVim-2.7.0/VsVim.vsix)

**Comment by ricksladkey** [comment]
If you want <kbd>Shift</kbd>+<kbd>Right</kbd> to work correctly in VsVim, you should do two things:

1. Set <kbd>Shift</kbd>+<kbd>Right</kbd> to be handled by VsVim
2. Ensure that your `~/.vsvimrc` file contains `:behave mswin`

Is there some reason that you cannot perform these actions?

**Comment by freetomik** [comment]
@kevmal 
> > Rolling back at the user side is not possible, right? :-)
> 
> Turn off "Automatically update extensions" in Tools->Options->Extenstions. Remove VsVim and install [VsVim 2.7.0.0](https://github.com/VsVim/VsVim/releases/download/VsVim-2.7.0/VsVim.vsix)

Oh, ok, so it is possible to roll back to previous version... Thanks. Haven't tried it though.

**Comment by freetomik** [comment]
@ricksladkey,
Your procedure works, thanks. Although second step changes caret in visual mode from solid rectangle to vertical line, which feels unusual a bit. 
I will stick to my previous non-mswin behaviour, since I am already used to it.
I don't use text selection with shift+arrows in vsvim mode, but just wanted to report this. :-)

**Comment by ricksladkey** [comment]
As long as VsVim is configured to handle shifted arrow keys, VsVim behaves exactly like gvim with the same settings.

**Comment by kevmal** [comment]
@ricksladkey  What is the "Shift + Right Arrow Handled by Visual Studio" option for? Is it meant for a different context?

**Comment by ricksladkey** [comment]
@kevmal That is a VsVim keyboard configuration option. See the second to last option in the screenshot below:

![image](https://user-images.githubusercontent.com/2680524/73776722-48102a80-4756-11ea-8de0-7b374f331c7d.png)

**Comment by ricksladkey** [comment]
@kevmal Thinking about it, I I understand better what you are asking. Why would anyone set any key to be "handled by Visual Studio"? That only makes sense for keys that perform some function that VsVim does not have, such as refactoring. For keys like shift plus arrow, assigning the handling to VsVim should always give you a more vim-compatible experience.
