### ISSUE TITLE
Colour highlighting for current line number

### ISSUE THREAD

**Issue by marovira** [VsVim/VsVim#2776]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [x] Vim
    - [ ] Vim plugin

In Vim, it is possible to set the colour of the current line to be something different from the regular line number. This is especially useful when combined with relative line numbers, as it makes it very easy to tell which line your cursor is currently on when working on large source files.

**Describe the solution you'd like**
A simple option under the Fonts and Colours settings for changing the current line number would be great for me.

**Describe alternatives you've considered**
Before the introduction of the relative line numbers in VsVim, this was accomplished through the Relative Line Numbers extension. Since VsVim introduced relative line number support, I dropped the extension as it showed two columns of line numbers. This resulted in losing the ability to change the colour of the current line number.

**Additional context**
Here's a sample of a source file in Vim (notice the yellow colour on the current line number):
<img width="551" alt="vim" src="https://user-images.githubusercontent.com/8482308/73409821-31c92100-42b5-11ea-8adb-5ffeb9cf30ce.png">

And here's the way VsVim currently works:
<img width="389" alt="vsvim" src="https://user-images.githubusercontent.com/8482308/73409874-61782900-42b5-11ea-97bf-1f8b81279a62.png">

I would like to be able to change the colour of the current line number in VsVim to match what I have on Vim.

**Comment by dannyp32** [comment]
If I wanted to try to implement this, could someone help point to me on where to start looking into it?
