### ISSUE TITLE
Ctrl-r in insert mode doesn't work

### ISSUE THREAD

**Issue by robbles** [VsVim/VsVim#278]
From the vim documentation:
    CTRL-R {0-9a-z"%#:-=.}
        Insert the contents of a numbered or named register.  Between
        typing CTRL-R and the second character '"' will be displayed
        to indicate that you are expected to enter the name of a
        register.

Right now if I press Ctrl-r while in insert mode, it ignores it and inserts whatever I type as the register name directly. I use this a lot for inserting small snippets of copied text while I'm typing, so it would be really handy to have.

**Comment by red1939** [comment]
I am using 2.8.0.0 (Visual Studio 2019) and `<C-R>=2+2` doesn't do anything, and pastes everything (`2+2`) into the code.

* Ctrl+R is mapped to VsVim (in options)
* Ctrl+R is not mapped to any shortcut in the VS keymap
* No Ctrl+R shenanigans in _vsvimrc

**Comment by os3albert** [comment]
instead to use `<C-r>` I've enabled `"vim.useSystemClipboard": true`.

Now every **motion action** is stored directly on the clipboard without pressing `Ctrl+C`.
At the end in _insert mode_ you just need to paste what is on your clipboard using `Ctrl+V`
