### ISSUE TITLE
VsVim for Mac: Need documentation on building and debugging the addin

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2781]
Tried to tackle a couple of irksome issues in VsVim for VsMac, particularly https://github.com/VsVim/VsVim/issues/2763. 

However, [Developing.md](https://github.com/VsVim/VsVim/blob/master/Documentation/Developing.md) does not have any information on developing and debugging on the Mac. Could we get some info on this in the next day or so, please, since this will then allow other issues to be debugged by the community.

**Comment by nosami** [comment]
Hi @coolbluewater. I've been meaning to do it for a while but other stuff has had to take priority for a while.

The instructions [here](https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555) should be more or less correct though (apart from repo URLs).

Want to try those out and see if it works for you? Maybe even update the wiki? :)

**Comment by nosami** [comment]
I added a wiki page here - https://github.com/VsVim/VsVim/wiki/MacOS-guide

Please add any missing information that you think I might have missed. Thanks!
