### ISSUE TITLE
Missing requirements after fresh installation of VS4Mac

### ISSUE THREAD

**Issue by wneessen** [VsVim/VsVim#2783]
**Describe the bug**
I just did a fresh installation of VS4Mac (8.4.5 b19). I opened the Extension Manager trying to install the VsVim extension from the Gallery. After the progress bar reaches the 100% is says: "Installation completed with warnings"

<img width="822" alt="Screenshot 2020-02-17 at 23 40 46" src="https://user-images.githubusercontent.com/542696/74690430-61e25080-51df-11ea-89c3-a0e058934841.png">

It tells me that I am missing some requirements, which I am not able to identify where to get them from. When I try to use the extension, it shows up in my Keybindings but it will not work. Once I restart VS4Mac, it will not show up in the Keybindings anymore but rather show "Custom".

**To Reproduce**

1.  Install latest VS4Mac release
2.  Go to File -> Extensions
3.  Search for "VsVim" in the Gallery
4.  Install the Extension
5.  Receive the error message

**Expected behavior**
Install the Extension and all requirements/dependencies are met or installed with the Extension.

**Environment (please complete the following information):**

- Visual Studio version: 8.4.5 build 19
- VsVim version: 2.8.0.1
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
I am totally new to VS4Mac, so it might be totally my mistake and not a bug. If that's the case, I'd highly appreciate any hint to point me to the correct solution.

**Comment by coolbluewater** [comment]
I am also seeing this. Looks like the fix for https://github.com/VsVim/VsVim/issues/2763 may have introduced a dependency on a Preview build of VsMac.

**Comment by nosami** [comment]
Sorry about this. I need to get better at making releases.

I've been building the extension myself up until now, but I really need to start publishing the artifact from Azure pipelines.

I just published 2.8.0.2 which fixes this. Thanks for reporting!

**Comment by wneessen** [comment]
Perfect. After the update and a restart of VS4Mac it works like a charme! Thanks for the quick response and the Extension :)
