### ISSUE TITLE
Insert模式下输入法切换的问题

### ISSUE THREAD

**Issue by xiongdashan** [VsVim/VsVim#2790]
这个应该是我不会配置的原因，求助指导一下：
从Normal-Mode向Insert-Mode切换后，输入法总是变中文，这时不得不再按Shift键切到英文输入，
困扰了好长时间，尝试换了输入法也没有解决切换到Insert-Mode后为英文输入法的办法。

**Comment by ricksladkey** [comment]
Rough translation of the issue:

#### Problems with input method switching in Insert mode

This should be the reason why I will not configure it. Please help for guidance:
After switching from Normal-Mode to Insert-Mode, the input method always changes to Chinese. At this time, you have to press the Shift key to switch to English input.
I have been troubled for a long time, and trying to change the input method did not solve the problem of switching to Insert-Mode for English input method.

**Comment by xiongdashan** [comment]
Thank you very much, the problem is solved
