### ISSUE TITLE
Line is inserted when Enter pressed for :wa( VS for Mac )

### ISSUE THREAD

**Issue by Akzwar** [VsVim/VsVim#2792]
**Describe the bug**
Line is inserted when Enter pressed for `:wa`( VS for Mac )

**To Reproduce**

Make sure the cursor is in the normal mode.
Enter `:wa`
Press Enter.

**Expected behavior**
Cursor stays at same position

**Environment**
- Visual Studio version: Visual Studio for Mac( COMMUNITY ) 8.4.6( build 36 )
- VsVim version: 2.8.0.2
- Programming Language: C#

**Additional context**
`:w` works as expected

**Comment by nosami** [comment]
Not sure how to replicate this although I did see this myself last night. Once it starts happening, it always happens.

**Comment by Akzwar** [comment]
Yes, you are right. I checked this out one more time and find out that it always happens if you try `:q` first and then `:wa`. I also noticed that `:qa` works the same way after that.

**Comment by nosami** [comment]
This is fixed in 2.8.0.5. Thanks for reporting and providing the repro!
