### ISSUE TITLE
Can't load _vsvimrc, Windows 10

### ISSUE THREAD

**Issue by Tozzo4316** [VsVim/VsVim#2795]
Hi, so I'm new in vim and from what I've read, you must have a _vsvimrc file, if you're using Windows 10, in your Username folder, but what do they mean by a _vsvimrc file? Does it have to be like myConfig._vsvimrc? Or just the name like _vsvimrc.txt? What extension should it be? txt?
I'm very confused because I tried both methods and none worked.
When I type in the vim command line :set vimrc it gives vimrc"" as a result, which makes me think that it didn't detect a _vsvimrc file.
How do I create such a file? Pls help I'm struggling a lot here.

**Comment by cbates-** [comment]
_vimrc (or _vsvimrc) is the entire filename - no extension.

**Comment by Tozzo4316** [comment]
Sorry for my dumb brain, but how would I create a extensionless file?

**Comment by Tozzo4316** [comment]
Ok I am dumb, just searche how to make an extensionless file and I literally had to delete the .txt part and voila. Thanks for the help
I will close the "issue"

**Comment by cbates-** [comment]
Lots of ways.
If want to create a file named _extensionlessFile_:
In Powershell:
`c:\temp> "" > extensionlessFile`

Or, with an editor such as vim or VS Code:
`c:\temp> code extensiolessFile`
`c:\temp> vim extensionlessFile`
