### ISSUE TITLE
Why does VsVim insert spaces instead of tabs, and can I change that behaviour?

### ISSUE THREAD

**Issue by murermader** [VsVim/VsVim#2797]
It makes indenting stuff really hard, especially when trying to remove the indendation (for example navigating back with Shift+Tab just moves the whole line back, instead of just moving the cursor). 

Any way to insert Tabs when pressing tab, instead of spaces? I could not find anything in the configuration in Visual Studio

**Comment by nosami** [comment]
Have you tried 

```
set noexpandtab
set tabstop=4
set shiftwidth=4
```
?

**Comment by ricksladkey** [comment]
VsVim by default uses the whitespace settings configured in Visual Studio for the type of file that you are editing. For example, if you are editing a C# file, then the whitespace settings are configured in:

Tools -> Options -> Text Editor -> C# -> Tabs

![image](https://user-images.githubusercontent.com/2680524/76534692-39e9b400-6450-11ea-9a80-111f1a6f58f5.png)

If you prefer to control the whitespace settings for all your files using only vim options, then you need to change those options:

Tools -> Options -> VsVim -> Defaults -> Vim Edit Behavior -> Use Visual Studio Settings -> False

Tools -> Options -> VsVim -> Defaults -> Vim Edit Behavior -> Use Visual Studio Tab / Backspace -> False

![image](https://user-images.githubusercontent.com/2680524/76535063-acf32a80-6450-11ea-8145-0c1280585a11.png)

**Comment by murermader** [comment]
Thank you both for your quick replies. I guess I should have looked a bit more carefully over the options.
