### ISSUE TITLE
VsVim for Mac: Escape remapping not working as expected

### ISSUE THREAD

**Issue by oskarskog** [VsVim/VsVim#2807]
First of all, thanks for this great plugin!

**Describe the bug**
I have escape remapped to 'fd' for insert mode in my  ~/.vsvimrc
```vim 
inoremap fd <esc>
```
then, when I'm in insert mode and  type 'f' no character is inserted, if I press 'f' again one 'f' character appears. If I continue to type some characters and then hit 'd' I'm thrown to normal mode. 

**To Reproduce**

1.  remap escape to 'fd' in .vsvimrc
2.  enter insert mode 
3.  press 'f' -> no 'f' appears
4.  continue to type
5.  hit 'd'  -> you're thrown to normal mode

**Expected behavior**

With the same mapping in vim the 'f' character normally appears the first time I hit 'f', if not followed by 'd'. Only if I enter 'f' and 'd' right after each other am I thrown back to normal mode.

**Environment (please complete the following information):**

- Visual Studio version: Visual Studio for Mac 8.5 (build 3183)
- VsVim version: 2.8.0.5
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by nosami** [comment]
Can confirm. Will try and fix - thanks for reporting!

**Comment by nosami** [comment]
Fixed in 2.8.0.8

**Comment by nosami** [comment]
Reopened as 2.8.0.8 was pulled from the feed.

**Comment by nosami** [comment]
Fixed in 2.8.0.11 . You can get it from the [Releases](https://github.com/VsVim/VsVim/releases/tag/v2.8.0.11-vsm8.9) page
