### ISSUE TITLE
VsVim for Mac: 2.8.0.6 does not work at all (DOA)

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2813]
No Vim editing functionality is available after upgrading to 2.8.0.6. Only the regular VS editor functionality is available.

Tried uninstalling and reinstalling, but that doesn't work either. Running VsMac 8.5.2 (build 13).

**Comment by nosami** [comment]
Please could you share your IDE logs? ‘Help -> Open Log Directory’

**Comment by nosami** [comment]
Never mind. I see what's wrong now :S My last commit isn't working for 8.5 :(

I pulled 2.8.0.6 from the feed. Please reinstall 2.8.0.5 from https://addins.monodevelop.com/Stable/Mac/8.5/Vim.Mac.VsVim-2.8.0.5.mpack

**Comment by nosami** [comment]
Sorry about that. Thanks for reporting!

**Comment by coolbluewater** [comment]
Hi, it might better to keep this open so that people hitting this issue - which is everyone who updates or installs - will know about the workaround.

**Comment by coolbluewater** [comment]
Also, for those who find this via google, the workaround steps are:
1. Uninstall the broken VsVim extension and restart Visual Studio for Mac.
2. Download https://addins.monodevelop.com/Stable/Mac/8.5/Vim.Mac.VsVim-2.8.0.5.mpack via your browser.
3. In VsMac, go to the Extensions pane and click Install From File. Navigate to your Downloads folder and select the .mpack file you downloaded.
4. For some reason the extension doesn't work right away. You need to restart Visual Studio for Mac.

**Comment by nosami** [comment]
@coolbluewater 2.8.0.5 is the latest version on the feed now.

**Comment by coolbluewater** [comment]
Great! Thanks.
