### ISSUE TITLE
VsVim Mac - It's not working  when use F# Project

### ISSUE THREAD

**Issue by zhangjinglin** [VsVim/VsVim#2833]
It's not working visual studio for mac when use F# Project

I create a C# project, vsvim work well, But in F# project, the vsvim not working and don't show 'Vim output'.

- Visual Studio for Mac 8.6.2(build 6)
- VsVim version: 2.8.0.8
- Programming Language: F#
- macOS Version: Mojave 10.14.6

**Comment by nosami** [comment]
@zhangjinglin Hi! Please read this https://github.com/VsVim/VsVim/issues/2809#issuecomment-605670797

**Comment by nosami** [comment]
Closing this as F# is using the same editor as C# in VSMac 8.8 (Preview channel) and hence is working.
