### ISSUE TITLE
Major regressions in 2.8.0.8

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2835]
Hi! There seem to be a lot of regressions in this build.

1) It took several tries before the build would install on my machine. VSMac kept reporting "Failed". Retried for a couple of weeks before it finally installed. Not sure if this is a server issue or something else.

2) As reported by another user, Intellisense does not trigger when "." is pressed.

3) Typing /// to start a c# doc comment section does not  add the `<summary>` tag.

4) Typing a close brace does not trigger auto-format.

I am going to try to revert to a previous version.

Thanks!

EDIT: I reverted to 2.8.0.5 because that is the last .mpack that I could access via URL https://addins.monodevelop.com/Stable/Mac/8.5/Vim.Mac.VsVim-2.8.0.5.mpack. 

Could we please revert the feed to the most recent stable version since 2.8.0.5 is a bit old at this point?

EDIT 2: Reverting to 2.8.0.5. did not work at all. Luckily another bug had this URL:  https://addins.monodevelop.com/Stable/Mac/8.5.2/Vim.Mac.VsVim-2.8.0.7.mpack. Installing it worked and life is good again. These URL's are unguessable!

Request: Could we please have an archive of past build URLs going forward as well as a bit more smoke testing?

**Comment by nosami** [comment]
> Request: Could we please have an archive of past build URLs going forward as well as a bit more smoke testing?

@coolbluewater Hi, are you offering? :) I no longer use VsVim or VsMac but don't mind keeping things ticking over in maintenance mode until someone else steps forward.

**Comment by coolbluewater** [comment]
> @coolbluewater Hi, are you offering? :) I no longer use VsVim or VsMac but don't mind keeping things ticking over in maintenance mode until someone else steps forward.

Sure, I'm already doing testing and bug reporting as a heavy user :) And the link of older releases you just added is pure gold, exactly what I wanted.

Just curious - what have you switched to in place of VsMac? Or did you migrate away from .net as a whole?

**Comment by nosami** [comment]
I am now on the Codespaces team working on Windows integration and so am using Windows.

Maybe I will return to using VSMac at some point but there is currently too much friction with my new team.

> Sure, I'm already doing testing and bug reporting as a heavy user :)

Fancy taking over development work too?

> And the link of older releases you just added is pure gold, exactly what I wanted.

You can also find mpack files as CI artifacts by following the links from PRs if you want to test them early.

**Comment by nosami** [comment]
These issues are fixed in v2.8.0.11 found on the releases page
