### ISSUE TITLE
VsVim for Mac: Insert mode not recorded in macro

### ISSUE THREAD

**Issue by ofthelit** [VsVim/VsVim#2844]
**Describe the bug**
When [recording a macro](https://vim.fandom.com/wiki/Recording_keys_for_repeated_jobs), everything entered in Insert mode is not recorded. A copy in Visual mode and a paste in Navigation mode works.

**To Reproduce**

1.  Open up a C# file
2.  Start recording in register a: `qa`
3.  Go to insert mode and type some text: `i test`
4.  Go back to navigation mode: <esc>
5.  Start a new line: `o newline test<esc>`
6.  Stop recording the macro: `q`
7.  Playback the macro: `@a`

**Expected behavior**
I expect the macro to repeat itself. The new line appears but entered text is not recorded.

**Environment**

- Visual Studio version: Version 8.6.8 (build 2)
- VsVim version: 2.8.0.7
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Enabled user installed extensions
DeepClean 1.2.5
Xamarin.Forms HotReload extension 1.4.0
Open With 0.2
XAML Styler 2.0.1
VsVim 2.8.0.7
MFractor 4.2.9
Project System Tools 0.4

**Comment by nosami** [comment]
Hmm... [I fixed this issue in 2.8.0.8](https://github.com/VsVim/VsVim/issues/2820) but that had to be reverted because it caused [new problems](https://github.com/VsVim/VsVim/issues/2835)

I'm afraid I'm not even using a Mac right now

**Comment by nosami** [comment]
Fixed in 2.8.0.11. You can get it from the [Releases](https://github.com/VsVim/VsVim/releases/tag/v2.8.0.11-vsm8.9) page
