### ISSUE TITLE
No Ctrl-I or Ctrl-O option in VsVim keyboard options (VS 2019) 

### ISSUE THREAD

**Issue by OnTheWay2015** [VsVim/VsVim#2846]
the problem like #2514
Microsoft Visual Studio Community 2019  v16.6.0

I checked that those keys are not bound to other function in Tools -> Options -> Environment -> Keyboard
![image](https://user-images.githubusercontent.com/12267238/90602797-e2d0e200-e22c-11ea-8c86-f73e7d794d36.png)

I set "handle all with VsVim" include C-O and C-I ,but those keys still can not use.
![image](https://user-images.githubusercontent.com/12267238/90602695-c03ec900-e22c-11ea-90c9-a5715f59ea4e.png)

**Comment by r4ks** [comment]
can't navigate back like normal vim too ctrl - o not doing anything :(

**Comment by thp** [comment]
@r4ks This hack-ish solution helped in my case with VS2022 (it's "Environment" -> "Keyboard" in VS settings, there you can remove all conflicting key bindings): https://stackoverflow.com/a/44894346/1047040 -- after that, hotkeys should be available for use within VsVim.

**Comment by ThakeeNathees** [comment]
After removing the binding I had two issues:
1. I can't go back <C-o> to a different file
2. go to definition also selects the text (visual mode).

This script will fix `path=(%HOME%, %VIM%, %USERPROFILE%)/.vsvimrc`

```vim
" NOTE: <C-o>, <C-i> are not working because they're shortcut to open and incremental search.
" So remove the shortcut to make the binding jump work by:
" Tools > Option > General > Keyboard > Search for "File open" and "Incremental search" Remove.

" NOTE: <C-o>, <C-i> is only works in a single file, so this hack is needed.
" Reference: https://github.com/VsVim/VsVim/wiki/VsVim-Nonstandard-Behavior#jumps
nmap <C-o> :vsc View.NavigateBackward<CR>
nmap <C-i> :vsc View.NavigateForward<CR>

" goto definition also selects the definition (visual mode), this hack will fix.
vmap <C-o> <esc>:vsc View.NavigateBackward<CR>
vmap <C-i> <esc>:vsc View.NavigateForward<CR>
```
