### ISSUE TITLE
VsVim for Mac: Does not activate

### ISSUE THREAD

**Issue by mtran45** [VsVim/VsVim#2863]
**Describe the bug**
VsVim 2.8.0.7 does not activate in the latest version of Visual Studio 2019 Community for Mac.

**To Reproduce**

1. Install Visual Studio 2019 Community for Mac version 8.8.1 (build 37) and VsVim 2.8.0.7
2. Create or open a new file
3. Observe that VsVim is not active for its window (i.e., cursor is not in normal mode and no bindings work)

**Expected behavior**
VsVim should be activated - cursor in normal mode and bindings should work.

**Screenshots**
N/A

**Environment (please complete the following information):**

- Visual Studio version: Visual Studio 2019 Community for Mac version 8.8.1 (build 37)
- VsVim version: 2.8.0.7
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
In the log files there are numerous entries with the error
`VsVim: Failed to get filename of textbuffer.`

From what I can tell, VsVim for Mac is no longer being actively maintained so I'm not expecting any fixes any time soon. But I'm just posting this in case I have set something up incorrectly and someone can point me in the right direction.

**Comment by nosami** [comment]
I installed 8.8.1 to test and it works for me.

![image](https://user-images.githubusercontent.com/667194/99874515-89d46980-2be0-11eb-99d0-f8c8f3c98eda.png)

If it still doesn't work for you after restarting, please share your log files. Thanks!

**Comment by mtran45** [comment]
Thanks for the quick response and for taking the time to install that build to test it out!

I've attached the logs as requested. Appreciate the help, thanks

[Ide.2020-11-22__10-29-59.log](https://github.com/VsVim/VsVim/files/5578677/Ide.2020-11-22__10-29-59.log)

**Comment by nosami** [comment]
@mtran45 does this happen in every file, every project? Did it work in previous versions of VSMac? Thanks.

**Comment by mtran45** [comment]
@nosami I've tried every file in a few solutions including creating new Console Application and ASP.NET projects from templates, but it hasn't worked in any of them. 

I haven't used VsVim on previous versions of VSMac, so not sure. Actually haven't used VSMac for a long time and just updated and installed VsVim yesterday

**Comment by mtran45** [comment]
I'm not really sure what fixed it, but it is working now. 
I installed another unrelated extension for VSMac and after restarting vim was working all of a sudden, but it is still working even after uninstalling that extension, so maybe it was something else. Can't say for sure..

Anyway, thanks for your help, I'll close the issue. Just glad that I can use vim now!
