### ISSUE TITLE
Automate the Visual Studio for Mac extension publish workflow using GitHub releases

### ISSUE THREAD

**Issue by nosami** [VsVim/VsVim#2866]
Visual Studio for Mac is changing the way that extensions will be published [starting from January](https://docs.microsoft.com/en-us/visualstudio/mac/migrate-extensions?view=vsmac-2019)

The mechanism for publishing the extension will use GitHub releases. Should we use this repo for doing that?

We can probably take advantage of this by automating the publishing of the extension. This is something that is not currently possible.

What does the process look like for publishing the Windows extension? I guess it would make sense to try and make it as similar as possible.

**Comment by jaredpar** [comment]
Yes let's use this repository for doing that. 

I'm alos not quite sure what that will look like for the Windows releases. Think we could just start with the Mac part and see how the Windows story evolves.

**Comment by nosami** [comment]
What I have done before that seemed to work well was automatically publishing release artefacts when a new tag was pushed. Does this sound reasonable?

**Comment by jaredpar** [comment]
That sounds good to me.

**Comment by nosami** [comment]
I just took a look at how this could be achieved. It seems that the [GitHub Release Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops) might be the best way to accomplish this.

However, I need a [GitHub Service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-github) configuring in Azure DevOps.

@jaredpar Please could you do this and let me know the connection name that you give to the service connection?

**Comment by jaredpar** [comment]
Created a GitHub service connection named automationConnection that we should be able to use for this purpose. 

Possible this may take a few attempts to get correct. The PAT that is needed for such a connection is pretty extensive. Enough that it effectively needed full access to private repos which is problematic since I'm an org admin in dotnet. Had to create a separate account, vsvim-bot, and use that to manage the connection instead. Believe I got everything correct here but if not let me know and I'll play with the PAT permissions on it.

**Comment by nosami** [comment]
> Created a GitHub service connection named automationConnection that we should be able to use for this purpose.

That's great thanks! I'll give this a go within the next couple of days and will let you know how it goes - cheers!

**Comment by nosami** [comment]
This seems to be working pretty well for the Mac artifact at least. I automatically created a [draft release](https://github.com/VsVim/VsVim/releases/tag/untagged-409d8586a66594500634) which has a generated changelog (can remove that if you're not keen).

I'm not too sure how this will work if we try and combine Windows and Mac artifacts from the same tag. For instance, do we always publish for both platforms (even if changes are Mac only)? I think that always publishing for all platforms is probably the simplest but not sure if this is desirable.

The name of the Mac extension file (.mpack) is derived from the [version](https://github.com/VsVim/VsVim/blob/master/Src/VimMac/Properties/AddinInfo.cs#L8). This should ideally match the tag and release name. This version number is also referred to from within `azure-pipelines.yml` in a couple of places now.
I'm currently thinking that we should modify the version via this source file from the CI server whenever a tag is pushed (make the source file match the tag version number) so that we don't have to change it in multiple places. Would appreciate your input if you have any better ideas!

**Comment by nosami** [comment]
After reading the [VSMac release guidelines(https://docs.microsoft.com/en-us/visualstudio/mac/migrate-extensions?view=vsmac-2019#release-a-new-version) a bit more carefully, it's apparent that we can't use the same format for the Release titles.

VSMac dictates that the format of the tag needs to be `v{Extension.Version}-vsm{Minimum VSMac Version}` and up until now you have been using the tag format `VsVim-{Extension.Version}`.

So I guess that this means that we need to separate the Mac releases from the Windows releases. I don't think this is ideal but I suppose it does simplify things somewhat. Whenever we want to publish a Mac release, we can just push the tag with the expected format, and Windows releases can work however they currently work.

**Comment by jaredpar** [comment]
I'm not wedded to my current tag naming scheme. Even so given that `vsm` is part of the format I can't see a good way to have a universal tag here unless I'm missing something. Think you're right that we may have to go with separate tags.
