### ISSUE TITLE
vsvim rc file

### ISSUE THREAD

**Issue by sumit-official** [VsVim/VsVim#2878]
I can't seem to find the VSVIM .vimrc file I want to make some changes but can't locate where the .rc file is to do so.

**Comment by nosami** [comment]
Hi @sumit-official, [this](https://github.com/VsVim/VsVim/wiki/VsVim-Nonstandard-Behavior) should help you out

**Comment by KiritchoukC** [comment]
Note that you have to create it yourself if it does not exist yet.

**Comment by sumit-official** [comment]
> Note that you have to create it yourself if it does not exist yet.

Is there a file loaction where your vsvim should be ?

**Comment by KiritchoukC** [comment]
If you follow @nosami link, you will find all the path vsvim will look for.
Type `echo $HOME` in your shell to get your home path and put it there.

**Comment by sumit-official** [comment]
thanks so much guys
