### ISSUE TITLE
VsMac auto-format randomly switches off with VsVim 2.8.0.11

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2888]
Hi, since updating to VsVim 2.8.0.11 Visual Studio's auto-formatting stops working randomly. 
When this happens e.g. typing a close brace will not format the code inside. Opening braces on a new line appear at the wrong tab stop, and so on.

I'm trying to roll back to an earlier VsVim to test whether the plugin is the cause.
Unfortunately the VS folks have removed the .mpack archive at https://addins.monodevelop.com/Project/Index/403

Any idea where I might find an earlier .mpack?
Thanks!

EDIT: Managed to fish out 2.8.0.7 from my Time Machine backup and things work again. So the problem is very likely in the current version of the plugin.

**Comment by nosami** [comment]
I noticed this myself today (along with some other input bugs, e.g. broken Signature Help)  and am currently fixing. Sorry about that.

> Unfortunately the VS folks have removed the .mpack archive at https://addins.monodevelop.com/Project/Index/403

Yeah, the monodevelop feed got retired. Going forward, mpacks will be uploaded to the [Releases](https://github.com/VsVim/VsVim/releases) page.

**Comment by nosami** [comment]
@bysameng You can get a build of 2.8.0.12 with the fix in here https://dev.azure.com/VsVim/503f82b4-a499-4dec-abba-84bfda309969/_apis/build/builds/555/artifacts?artifactName=VSMacExtension&api-version=6.0&%24format=zip
