### ISSUE TITLE
VS 2022 Preview Requires Double ESC tap after semicolon when fullline IntelliCode enabled

### ISSUE THREAD

**Issue by bbartels** [VsVim/VsVim#2901]
**Describe the bug**
VS 2022 Preview Requires Double ESC tap to return to normal mode after semicolon when fullline IntelliCode enabled

**To Reproduce**

1.  dotnet new console
2.  Write character for character in Main method (dont make intellicode complete): int length = args.Length;
3. After the semicolon was entered, press ESC. Vim does not return to normal mode. A second ESC press will do so.

**Expected behavior**
A single ESC press should return to normal mode

**Screenshots**
https://imgur.com/QqgNgLz

**Environment (please complete the following information):**

- Visual Studio version: 2022 Preview 1
- VsVim version: 2.10.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by bbartels** [comment]
Upon further investigation it seems to occur every time IntelliCode full line completion is enabled. A double ESC tap is required to go back to normal mode

**Comment by jaredpar** [comment]
Right now I'm in the middle of re-working the project so that VsVim can more easily support VS 2022 (#2900). Once that is complete I will take a look at this.
