### ISSUE TITLE
Better separate VimTestUtils and VimEditorHost

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2905]
The intent of these two projects was:

- `VimEditorHost`: provide a simple API for hosting `IVim` and `ITextBuffer` for testing and debugging purposes 
- `VimTestUtils`: provide xUnit helpers necessary for testing. Most notably the `StaFramework` infrastructure 

The intent though wasn't 100% clear when I created these years ago and accordingly I didn't break up the code correctly when I did this. As a result there is presently a lot of code in `VimTestUtils` that should be in `VimEditorHost`: lots of exports, extension methods for `VimCore`, etc ... 

This was okay before the move to shared projects because it was setup such that `VimTestUtils` could reference `VimEditorHost` and every test project referenced both of them. Now in shared projects (#2900) `VimEditorHost` has moved to a shared project and that breaks this relationship. As a result `VimTestUtils` needs to compile independently. That has really shined a light on the problems I created when I didn't separate the code cleanly. 

It's all working now but it was rough to work with (particularly makes creating `CompositionContainer` hard to reason about). This issue is meant to track cleaning that all up.

**Comment by nosami** [comment]
`VimTestUtils` probably shouldn't depend on `WPF` either as this makes it impossible to run the unit tests on a Mac. The unit test projects are currently excluded from compilation when using `DebugMac` configuration.

Can we use this issue to track that work or should we create a separate issue?

**Comment by jaredpar** [comment]
> Can we use this issue to track that work or should we create a separate issue?

Thought about this on the plane ride home today and think we should track it with a separate issue. The work needed to break up `VimTestUtils` in order to support Mac unit testing is a bit further than what I was intending with this issue. But solving this issue is likely going to make the work necessary to test on Mac a bit easier. 

In my head I *think* the right way to approach the Mac testing is to essentially end up with the following structure:

- VimTestUtils: shared project that encapsulates a couple of layers and uses `#if` to compile between Windows and Mac
    - `StaFramework`: this is xUnit extension layer which allows for tests to be run on a specific thread
    - `WpfFact`: although we'd likely name it `StaFact` given that it won't be tied to WPF anymore and will be more platform neutral  
- VimTestUtilsWpf: references `VimTestUtils` and serves essentially the same purpose `VimTestUtils` serves today
- VimTestUtilsMac: references `VimTestUtils` and compiles for Mac 
- VimCoreTestMac: this references `VimCoreTest` (the shared project for core vim testing layer) and `VimTestUtilsMac` 

At a quick glance the`VimTestUtilsMac` project may seem unnecessary. However xUnit requires that the type of extensions that drive `WpfFact` exist in a separate library hence it becomes necesary.

Does this line up with how you think it will work? I must admit, I don't essentially know what the equivalent of STA threads are in Mac. But given the WPF editor runs in Mac I assume the rough concept is there (essentially the main UI thread). Hence shouldn't be too hard to implement there.

**Comment by nosami** [comment]
> Does this line up with how you think it will work?

This sounds great as an initial way to approach this. We can always tweak things later if it doesn't work out.

> I assume the rough concept is there (essentially the main UI thread)

Yes, it's pretty much exactly the same. One thread is responsible for all of the updates to the UI. It's generally illegal to use any background thread to update the UI and some assertion will fail. It's usually just named the main thread or the UI thread :)

> although we'd likely name it StaFact

STA isn't an acronynm used on the Mac at all... so maybe we could think of a better name. Not too fussed about this though if the concept is the same.
