### ISSUE TITLE
How to integrate another extension with VsVim?

### ISSUE THREAD

**Issue by elHamil** [VsVim/VsVim#2909]
Hi, this is not a bug report, rather a support request (or maaayybe a feature request). I'm developing another Visual Studio extension, and I'd like to cooperate well with VsVim, so now I'm asking how to do it best.

In my extension, the user should be able to press a key combination to do a certain action. (For our discussion it doesn't matter what the action actually is.) If the user also uses VsVim, it would be ideal if he could choose to sacrifice one of the vim keys, for example the "S" key, and use it for my extension like this:
VsVim is in normal mode, user presses S = action taken
VsVim is in visual mode, user presses S = action taken
VsVim is in insert mode, user presses S = action not taken, "s" is inserted into the text as usual
VsVim is in command mode, user presses S = action not taken, "s" is inserted into the command box as usual

I can think of a few different ways to implement this integration:

1. I could try to guess which mode VsVim is in, by listening to the Visual Studio API's text buffer events between key down and up - did the keypress cause the text to change? If it did change, we must be in insert mode, so don't do my action. I already implemented this, but I don't think it's good, it doesn't detect command mode, and it also gets confused by Visual Studio's own builtin search&replace box.

2. Maybe I could **ask VsVim which mode it's in**. Is there an official way to do that? I read the docs, looked around in the source code for a while, and searched this issue tracker, but found nothing yet.

3. Maybe flip the relationship around and **have VsVim call my extension**. Is there an official way to do that? Again, I tried to look for info, but maybe in the wrong place.

I'd appreciate any pointers to the best integration method and the right place for more info. If there's no official way, but if you maintainers like the idea, I'm **willing to help** if I can.

**Comment by jaredpar** [comment]
At the moment there is no exposed API from VsVim that other extensions can depend on. In the past I thought about exposing an API but never really had a motivating example to drive a design off of. 

At a high level, and please correct me if I'm wrong, it sounds like you mostly want to be able to effectively disable certain keys in vim mode. Essentially assign a key such that VsVim won't actually process it and will instead allow it to fall back to Visual Studio. Is that understanding correct? 

If so it falls in line with an idea I've had over the years. Essentially a way of registering keys as "please don't handle at all". There are operations like <kbd>Ctrl-S</kbd> that I've long wanted to just have VsVim ignore and let Visual Studio behavior take hold.

**Comment by cbates-** [comment]
It's not an API exactly, in that you aren't calling methods directly on a VsVim interface but you can send commands to VsVim via Visual Studio.
An example: 
VsVim.SetMode Normal
can be entered in the Command window in VS.
It can also be executed via the ExecuteCommand(...) method on the DTE2 interface in an extension.
(This works at least up to VS 2017, no guarantees beyond that...)

**Comment by elHamil** [comment]
> it sounds like you mostly want to be able to effectively disable certain keys in vim mode. Essentially assign a key such that VsVim won't actually process it and will instead allow it to fall back to Visual Studio.

No, I don't think that's what I want. I'll try again. In normal mode, Vim has actions like for example "move caret to next word boundary" or "insert line above". I kinda want to add another such action, and allow users to map it to a single key, but my action is far out of scope of VsVim's intended feature set, and better implemented as a separate Visual Studio extension. (Also, users should be able to use my extension without VsVim, in which case they would use some more complex keyboard shortcut like Ctrl+Shift+Whatever)

If I, in my extension, write this (pseudocode)...
```
if (keys Ctrl+Shift+S pressed)
    doAction();
```
... it will work fine if the keyboard combination is unique. But if I want the user to be able to use a single key...
```
if (key S pressed)
    doAction();
```
... the action will happen _and_ the letter "s" will be inserted into the document at the same time, which is bad. Vim solves this conundrum with different modes, essentially:
```
if (key S pressed)
{
    if (normal mode)
    {
        doAction();
        blockVisualStudiosDefaultAction();
    }
    // else if (insert mode) Visual Studio itself will insertCharacter("s");
}
```

I hope this clarifies why I'd like to either ask VsVim which mode it's in, or let my extension add a new type of action to VsVim which the user can map however they like.


> you can send commands to VsVim via Visual Studio.
> An example:
> VsVim.SetMode Normal
> can be entered in the Command window in VS.

This sounds close to what I need! Is there also a `VsVim.GetMode`? Or where can I find a list of supported commands?

**Comment by nosami** [comment]
Sounds to me like you should write your extension as a VS Command ([see example](https://github.com/VsVim/VsVim/wiki/VsVim-Nonstandard-Behavior#integration-with-visual-studio))

VsVim can invoke any VS Command via VimScript using `:vsc` so you could have something like this in the .vsvim configuration file

```
nmap s :vsc: Your.Command<CR> # for a normal mode s
```

**Comment by elHamil** [comment]
Sounds perfect! When I read the wiki, I didn't realize that, so thanks for connecting the dots for me. 😃  We can probably close this issue, but maybe first let me try this method, and see if it works for my use case. I'll report back.

**Comment by elHamil** [comment]
I've implemented it now (my extension as a VS command). The `:vsc` trick worked fine. Thanks again for the guidance, and I hope this Github issue can help someone else in the future.

I did find an integration problem (related to visual mode and caret movement) but I think it's conceptually separate from the above discussion, so I'll open a new issue for it.
