### ISSUE TITLE
How to disable gutter icons?

### ISSUE THREAD

**Issue by zhengweidi** [VsVim/VsVim#2913]
How to disable gutter icons?
![image](https://user-images.githubusercontent.com/31889177/125727532-d6a5ad5a-4e73-4087-90ed-ddaf437d0b7c.png)

**Comment by jaredpar** [comment]
This can be done by updating the `vsvim_hidemarks` setting

```
:set vsvim_hidemarks=-
```

Or by specifying it in the VsVim options page 

![image](https://user-images.githubusercontent.com/146967/125734306-b9f0862c-a182-4dc5-9825-a70f22a4303b.png)
