### ISSUE TITLE
Tab and Window commands don't work in VSMac 17.0

### ISSUE THREAD

**Issue by nosami** [VsVim/VsVim#2918]
**Describe the bug**
All Tab and Window commands don't work with the upcoming release of VSMac . This includes "go to tab", split window commands etc.

Will need to write some more reflection based code in [WindowManagement.cs](https://github.com/VsVim/VsVim/blob/master/Src/VimMac/WindowManagement.cs) and maybe drop support for 8.9 at the same time.

**To Reproduce**

1.  Open multiple tabs
2.  Switch to the first tab
3.  type 'gt' to switch to the second tab.
4.  Nothing happens

**Expected behavior**
Should switch to the second tab.

**Environment (please complete the following information):**

- Visual Studio version: VSMac 17.0
- VsVim version: latest
- Programming Language: any

**Comment by jaredpar** [comment]
Is this something I broke recently with my changes?

**Comment by nosami** [comment]
> Is this something I broke recently with my changes? 

No, don't worry 🙂

The API for VSMac has changed completely in between 8.10 and 17.0. We moved from GTK to Cocoa.

Should be an easy fix, just need to allocate some time to spend on it.
