### ISSUE TITLE
How can I get the all actions|command list with vsvim ?

### ISSUE THREAD

**Issue by eggcaker** [VsVim/VsVim#2928]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [ ] Vim
    - [x ] Vim plugin

If the function you request is realized by Vim or Vim plugin,
When you link the URL that is related,
We will make it easier to understand its function.

**Is your feature request related to a problem? Please describe.**
 How can list all actins from ex? then later I can mapping that command in .vsvirmc file .

**Describe the solution you'd like**
like in ideavim, can list all actions with ```:actionlist```

**Comment by jaredpar** [comment]
Not quite sure what you mean by "actions" here. Can you try elaborating a bit?

**Comment by eggcaker** [comment]
ex: ```nnoremap gI :vsc Edit.GoToImplementation<cr>```

the  ```Edit.GoToImplementation``` is action(or command)  at least I called them. I'm not sure it's correct or not, the question is how can get all actions like this

**Comment by jaredpar** [comment]
Those commands are all just Visual Studio commands. I don't know where you can go to get a full list written out but you can see all of them listed in the Visual Studio Keyboard options page 

![image](https://user-images.githubusercontent.com/146967/131874477-0380ea8b-5b4a-4c8d-a9ba-147bada2841b.png)

**Comment by eggcaker** [comment]
use that for now.
