### ISSUE TITLE
move visually selected lines up/down

### ISSUE THREAD

**Issue by tobser** [VsVim/VsVim#2936]
I have two mappings to move visually selected lines up/down (from https://vim.fandom.com/wiki/Moving_lines_up_or_down) :
```
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
```
The mappings work one time, they move the selection one line up/down but then the lines are no longer visually selected.

VsVim output:
```
VsVim Error Error Start
Cannot retrieve the previous Visual Span
VsVim Error Error End
```
- Visual Studio version: 16.11.5
- VsVim version: 2.8.0.0
- Programming Language: c#

this may be related to https://github.com/VsVim/VsVim/issues/2185

**Comment by gadr1on** [comment]
#2446 <-- Problem solved here

**Comment by tobser** [comment]
Thanks. Solution in #2446 works for me. Only issue: moved lines are indented correctly after being moved...
