### ISSUE TITLE
Missing relativenumber setting reference in the wiki

### ISSUE THREAD

**Issue by wizardlink** [VsVim/VsVim#2946]
Since the PR #2571 VsVIm has the `relativenumber` local setting, however it is not present in the [settings reference](https://github.com/VsVim/VsVim/wiki/Settings-Reference) wiki page.

Not much else I can add to this issue, I think it's descriptive enough.

**Comment by nosami** [comment]
Do you have edit access to the wiki page?

**Comment by wizardlink** [comment]
> Do you have edit access to the wiki page?

No, the repository probably limits wiki editing to collaborators only.

**Comment by nosami** [comment]
added
