### ISSUE TITLE
CTRL+D doesn't work in VS2022

### ISSUE THREAD

**Issue by ThomsonTan** [VsVim/VsVim#2971]
**Describe the bug**
VS2022 with VsVim installed, with CTRL+D/CTRL+U setting to be handled by VsVim instead of Visual Studio, `CTRL+U` seems working, but `CTRL+D` doesn't scroll down half page.

**To Reproduce**

1.  Go to Tools -> Options -> VsVim -> Keyboard, set `CTRL+D` and `CTRL+U` handled by VsVim.
2.  Open any source file.
3.  Press `CTRL+D`.
4.  It doesn't scroll half page down.

**Expected behavior**
The editor should scroll down half a page after each stoke of `CTRL+D`.

**Screenshots**

**Environment (please complete the following information):**

- Visual Studio version: VS2022 latest
- VsVim version: latest
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by ThomsonTan** [comment]
Never mind, `CTRL+D` is interfered other app which defined global mapping on it.

**Comment by martin-braun** [comment]
@ThomsonTan I have the same problem. This is a clean Windows under Parallels. What was the cause exactly in your case please?

**Comment by ThomsonTan** [comment]
> @ThomsonTan I have the same problem. This is a clean Windows under Parallels. What was the cause exactly in your case please?

I forgot the app which defined `CTRL+D` as global hotkey. Perhaps it is a different issue in your scenario. I would check if `CTRL+D` is configured to be handled by VsVim, not by VS itself.
