### ISSUE TITLE
Moving to GitHub Actions

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2974]
The repository uses AzDO pipelines today because that was the only available choice at the time I added it. It's worked really well for VsVim so far but it has some associated costs: 

1. Maintenance: have to keep an AzDO instance alive with associated pipelines. That has an entirely separate security model that I have to maintain. 
2. Contributions: GitHub Actions are _the way_ that PRs are validated these days. All the documentation and community knowledge is in terms of GitHub Actions. That means it's hard to get help with the AzDO work and expand to new scenarios. 

As such I'm going to transition the repo to use GitHub actions over the next week or so. This should mostly just result in headaches for me during the transition :smile: 

Work: 
- [x] Windows build and test loop
- [x] MacOS build and test loop 
- [x] Publish VSIX
- [x] Publish .mpack file
- [x] MacOS release workflow

**Comment by jaredpar** [comment]
I will be using the branch `/dev/gha` for the work here. A PR into that branch won't trigger the AzDO pipeline so I can keep it independent for the time being

**Comment by nosami** [comment]
Don't forget the work to publish the .mpack file (VSIX mac equivalent) on the Releases page :)
