### ISSUE TITLE
when on NORMAL mode, there's no Normal string indicator like visual mode

### ISSUE THREAD

**Issue by ianzhang366** [VsVim/VsVim#2982]
**Describe the bug**
when on NORMAL mode, there's no `-- NORMAL --` string indicator like visual mode `-- VISUAL --`

**To Reproduce**
1.  open vs2022
2. open a file and make sure the mouse is focused on a file

**Expected behavior**
When on normal mode, we should show a string at the left bottom corner saying `-- NORMAL --`

**Screenshots**
 
![image](https://user-images.githubusercontent.com/55893269/175315668-cdb23118-ea1a-4b33-908a-c426f52a7288.png)

The above corner should show `-- NORMAL --` string.

**Environment (please complete the following information):**

- Visual Studio version: 2022
- VsVim version: 2.10.0.5
- Programming Language: csharp
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by jaredpar** [comment]
VsVim is emulating vim behavior and by default there is no normal mode indicator. Consider gVim on my machine. 

<img width="495" alt="image" src="https://user-images.githubusercontent.com/146967/175319872-d759376b-96b8-4593-8474-12073a632a10.png">

Is there a setting I'm unaware of that ads this?

**Comment by ianzhang366** [comment]
Hi @jaredpar thanks for the reply! Thanks for the nice project as well!

you are right! In vim I need to do `set statusline=%!mode()` to get the above working... not sure if we go the `mode()` function `VsVim`.

Another issue is, at the output window of `VsVim`, I'm seeing `VsVim Error Status End` but I don't understand what the meaning of `VsVim Error Status`... can you please point to me the doc or code for it?

![image](https://user-images.githubusercontent.com/55893269/175325013-884e87be-7bbe-4434-b94f-fd73ffe65df5.png)

**Comment by mark-strelau-insurity** [comment]
How was this resolved?   I get the same VsVim Error Status Start/End messages in the output window.  I'm running 2.10.0.6 (which I believe is the latest version of vivim).  Visual Studio Professional 2022  v17.14.0
