### ISSUE TITLE
.vsvimrc not loading

### ISSUE THREAD

**Issue by Zer0xTJ** [VsVim/VsVim#2985]
**Describe the bug**
IM trying to setup my vsvimrc but it's not working (win 10)

**To Reproduce**
I want to enable system clipboard, 

but it's not working when i use .vsvimrc

1.  go to ~/.vsvimrc
2.  add `set clipboard=unnamed,unnamedplus`
3. save file
4. open visual studio (2022)
5.  visual mode -> yank (Y)
6. Ctrl+v in system
7. not working

**Expected behavior**
It should paste the content I yank from visual studio

im running win 10 ( visual studio 2022)

- Visual Studio version: 2022
- VsVim version: 2.10.0.5
- Programming Language: c++
- Check(Type 'x') any that are installed:

    - [ ] ReSharper
    - [ ] Visual Assist

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by Wizmann** [comment]
Same problem here with simple `_vsvimrc` file ([link][1])

Environment: Win11, VS2022, C++, no ReSharper, no Visual Assistent

The `set vimrc?` commands show the right path to the file, but appearently it doesn't really loaded.

[1]: https://gist.github.com/Wizmann/8da9829fd934767cbc3ff7130efde259

**Comment by Zer0xTJ** [comment]
It was my fault, I didn't notice the .txt in the filename, removing .txt from the file name solved the issue
