### ISSUE TITLE
Manual Vim Configuration

### ISSUE THREAD

**Issue by PRATIK-CHOLKE** [VsVim/VsVim#2989]
While setting vim for vs code I have modified my **settings.json** and **keybindings.json** files. How do apply that kinds of modifications in Visual Studio 2022? 

Following are two files from vscode.

***settings.json***

    {
    "vim.easymotion": true,
        "vim.incsearch": true,
        "vim.useSystemClipboard": true,
        "vim.useCtrlKeys": false,
        "vim.hlsearch": true,
        "vim.insertModeKeyBindings": [
            {
              "before": ["j", "j"],
              "after": ["<Esc>"]
            }
        ],
        "vim.normalModeKeyBindingsNonRecursive": [
            {
              "before": ["<leader>", "d"],
              "after": ["d", "d"]
            },
            {
              "before": ["<C-n>"],
              "commands": [":nohl"]
            }
        ],
        "vim.leader": "<space>",
        "vim.handleKeys": {
            "<C-a>": false,
            "<C-f>": false
        },
    }

***keybindings.json***

    [
        {
            "key": "tab",
            "command": "tab",
            "when": "editorTextFocus && !editorTabMovesFocus"
        },
        {
            "key": "shift-tab",
            "command": "outdent",
            "when": "editorTextFocus && !editorTabMovesFocus"
        }
    ]

**Note:** I have installed VsVim 2022 extension on Visual Studio 2022.

**Comment by jaredpar** [comment]
To customize VsVim in Visual Studio you generally apply the desired mappings to your `_vsvimrc` file. There you can use standard `:nmap` style commands to customize your bindings just as you would for vim proper.

**Comment by PRATIK-CHOLKE** [comment]
> To customize VsVim in Visual Studio you generally apply the desired mappings to your `_vsvimrc` file. There you can use standard `:nmap` style commands to customize your bindings just as you would for vim proper.

Okay. But could you please let me know where _vsvimrc file is located? Or do I need to create that file? My vimfiles folder has subfolders as `keymap plugin syntax` etc but all those folders are empty.

**Comment by cbates-** [comment]
Look in %USERPROFILE% (or $env:USERPROFILE, in PowerShell).
(I think it could also be named .vsvimrc.)
If you don't have vim installed, you will probably have to create the _vsvimrc file.
Note jaredpar's comment -- _vsvimrc uses vim keymapping syntax, not VSCode's json.
Also, not all mappings supported in VSCodeVim are necessarily supported in VsVim for VS2022.

**Comment by jaredpar** [comment]
> But could you please let me know where _vsvimrc file is located? 

It should exist in the same place as a `_vimrc` file. Typically most users put this inside of `%USERPROFILE%`. 

> Or do I need to create that file?

You need to create that file

**Comment by PRATIK-CHOLKE** [comment]
Okay. Thank you @jaredpar and @cbates- I have got what all is needed. Closing the issue.

**Comment by edigun-man** [comment]
> Okay. Thank you @jaredpar and @cbates- I have got what all is needed. Closing the issue.

SO can i have your setting in vsvimrc? i just need jj <ESC>

**Comment by apsampaio** [comment]
> > Okay. Thank you @jaredpar and @cbates- I have got what all is needed. Closing the issue.
> 
> SO can i have your setting in vsvimrc? i just need jj

`
"jj For Qicker Escaping between normal and editing mode.
inoremap jj <ESC>
`

add this to your .vsvimrc
