### ISSUE TITLE
Enable/Disable VsVim not working

### ISSUE THREAD

**Issue by StarBax89** [VsVim/VsVim#2996]
**Describe the bug**
cmd+F12+Shift does not disable/enable VsVim

**To Reproduce**

Press cmd+shift+F12  -> nothing happens

**Expected behavior**
Press cmd+shift+F12  -> disable/enable VsVim

**Screenshots**

**Environment (please complete the following information):**

- Visual Studio version: 2019 16.9.9
- VsVim version: 2.8.0.0
- Check(Type 'x') any that are installed:
    - [x] ReSharper
    - [ ] Visual Assist

**Additional context**
German keyboard

**Comment by webgtx** [comment]
> **Describe the bug** cmd+F12+Shift does not disable/enable VsVim
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> Press cmd+shift+F12 -> nothing happens
> 
> **Expected behavior** Press cmd+shift+F12 -> disable/enable VsVim
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Environment (please complete the following information):**
> 
> * Visual Studio version: 2019 16.9.9
> * VsVim version: 2.8.0.0
> * Check(Type 'x') any that are installed:
>   
>   * [x]  ReSharper
>   * [ ]  Visual Assist
> 
> **Additional context** German keyboard

### got the same issue 🍞

**Comment by webgtx** [comment]
![image](https://user-images.githubusercontent.com/62614322/185734425-46e1022f-1eab-4603-9633-0bbc0d1e0375.png)

**Comment by jaredpar** [comment]
That keyboard shortcut is usually very reliable but it's possible something about the setup is breaking it. Can you try the following: 

- View -> Other Windows -> Command Window
- Type: VsVim.SetDisabled

That is a direct command to force it to be disabled. If that doesn't work then there are some deeper issues to work out.

**Comment by StarBax89** [comment]
The command is working fine.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Jared Parsons ***@***.***>
Gesendet: Monday, August 22, 2022 6:20:48 PM
An: VsVim/VsVim ***@***.***>
Cc: StarBax89 ***@***.***>; Author ***@***.***>
Betreff: Re: [VsVim/VsVim] Enable/Disable VsVim not working (Issue #2996)


That keyboard shortcut is usually very reliable but it's possible something about the setup is breaking it. Can you try the following:

  *   View -> Other Windows -> Command Window
  *   Type: VsVim.SetDisabled

That is a direct command to force it to be disabled. If that doesn't work then there are some deeper issues to work out.

**Comment by StarBax89** [comment]
The commands (SetEnabled/SetDisabled) are working fine.

**Comment by jaredpar** [comment]
That means it's an issue in the key processing. Can you try the following. First enable the Output window diagnostics by setting `Output Window` to `True`

<img width="359" alt="image" src="https://user-images.githubusercontent.com/146967/185985024-493fe312-424c-4b19-b196-8cf3687bf7c0.png">

Then open the Output Window (View -> Output Window) and flipping it to VsVim 

<img width="415" alt="image" src="https://user-images.githubusercontent.com/146967/185985113-e23462d4-cfa6-4a14-b4e5-914eb2401593.png">

After that attempt to hit <kbd>Ctrl-Shift-F12</kbd> and send me the text that shows up in that window.

**Comment by StarBax89** [comment]
VsVim VimBuffer.Process: none:LeftMouse:None
VsVim VimBuffer.Process: none:LeftDrag:None
VsVim VimBuffer.Process: none:LeftRelease:None
VsVim VimKeyProcessor::KeyDown LeftCtrl None Control
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::KeyDown LeftShift None Control, Shift
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimBufferCoordinator::PreviewKeyUp F12
VsVim VimKeyProcessor::KeyUp F12 Control, Shift
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp F12
VsVim VimBufferCoordinator::PreviewKeyUp LeftShift
VsVim VimKeyProcessor::KeyUp LeftShift Control
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp LeftShift
VsVim VimBufferCoordinator::PreviewKeyUp LeftCtrl
VsVim VimKeyProcessor::KeyUp LeftCtrl None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp LeftCtrl

**Comment by jaredpar** [comment]
Here is what a successful usage looks like 

```
VsVim VimKeyProcessor::KeyDown F12 None Control, Shift
VsVim VimBuffer.Process: none:F12:Control, Shift
VsVim VimKeyProcessor::KeyDown Handled = True
VsVim VimBufferCoordinator::PreviewKeyUp F12
VsVim VimKeyProcessor::KeyUp F12 Control, Shift
VsVim VimKeyProcessor::KeyUp Handled = False
```

In your log I see only 

```
VsVim VimKeyProcessor::KeyDown LeftShift None Control, Shift
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimBufferCoordinator::PreviewKeyUp F12
VsVim VimKeyProcessor::KeyUp F12 Control, Shift
VsVim VimKeyProcessor::KeyUp Handled = False
```

Essentially the Key Down event for <kbd>F12</kbd> isn't registering at all. That means it's being intercepted at a layer above what VsVim can see. Generally that happens because of one of the following:

1. Visual Studio has a command mapped to that key combination. Those key presses are intercepted at a very low level. 
2. A non-English keyboard is sending key codes in a way that I didn't anticipate. I attempt to keep VsVim as keyboard language neutral as possible but occasionally bugs do pop up. 

I think (1) is far more likely here, especially since I see the <kbd>F12</kbd> up event. 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/146967/186008303-deb56cf0-5903-44c9-a581-a45c66a9d419.png">

Can you go to the Keyboard options menu, hit <kbd>Ctrl+Shift+F12</kbd> in the specified box and see if any commands are bound to it? They would show up in the box at the bottom of that menu. If there are any go and unmap them from that keyboard combination and it should start working.

**Comment by StarBax89** [comment]
oh damn, I could have thought of that myself. The key combination was actually used by Visual Studio, after removing the shortcut it is now working.
Thank you very much for your help.
