### ISSUE TITLE
MacOS wiki page to include all commands from Visual Studio for Mac (v17.3)

### ISSUE THREAD

**Issue by jawee** [VsVim/VsVim#3006]
I have added all the commands I could get out from the keybindings menu in Visual Studio for Mac, to the MacOS page on the wiki. I think it could be helpful to people, as I could not find an official commands reference from Microsoft.

If you don't think it's a good idea, the issue can be closed. :) 

Link to the page in my own repository: https://github.com/jawee/VsVim-wiki/blob/master/macOS-guide.md

(I couldn't find a way to submit a PR to the wiki)

**Comment by nosami** [comment]
This is great! I was meaning to get around to this for a long time :)

Can you edit the wiki directly?

**Comment by jawee** [comment]
Either I'm too stupid to figure out how to do it, or I can't do it. Unfortunately. But I only added that section, so you could just copy it from my repository and add it in here.

**Comment by nosami** [comment]
Ok. I copy and pasted your page into the wiki here. Thanks for doing this 👍

Maybe the wiki is locked down. I don't have admin rights on this repo.

**Comment by nosami** [comment]
Maybe I should create a command that dumps out a list of available commands? 🤔

**Comment by nosami** [comment]
I created an issue for it. Should be pretty easy to implement.
