### ISSUE TITLE
Unable to save file with :wq

### ISSUE THREAD

**Issue by nanoric** [VsVim/VsVim#3009]
**Describe the bug**
Unable to save file with :wq

**To Reproduce**
open a file, edit, then type :wq\<Enter>

**Expected behavior**
File saved and closed.

**Acual behavior**
File not saved but closed.

- Visual Studio version: Visual Studio 2022 17.3.32825.248
- VsVim version: VsVim 2022 2.10.0.5
- Programming Language: C++
- Check(Type 'x') any that are installed:
    - [x] ReSharper: ReSharper C++ 2022.2.20220820.134329
    - [-] Visual Assist

**Comment by weiconglu** [comment]
Same issue
VisualStudio.17.Release/17.3.4+32901.215
VsVim   2.10.0.5

**Comment by jnothstine** [comment]
Having the same problem now.  Very frustrating as it is a habit to do :wq and now, I frequently lose changes I make because of this issue.

**Comment by pettys** [comment]
I thought I was somehow closing files without saving changes - half-relieved to find this bug here. :)

**Comment by pmurraygenesis** [comment]
Having the same problem and I've lost work as a result

**Comment by pettys** [comment]
I'm still experiencing this issue on VS 2022 17.3.6.

> This issue may be resolved in visual studio 2022 17.3.6 released on 2022-11-10

**Comment by pmurraygenesis** [comment]
Indeed the issue reappeared for me after a restart unfortunately

**Comment by nanoric** [comment]
seems this issue is fixed.
