### ISSUE TITLE
:w command inserts new line in Razor files (Vs for Mac)

### ISSUE THREAD

**Issue by lordfeck** [VsVim/VsVim#3011]
**Describe the bug**
When editing Razor cshtml files, issuing the command :w will insert a new line. My guess is this is caused by the ENTER command passing through the Vim layer to the VS editor layer.

**To Reproduce**

1.  Enable VsVim 2.8.0.17 on Vs Mac 17.3.4
2. Edit a razor file
3. Issue the 'write' vim command
4. Observe the unwanted newline

**Expected behavior**
I expected Vim to take the `:w` command and write the buffer. A new line should not be inserted into the document.

This doesn't happen when saving any other source file.

**Environment (please complete the following information):**

- Visual Studio version: 17.3.4 (Mac)
- VsVim version: 2.8.0.17
- Programming Language: C#/Razor

**Comment by nosami** [comment]
Thanks for reporting this. I can reproduce this bug. Should be an easy fix

**Comment by nosami** [comment]
Fixed in 2.8.0.18

**Comment by lordfeck** [comment]
Thanks @nosami
