### ISSUE TITLE
Insert mode enter key is introducing "coc#pum#visible() ? coc#pum#confirm()" string.

### ISSUE THREAD

**Issue by traderdude123** [VsVim/VsVim#3014]
**Describe the bug**
In insert mode after hitting enter i get coc#pum#visible() ? coc#pum#confirm(). I have keep deleting it.

**To Reproduce**
In insert mode  after hitting enter key "coc#pum#visible() ? coc#pum#confirm()" is displayed.

**Expected behavior**
After hitting enter in insert mode , must go to new line.

**Environment (please complete the following information):**

- Visual Studio version: Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.6

- VsVim version: latest from market place.
- Programming Language: C++

**Comment by jaredpar** [comment]
Likely you have an existing .vimrc file that VsVim is picking up and trying to process. That is resulting in a key map that is being executed here. 

Can you try adding a `.vsvimrc` file into your `%USERPROFILE% directory? That will be preferred by VsVim and it will stop loading your existing .vimrc. You can copy over the parts that are relevant to VS based development.

**Comment by traderdude123** [comment]
does VsVim prefer _vsvimrc or .vsvimrc since i am on windows.

but yes i suspected it was picking up the existing _vimrc config , so i deleted all vim installations and config and its working fine now. 

But shouldn't vsvim create its own config file on installation of vsvim? Is there a way to completely ignore existing vim configs on the system.

This will cause issues if we have vim and vsvim installed on the same system.

**Comment by jaredpar** [comment]
> But shouldn't vsvim create its own config file on installation of vsvim?
> This will cause issues if we have vim and vsvim installed on the same system.

In retrospect if I were doing VsVim over again I would not load existing .vimrc files by default. When I initially started the project though I was just looking at simple rc files, it was easy to add support for those and it became a **very** popular feature. As it got more popular more complex rc files started coming along and made me regret my decision a bit. It was too late to pull it out though as it would break too many customers. 

> Is there a way to completely ignore existing vim configs on the system.

Yes. You can change the option to only consider vsvim rc files 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/146967/191058711-66fc349e-7cf3-44c0-b260-e7aa13c46432.png">
