### ISSUE TITLE
CTRL+O and CTRL+I don't switch between files

### ISSUE THREAD

**Issue by adrianhoppe** [VsVim/VsVim#3021]
Hi all,

please see the bug report below.

Thanks a lot!
Best,
Adrian

**Describe the bug**
CTRL+O and CTRL+I don't switch between files, e.g., after using `gd` or Shift+Tab.

**To Reproduce**
Setup: Have a project with two files A and B. File A uses a function, e.g. `MyFunction()`, and File B implements that function, `public void MyFunction() {....}`.
1. Open file A.  
2. Use a command to jump to file B, e.g., by either:
  2.1 Moving cursor over call to `MyFunction()` and using `gd` to jump to the definition file B.
  2.2 Using `Shift+Tab` and selecting file B.
4. Now, typing `CTRL+O` should jump back to file A but it doesn't.

**Expected behavior**
`CTRL+O` should move back in the vim jump list and return to file A but it remains in file B (and traces back any jumps in file B if there are any).

**Screenshots**
n/A

**Environment**

- Visual Studio version: Microsoft Visual Studio Professional 2022 (64-bit) Version 17.3.5
- VsVim version: 2.10.0.5
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
Moving forward and backward in the jump list with CTRL+O and CTRL+I works fine within one file but seems to have some issues when jumping between files.
It also keeps multiple jump lists for each file.  
Is there an option to switch from this "local" jump list to a "global" jump list that I have missed maybe?

Also mentioned by [muchcharles](https://github.com/muchcharles) in https://github.com/VsVim/VsVim/issues/2514#issuecomment-876902677

**Comment by nosami** [comment]
Check this section from the wiki https://github.com/VsVim/VsVim/wiki/VsVim-Nonstandard-Behavior#jumps
