### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by PaddiM8** [VsVim/VsVim#3024]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [ ] Vim
    - [x] Vim plugin

It doesn't currently seem to be possible to install VsVim on the ARM version of Visual Studio (Preview).

**Comment by nosami** [comment]
Windows?

**Comment by PaddiM8** [comment]
@nosami Yes. Visual Studio on Windows for ARM.

**Comment by rodpl** [comment]
I am using Windows 11 ARM with VisualStudio 17.4 preview ARM installed. I am missing vivim much :(.

https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/

**Comment by jaredpar** [comment]
@PaddiM8 fixed this via #3026. Thanks!

I published a new release this morning so it should go live shortly.
