### ISSUE TITLE
Cannot build under VS2022 ("$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" was not found)

### ISSUE THREAD

**Issue by chtenb** [VsVim/VsVim#3073]
**Describe the bug**

I wanted to take a stab at fixing some issues, but I can't seem to compile this extension unfortunately.
When building the VsVim2022 project I get

```
VsVim\References\Vs2022\Vs2022.Build.targets(32,11): error MSB4226: The imported project "$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" was not found. Also, tried to find "$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0" . These search paths are defined in "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
```

The project VimApp builds and runs fine.

**To Reproduce**

1. Install VS2022
2. Install required VS features (F#/Desktop/VSX)
3. Build solution / try to start VsVim2022.

**Expected behavior**
The project building out-of-the-box, or a documentation of possible missing things in https://github.com/VsVim/VsVim/blob/master/Documentation/Developing.md

**Screenshots**
![image](https://github.com/VsVim/VsVim/assets/1030961/d0ce3a3d-23d5-4d0a-9a2e-ebc4af007e9a)

**Environment (please complete the following information):**

- Visual Studio version: 17.7.5
- VsVim version: latest commit

**Comment by hailong-ph** [comment]
Hi @chtenb , I met this issue too, and [this](https://github.com/dotnet/msbuild/issues/8168#issuecomment-1625318954) helped.  Hope it works for you too.

**Comment by nosami** [comment]
This was fixed by https://github.com/VsVim/VsVim/pull/3079
