### ISSUE TITLE
When I switch from normal mode to insert mode, the cursor appears one character behind the character it's on top of. 

### ISSUE THREAD

**Issue by bylucaspaiva** [VsVim/VsVim#3076]
When I switch from normal mode to insert mode, the cursor appears one character behind the character it's on top of. This causes some issues if you're on the last letter of the line, as when you return to insert mode, the cursor is positioned before the last letter and not after it, requiring you to click the '->' button to continue typing.

**Comment by nosami** [comment]
I think what you are describing is standard Vim behavior.

If you are on the last character on the line and want to append after it,
use `a` instead of `i` to enter insert mode.
If you are not on the last character and you want to append at the end of
the line, use `A`

**Comment by bylucaspaiva** [comment]
Thanks a lot!
