### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by RevisedJDUDE2** [VsVim/VsVim#3083]
**Describe the bug**

**To Reproduce**

1.  Go to 'the file ending on .vsix'
2. Click on install

**Expected behavior**
it should have installed vsvim

**Environment (please complete the following information):**

- Visual Studio version: 17.8.0 vs 2022
- VsVim version: 2.8.0.0
- Programming Language: C++
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

Error Logs:
11/24/2023 12:28:16 AM - Microsoft VSIX Installer
11/24/2023 12:28:16 AM - -------------------------------------------
11/24/2023 12:28:16 AM - vsixinstaller.exe version:
11/24/2023 12:28:16 AM - 17.8.2365+1ea9c98024
11/24/2023 12:28:16 AM - -------------------------------------------
11/24/2023 12:28:16 AM - Command line parameters:
11/24/2023 12:28:16 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Emachines\Downloads\VsVim (1).vsix
11/24/2023 12:28:16 AM - -------------------------------------------
11/24/2023 12:28:16 AM - Microsoft VSIX Installer
11/24/2023 12:28:16 AM - -------------------------------------------
11/24/2023 12:28:17 AM - Initializing Install...
11/24/2023 12:28:17 AM - Searching for applicable products...
11/24/2023 12:28:19 AM - Found installed product - Visual Studio Community 2022
11/24/2023 12:28:19 AM - Found installed product - Global Location
11/24/2023 12:28:19 AM - Extension Details...
11/24/2023 12:28:19 AM - 	Identifier         : VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3
11/24/2023 12:28:19 AM - 	Name               : VsVim
11/24/2023 12:28:19 AM - 	Author             : Jared Parsons
11/24/2023 12:28:19 AM - 	Version            : 2.8.0.0
11/24/2023 12:28:19 AM - 	Description        : VIM emulation layer for Visual Studio
11/24/2023 12:28:19 AM - 	Locale             : en-US
11/24/2023 12:28:19 AM - 	MoreInfoURL        : https://github.com/VsVim/VsVim
11/24/2023 12:28:19 AM - 	InstalledByMSI     : False
11/24/2023 12:28:19 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
11/24/2023 12:28:19 AM - 	SignatureState     : Unsigned
11/24/2023 12:28:19 AM - 	Supported Products : 
11/24/2023 12:28:19 AM - 		Microsoft.VisualStudio.Community
11/24/2023 12:28:19 AM - 			Version : [14.0,17.0)
11/24/2023 12:28:19 AM - 			ProductArchitecture : x86
11/24/2023 12:28:19 AM - 		Microsoft.VisualStudio.IntegratedShell
11/24/2023 12:28:19 AM - 			Version : [14.0,17.0)
11/24/2023 12:28:19 AM - 			ProductArchitecture : x86
11/24/2023 12:28:19 AM - 		Microsoft.VisualStudio.Pro
11/24/2023 12:28:19 AM - 			Version : [14.0,17.0)
11/24/2023 12:28:19 AM - 			ProductArchitecture : x86
11/24/2023 12:28:19 AM - 		Microsoft.VisualStudio.Enterprise
11/24/2023 12:28:19 AM - 			Version : [14.0,17.0)
11/24/2023 12:28:19 AM - 			ProductArchitecture : x86
11/24/2023 12:28:19 AM - 		AtmelStudio
11/24/2023 12:28:19 AM - 			Version : [7.0]
11/24/2023 12:28:19 AM - 			ProductArchitecture : x86
11/24/2023 12:28:19 AM - 	References         : 
11/24/2023 12:28:19 AM - 	Prerequisites      : 
11/24/2023 12:28:19 AM - 		-------------------------------------------------------
11/24/2023 12:28:19 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
11/24/2023 12:28:19 AM - 		Name         : Visual Studio core editor
11/24/2023 12:28:19 AM - 		Version      : [11.0,17.0)
11/24/2023 12:28:19 AM - Signature Details...
11/24/2023 12:28:19 AM - 	Extension is not signed.
11/24/2023 12:28:19 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Charlie-Porter** [comment]
I was able to workaround this exact exception using the vsvim 2022 version found on[ marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVim2022Preview).

**Comment by RevisedJDUDE2** [comment]
it works now after installing it from the official website.
