### ISSUE TITLE
Save feature for `set relativenumber`

### ISSUE THREAD

**Issue by jonesy-b-dev** [VsVim/VsVim#3093]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [ ] Vim
    - [ x] Vim plugin

**Is your feature request related to a problem? Please describe.**

Currently i need to run the `set relativenumber` every time i open a new file. And when i restart vs i can start over again. 
Is there a way to save it?

**Describe the solution you'd like**
That the setting saves and applies globally 

Note:
Please refer to the following. The goals of this project are written.
https://github.com/VsVim/VsVim/blob/master/Documentation/Project%20Goals.md

**Comment by nosami** [comment]
You can put the following inside your `~/.vsvimrc` file.

```
set number
set relativenumber
```

**Comment by jonesy-b-dev** [comment]
@nosami i have no such file on my pc, where should i create that? just in my user folder?

**Comment by nosami** [comment]
If you have Vim, you can just do `vim ~/.vsvimrc`.

Or you can use other folders - see here
<https://github.com/VsVim/VsVim/wiki/Settings-Reference#rc-file>

**Comment by jonesy-b-dev** [comment]
Yes thank you i got it fixed!
