### ISSUE TITLE
run `:set clipboard=unnamed` on startup?

### ISSUE THREAD

**Issue by danielk892374** [VsVim/VsVim#3102]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [ ] Vim
    - [X] Vim plugin

If the function you request is realized by Vim or Vim plugin,
When you link the URL that is related,
We will make it easier to understand its function.

**Is your feature request related to a problem? Please describe.**
I'm trying to set `:set clipboard=unnamed` by default

**Describe the solution you'd like**
- .vim or similar startup "dotfile" to add commands that exectute on start
- option to sync vim and system clipboard in visual studio options dialog

**Describe alternatives you've considered**
Running it each time on start (tedious)

Note:
Please refer to the following. The goals of this project are written.
https://github.com/VsVim/VsVim/blob/master/Documentation/Project%20Goals.md

**Comment by nosami** [comment]
https://github.com/VsVim/VsVim/wiki/Settings-Reference
