### ISSUE TITLE
How can I install this plugin offline 

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [VsVim/VsVim#3103]
How can I install this plugin offline

**Comment by nosami** [comment]
iwr -useb
https://jaredparmsft.gallerycdn.vsassets.io/extensions/jaredparmsft/vsvim2022preview/2.10.0.6/1667494131532/VsVim.vsix
-OutFile VsVim.vsix
VSIXInstaller.exe /quiet /admin VsVim.vsix

On my phone, so please excuse formatting.

**Comment by wangwenqiangGitHub** [comment]
> VSIXInstaller.exe /quiet /admin VsVim.vsix

Can't Install , Still some error for me

**Comment by nosami** [comment]
What's the error? Is VSIXInstaller on the PATH?

Try running from Administrator Developer Powershell

**Comment by wangwenqiangGitHub** [comment]
> What's the error? Is VSIXInstaller on the PATH?
> 
> Try running from Administrator Developer Powershell

Yes, It's my fault, thanks very much
