### ISSUE TITLE
:set relativenumber not working

### ISSUE THREAD

**Issue by tomasstupavsky** [VsVim/VsVim#3108]
**Describe the bug**
When I try to enable relative line numbers using `:set relativenumber`, only the non-relative numbers pop up.

**To Reproduce**

1. Type in command `:set relativenumber`
2. See only non-relative numbers pop up

**Expected behavior**
I would expect the relative numbers to pop up on the left.

**Screenshots**
![image](https://github.com/VsVim/VsVim/assets/126089313/fc645bfe-854d-428a-a4bf-c0defb6ec2ed)
![image](https://github.com/VsVim/VsVim/assets/126089313/94a0009b-8975-4e8c-9787-78292a57aa14)

**Environment (please complete the following information):**

- Visual Studio version: 17.9.6
- VsVim version: 2.10.0.6
- Programming Language: plain text
- Check(Type 'x') any that are installed:
    - [x] ReSharper
    - [ ] Visual Assist

**Comment by kbilsted** [comment]
Seems ok here

![image](https://github.com/VsVim/VsVim/assets/1616338/fb71d90d-7e71-4419-b56a-9c57e748900f)

Windows 10
Visual Studio version: 17.10.1
VsVim version: 2.10.0.6
Programming Language: c#
Programming Language: plain text

**Comment by Asttear** [comment]
Try enable line number display in Visual Studio settings.

**Comment by tomasstupavsky** [comment]
![image](https://github.com/user-attachments/assets/3be04d03-0895-4330-be65-bc902b1a413c)
Enabling Line Numbers in Options resolved the issue. Thanks so much!
