### ISSUE TITLE
Custom key shortcuts

### ISSUE THREAD

**Issue by CoolCoderSuper** [VsVim/VsVim#3121]
**Feature category**
- Check(Type 'x') any that Applicable item:
    - [x] Vim
    - [ ] Vim plugin

**Is your feature request related to a problem? Please describe.**
I'm coming from the IdeaVim plugin and one thing that it can do is this in vimrc:
```
map <leader>ac <Action>(ShowIntentionActions)
map <leader>rn <Action>(RenameElement)
map <leader>rm <Action>(ExtractMethod)
map <leader>rv <Action>(IntroduceVariable)
map <leader>rf <Action>(IntroduceField)
map <leader>rs <Action>(ChangeSignature)
map <leader>l <Action>(ReformatCode)
" Navigation
map <leader>gd <Action>(GotoDeclaration)
map <leader>gy <Action>(GotoTypeDeclaration)
map <leader>gi <Action>(GotoImplementation)
map <leader>gu <Action>(ShowUsages)
map <leader>gr <Action>(FindUsages)
map <leader>gf <Action>(Back)
map <leader>gb <Action>(Forward)
map <leader>ff <Action>(GotoFile)
map <leader>fs <Action>(GotoSymbol)
map <leader>s <Action>(Switcher)
" General
map <leader>z <Action>(ToggleZenMode)
map <leader>d <Action>(Debug)
map <leader>b <Action>(ToggleLineBreakpoint)
map <leader>c <Action>(Stop)
map <leader>r <Action>(Run)
map <leader>bb <Action>(RebuildStartupProject)
```

**Describe the solution you'd like**
A way to create custom mapping to visual studio options.

**Describe alternatives you've considered**
A GUI in the setttings.

Note:
Please refer to the following. The goals of this project are written.
https://github.com/VsVim/VsVim/blob/master/Documentation/Project%20Goals.md

**Comment by nosami** [comment]
You can map commands like I do in here https://github.com/nosami/configs/blob/master/.vsvimrcwindows

**Comment by CoolCoderSuper** [comment]
Awesome, thank you so much.
