### ISSUE TITLE
Support for jumplist, ^o, and ^i

### ISSUE THREAD

**Issue by kalebpederson** [VsVim/VsVim#485]
See :help jumplist

Here's one simple use case: I'll often be working on a section of code and use \* or some other command which jumps to a different position.  After I'm done making my edits, I'll then use ^o and ^i to navigate back and forth until I'm done.

**Comment by wererogue** [comment]
Hi, I'm using 1.8.0.0 and I've been annoyed by visual studio's navigation so I wanted to see if VsVim's jumplists were working well (I've used them in Vim, just didn't think to check for VsVim).  ctrl-o and ctrl-i don't seem to be doing anything even though they're assigned to VsVim in the VsVim settings, and :jumps shows a "Parse error".
