### ISSUE TITLE
Add support for CTRL-A and CTRL-X

### ISSUE THREAD

**Issue by kalebpederson** [VsVim/VsVim#530]
See `:help ^A` and `:help ^X`.

Often when creating or asserting test data or working with arrays I'll want to be able to copy a line and then change the index by one which I do with one of the above commands.

**Comment by nadya-p** [comment]
For the sake of documentation: in order to enable ctrl+a and ctrl+x shortcuts, go to VS's shortcut settings, and remove current usages of "ctrl+a" and "ctrl+x". Now VsVim will handle those shortcuts.
