### ISSUE TITLE
Add support for Ctrl-r within command-line mode

### ISSUE THREAD

**Issue by kalebpederson** [VsVim/VsVim#551]
Assume I have identified some non-trivial text that I want to replace within a document and yanked it into the `a` buffer.  I'd then do the following from Vim's normal mode: `:%s/<Ctrl-R>a/substitution text/g`

**Comment by farzadmf** [comment]
I have this line in my `_vimrc` file:

    inoremap <C-Y> <C-r>

And when I press `CTRL + Y` in command bar, it doesn't do anything (I can paste in `INSERT` mode using `CTRL + Y`, but it has no effect in the command bar
