### ISSUE TITLE
Remove command line, and transfer in to default VS status bar (like in Viemu)

### ISSUE THREAD

**Issue by umek** [VsVim/VsVim#620]
I don't like second status bar in my code window. It would be nice to update default visual studio status bar with commands I entered. Like ViEmu does, when I type let's say :w it displayed instead of ready status in vs bar.

Thanks

**Comment by madsystem** [comment]
is this in the current version available, or do i need to get the latest git revision?

thx kris

**Comment by jaredpar** [comment]
@madsystem this isn't in the official gallery yet.  Will be in a few days.  

Short term you can use the open VSIX gallery to grab the latest without the need to build from source:

http://vsixgallery.com/guide/feed/
