### ISSUE TITLE
CTRL-V after / to search, pastes clipboard into document

### ISSUE THREAD

**Issue by MarkLIC** [VsVim/VsVim#623]
I had a Unicode character in my clipboard, and I wanted to search for it with `/`.

So I pressed `/`, then I pressed `CTRL-V` to paste the character, and instead it pasted the character where my caret was, in spite of being in normal mode (or command mode, since I had pressed `/` already).

This also happens with ASCII text in the clipboard.

I am using VsVim 1.0.3 with ReSharper 5.1, Visual Studio 2010 Professional, Windows 7 Professional x64.

**Comment by blainesch** [comment]
:+1:
