### ISSUE TITLE
Selection + direction keys + Visual Assist - again

### ISSUE THREAD

**Issue by rride** [VsVim/VsVim#626]
Hi,

I've recently upgraded from 0.9.6 to 1.0.3 and found that the bug https://github.com/jaredpar/VsVim/issues/319 with selection + direction keys came into existence again. I'm using Visual Assist's build 10.6.1849

**Comment by tsmoreland** [comment]
seeing this behavior in vs2019 with latest vsvim and visual assist - but only with h,k,l,m keys, using arrow keys works fine

**Comment by ricksladkey** [comment]
@tsmoreland, can you file a new issue? This old issue was possibly a different problem and even if it were the same problem there is no indication here of how or when it got fixed, so we might as well start from scratch. But you can reference this old issue.

**Comment by tsmoreland** [comment]
sure, I'll do that shortly
