### ISSUE TITLE
Undo undoes last several commands

### ISSUE THREAD

**Issue by jnothstine** [VsVim/VsVim#672]
Each time I do undo, it undoes all my previous commands to some set point.  I haven't figured out what the catalist for that point is.  I can make a change, let's say on line 51, and then make 10 other changes in various places in my document.  Then, I hit "u" and all changes to the one on line 51 get undone.  I have to go and redo all those changes manually.  Then, I do a bunch more changes and accidently hit "u" again.  I consider it an accident because I know this happens, it is just a habit to use undo.  All my changes back to the original change on line 51 get undone.

I just lost about 45 minutes of work because I hit "u" at the wrong time.  Unfortunately, I can't find a catalyst for the problem but it has happened to me twice tonight.

I will try to add more information if I can find the cause.  For now, this is quite difficult to deal with because I am trying to not undo my changes for obvious reasons.

**Comment by ImaginaryDevelopment** [comment]
I'm seeing this issue. Vs 2015 Update 3. 

**do I need to open a ticket or does this belong here?**


Copy Info from About Visual studio produces ->


> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01586
> 
> Installed Version: Enterprise
> 
> Architecture and Modeling Tools   00322-80000-00000-AA397
> Microsoft Architecture and Modeling Tools
>     
> UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
> 
> Microsoft Visual Studio Tools for Applications 2015   00322-80000-00000-AA397
> Microsoft Visual Studio Tools for Applications 2015
> 
> Visual Basic 2015   00322-80000-00000-AA397
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-80000-00000-AA397
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-80000-00000-AA397
> Microsoft Visual C++ 2015
> 
> Visual F# 2015   00322-80000-00000-AA397
> Microsoft Visual F# 2015
> 
> Application Insights Tools for Visual Studio Package   7.17.00119.9
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2015.1   14.1.21111.0
> ASP.NET and Web Tools 2015.1
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Azure App Service Tools v2.8.1   14.0.11123.0
> Azure App Service Tools v2.8.1
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
> Microsoft .NET Core Tools (Preview 2)
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> NuGet Package Manager   3.5.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> SQL Server Data Tools   14.0.60629.0
> Microsoft SQL Server Data Tools
> 
> SQL Server Integration Services   
> Microsoft SQL Server Integration Services Designer
> Version 13.0.1601.5
> 
> Syntax Visualizer   1.0
> An extension for visualizing Roslyn SyntaxTrees.
> 
> TypeScript   1.8.36.0
> TypeScript tools for Visual Studio
> 
> Visual F# Power Tools   2.5.6
> A collection of additional commands for F# in Visual Studio
> 
> VsVim   2.2.0.0
> VsVim is a Vim emulator for Visual Studio

**Comment by jaredpar** [comment]
@ImaginaryDevelopment 

This particularly area of VsVim is pretty heavily locked down now.  There are a number of internal diagnostics that are kept and checked for undo.  It also detects cases where it believes Visual Studio itself is in an error state.  When any of these conditions are seen VsVim will fall back to simple single undo / redo operations and notify the user. 

If you're still hitting an issue then it's most likely either 

1. A somewhat uncommon command, or uncommon combination of commands.
1. Bad interaction with another extension. 

Are there any commands you use which would fall into 1 above? 

I'm familiar with most of the extensions on the list above.  The others I don't believe would interact with undo / redo but it's possible.

**Comment by ImaginaryDevelopment** [comment]
is there a command/keylogging option I can turn on in vsvim to help find
it? as soon as it hits I could close the app, grab the log file, and resume
working perhaps?

**Comment by jaredpar** [comment]
@ImaginaryDevelopment there isn't any option that is exposed to end users.  I will change that for the release I'm trying to get out today / tomorrow.
