### ISSUE TITLE
Suddenly I miss them ... abbreviations (:ab)

### ISSUE THREAD

**Issue by MartinL0815** [VsVim/VsVim#702]
It's not a issue, but a feature request ... working with `LPCTSTR` and other obscured types in C++ my colleagues ask me to use the "old fashioned" `const TCHAR*` ... so suddenly I miss the VIM abbreviation capabilities, because I wanted to define abbreviations for the various string type synonyms.

What do you think ... when the abbreviations will come to VsVim?

**Comment by vzakanj** [comment]
:+1:

**Comment by idvorkin** [comment]
Double checking, this hasn't been implemented right?

**Comment by jaredpar** [comment]
@idvorkin correct, this is not implemented yet.

**Comment by 3rdey3** [comment]
👍

**Comment by wongjiahau** [comment]
Is this implemented yet?
