### ISSUE TITLE
Where is the options dialog?

### ISSUE THREAD

**Issue by michael-gram** [VsVim/VsVim#752]
This may be a stupid question, but after much searching, both online and through Visual Studio, I am totally unable to find the VsVim options dialog which lets me rebind Ctrl+C, etc. Can you please point me in the right direction?

**Comment by BigDub** [comment]
Am I just stupid? I still can't find it. Are we talking about right of where it shows you what line/column/character your cursor is on? Because my git plugin takes that corner of the screen. I do not see the word Options on the screen.
