### ISSUE TITLE
Implement nowrap-specific cursor and scroll commands

### ISSUE THREAD

**Issue by tremby** [VsVim/VsVim#787]
With nowrap on, the sequences

```
ze
zs
zh
zl
g$
g0
g^
```

do some useful things in vim -- scrolling the window left and right without moving the cursor, or moving the cursor with respect to the currently visible chunk of left-right space. Obviously check the docs -- counts are useful for many of them.

It'd be great to be able to use these in vsvim.

**Comment by ricksladkey** [comment]
The keys that being with `z` are described in `:vimhelp scroll-horizontal` and the ones the being with `g`  are described in `:vimhelp left-right-motions`.

**Comment by ricksladkey** [comment]
Turns out that `gm` should be included in this list. It is in implemented, but it doesn't work correctly when wrapping isn't in effect. In short, `gm` should never cause the screen to scroll.
