### ISSUE TITLE
"Vim Disabled. Type F12+Control, Shift to re-enable" is incorrect

### ISSUE THREAD

**Issue by vsviridov** [VsVim/VsVim#853]
F12 kicks in "Navigate to Definition" by default. It should read "Type Ctrl+Shift+F12 to re-enable".

**Comment by mattklein999** [comment]
I agree about the wording. It currently reads:

"Vim Disabled. Type F12+Control, Shift to re-enable"

So it looks like a two part key combo. Of course, when pressing Ctrl+F12 and then Shift doesn't do anything, you would expect that it is a typo and then try all three together.

However, if you have any items in your "Error List" then pressing Ctrl+Shift+F12 steps you through the items and does not re-enable VsVim. So I was left trying the two press combo for awhile when I went hunting for a solution (and ended up here).

---
In case anyone is in the same position I was, I just fixed my compile errors and then when the "Error List" was empty I could press Ctrl+Shift+F12 to re-enable VsVim.

**Comment by golergka** [comment]
I'm faced with this shortcut and it doesn't work. This is the first link I get when I google the error message. I have no idea how to switch VsVim back on. Can anyone help?

**Comment by wziska** [comment]
> I'm faced with this shortcut and it doesn't work. This is the first link I get when I google the error message. I have no idea how to switch VsVim back on. Can anyone help?
Try to remove CTRL+SHIFT+F12 shortcut for View.NextError command in VS Keyboard options.
