### ISSUE TITLE
Ctrl+U/Ctrl+D do not move cursor

### ISSUE THREAD

**Issue by ianwjhalliday** [VsVim/VsVim#858]
Ctrl+U/Ctrl+D move the cursor through the buffer along with the view in vim.  In VsVim the cursor is clipped to stay within the view, but it does not move until it is clipped.

**Comment by mdentremont** [comment]
@jaredpar Wow, can't believe this worked - great hack/solution!

**Comment by mlynch** [comment]
Just want to add this is still an issue using vsvim in VS 2022, and to fix it I had to go into the global keyboard settings like you said, find the binding for Ctrl+D, turns out it's used by Debug.Autos as a chord, so removing that binding worked and now vsvim handles it
