### ISSUE TITLE
F12 (go to definition) also puts VsVim into visual mode

### ISSUE THREAD

**Issue by ralphbecket** [VsVim/VsVim#891]
Hi,

if I hit F12 with the cursor in an identifier, the editor will correctly take me to the definition of that identifier, but VsVim also incorrectly moves into visual mode.

Cheers,
-- Ralph

**Comment by absilver808** [comment]
I seem to be facing this issue in vs2019. Any ideas how to fix?

**Comment by popizdeh** [comment]
Sorry no, I switched to VS Code.

**Comment by jackhub** [comment]
Still facing this issue in vs2022.

**Comment by frozax** [comment]
Even is the issue is still not fixed, and probably won't because it's been 10 years ;)
Did someone find a workaround? Maybe in .vimrc or anything?

**Comment by StephanMoeller** [comment]
I'm struggling with this one too. Have to type esc after each hit - it really sucks :(

**Comment by nosami** [comment]
Hmm, I just tried this and can reproduce. I always use `gd` for goto definition which is also switching to Visual Mode. I can take a look into this when I get some free time.

**Comment by StephanMoeller** [comment]
F12 goes to interface definition - same as gd. 
Ctrl + F12 goes to implementation - not possible in vim motion

**Comment by nosami** [comment]
> F12 goes to interface definition - same as gd. Ctrl + F12 goes to implementation - not possible in vim motion


I have this in my .vsvimrc for go to implementation.
`nmap gi :vsc Edit.GoToImplementation<CR>`

**Comment by nosami** [comment]
I just noticed that vsvim only goes into Visual Mode when the definition is in a decompiled file. Anybody else?

**Comment by StephanMoeller** [comment]
In my vs it goes to visual mode on every occasion.

**Comment by StephanMoeller** [comment]
I just tested this:

nmap gi :vsc Edit.GoToImplementation<CR>

It still enters visual mode when I type gi

**Comment by nosami** [comment]
For me, `gd` goes into Visual Mode only when jumping to decompiled code.
`gi` always goes into Visual Mode.

**Comment by StephanMoeller** [comment]
Ahhh same here. gd / f12 is not an issue but it goes to the definition which is the interface if such exists. gi / ctrl+f12 goes to implementation and this is the one that is a pain cause it goes to the visual mode.

Thanks for an awesome extension by the way. The only usable solution on the market for vim motion in vs. And thanks for taking your time discussing this issue!

**Comment by nosami** [comment]
> Ahhh same here. gd / f12 is not an issue but it goes to the definition which is the interface if such exists. gi / ctrl+f12 goes to implementation and this is the one that is a pain cause it goes to the visual mode.
> 
> Thanks for an awesome extension by the way. The only usable solution on the market for vim motion in vs. And thanks for taking your time discussing this issue!

You should thank @jaredpar for creating VsVim!

**Comment by StephanMoeller** [comment]
Ahhh, thought you were the creator :) But looks like you are able to merge PRs as well, right?

**Comment by nosami** [comment]
Yeah, I made this extension work for VSMac, but now that that is defunct, you can expect to see some Windows fixes from me :)

**Comment by StephanMoeller** [comment]
That would really be awesome. This is the only bug I have encountered so far so beside this, the extension is a breeze to use imo. :)

**Comment by backflip9** [comment]
Hi! As a workaround, is it possible to write a vim mapping that runs `:vsc Edit.GoToImplementation` and then returns to normal mode?

**Comment by StephanMoeller** [comment]
I already tried that, but it does not work. I suspect all the vim commands to be done by the time vs has jumped to the target. Do you know if vim motions has a ctrl f12 function? f12 goes to interface definition, I need to go to the declaration (actual methods)

**Comment by Toqozz** [comment]
I could be wrong, but I feel like this has something to do with whether visual studio decides to highlight the text after you go to definition/implementation.  It also happens after I've disabled vsvim with the Ctrl-Shift-F12 shortcut, and drops me back into visual mode, not always, but sometimes -- I think when the text gets selected.

**Comment by AstroWYH** [comment]
Is there any way to fix it? I've seen you talk about it for 12 years...

**Comment by jiaobendaye** [comment]
it just about vs. if you disable vsvim, f12 will select symbol too.

**Comment by gxrxrdx** [comment]
> I just noticed that vsvim only goes into Visual Mode when the definition is in a decompiled file. Anybody else?

I confirm that (VS Community 2022 17.10.5)

**Comment by backflip9** [comment]
I believe I tried adding a mapping like that too, @kcbanner. It seems like the GoToImplementation command kind of runs asynchronously so the ESC input is processed before visual studio has moved the cursor to the place where the implementation lives. As others have pointed out, though, this seems to be a problem in my setup even when VsVim is disabled. Using GoToDefinition or GoToImplementation always highlights the text that comprises the symbol I jumped to. VsVim just happens to interpret that automatic action as entering visual mode. I'm curious if that happens on your machine as well, and whether Visual Assist is the actual cause of the symbol being highlighted, since I use Visual Assist as well.

**Comment by kcbanner** [comment]
@backflip9 I just tried using standard F12 with Visual Assist disabled, and Intellisense enabled, and it does not enter visual mode after navigating to the symbol. So this seems to be a quirk of Visual Assist, and I suspect it's something to do with how it's asynchronous like you mentioned.

**Comment by panda7789** [comment]
Maybe next key strokes should wait until :vsc command ends?
This could be issue also on other places where :vsc commands are invoked, but on gotoDefinition it is noticeable annoying.

**Comment by kbilsted** [comment]
When using vs community or professional i experience the same issue. I think it started with the ladt 2 months. Tey upgrading vs...

Also updating breaks relative line numbering
