### ISSUE TITLE
Proposed mapping for C-O, C-I, C-]

### ISSUE THREAD

**Issue by philipmat** [VsVim/VsVim#916]
I proposed that by default VsVim maps the [jump-motions](http://vimdoc.sourceforge.net/htmldoc/motion.html#jump-motions) `Ctrl-O` and `Ctrl-I` to `View.NavigateBackward` and `View.NavigateForward`.

Also, although not part of jumps motions but rather [tag-command](http://vimdoc.sourceforge.net/htmldoc/tagsrch.html#tag-commands), it seems sensible to also bind `Ctrl-]` to `Edit.GoToDefinition` given that `C-LeftMouse` is already handled by Visual Studio that way.

Meanwhile, the following nmaps would do the same:

```
nmap <C-]> :vsc Edit.GoToDefinition<CR>
nmap <C-O> :vsc View.NavigateBackward<CR>
nmap <C-I> :vsc View.NagivateForward<CR>
```

**Comment by cjappl** [comment]
Hi! I propose we re-open this. I agree that as a new user, Ctrl-O seems broken, specifically when jumping between files (which is my most common use case).

I expect (as is the vim use case):
with cursor over symbol, <C-]> jumps to that symbol's definition, regardless of file
<C-o> jumps back to the previous location, regardless of file. The mappings provided in @philipmat's original post seem more accurate to vim behavior than the default VsVim behavior
