### ISSUE TITLE
gt & gT nolonger work

### ISSUE THREAD

**Issue by m0tive** [VsVim/VsVim#931]
This has changed in a recent update (possibly to 1.3.0), they worked previously.

Visual Studio 2010
VsVim v1.3.0.2

**Comment by skalpin** [comment]
I think this is broken again in the latest release with vs2013.

**Comment by jaredpar** [comment]
@skalpin just released 2.0.1 which fixes this problem.  There was a deployment hiccup with 2.0.0 that broke this functionality.

**Comment by skalpin** [comment]
@jaredpar I just got the update. Thanks for being so quick with that.
