### ISSUE TITLE
Hitting enter on any ex command on double slashed commented line puts in line feed

### ISSUE THREAD

**Issue by frizzr** [VsVim/VsVim#965]
In a situation where I have a commented line such as the following:

// This is a comment.

it seems when the cursor is anywhere after the two slashes, and I hit a colon, put a command in, and hit enter, it inserts a line feed in the text and the command does not happen. If I hit enter for the second time, then the command executes, but the extra line remains.

My apologies if this is a configuration item in advance.

**Comment by dtabuenc** [comment]
This seems to work fine in C# files, but I still have resharper intercepting my enter key in visual mode inside javascript strings. Is there anything sepecial that must be done to intercept the key in javascript?

**Comment by simendsjo** [comment]
I'm using ViEmu, and I'm having the same issue. Should workarounds be added to both ViEmu and VsVim, or should JetBrains fix ReSharper instead? I haven't found any setting to turn off this "feature", and I cannot find any issue for this in their issue tracker. Breaking the workflow of all vim users should be addressed at the source.

**Comment by farzadmf** [comment]
I'm not sure if this issue was ever fixed or not, but I'm having the same problem with C++ and ReSharper ...

**Comment by loolo78** [comment]
same problem. Sorry for digging up an ancient issue.
