### ISSUE TITLE
Can I enable block move using Tab

### ISSUE THREAD

**Issue by deighvyd** [VsVim/VsVim#971]
Visual Studio allows you to indent a selection containing mutliplt lines using Tab and Shift-Tab.

Is it possible to enable this behavior using VsVim?

**Comment by markvincze** [comment]
Hi @jaredpar,  
My only problem with using `>` or `<` is that if I do that, the editor loses the selection. So if I want to repeat the shifting, I have to select the text again. (I know I can indent by multiple levels if I prefix it with a number, for example `3>`, but sometimes it's difficult to guess the number of indentations needed beforehand.)  
Do you know any way around this?

**Comment by allender** [comment]
Use the '<' or '>' command and then you can use '.' to repeat the last edit, which will be an indent our outdent depending on which characters you previously used.

**Comment by markvincze** [comment]
@allender,

That's amazing, for some reason it never occurred to me that `.` would work for the multiline indentation :).  
Thanks!
