### ISSUE TITLE
Linebreaks and backspace in macros

### ISSUE THREAD

**Issue by ahem** [VsVim/VsVim#983]
In VSVim 1.3.1.3 macros doesn't record special characters like linebreaks and backspace. I seem to recall this working in previous versions, but I may be mistaken. If I record this macro: `9lf,a"<ENTER>+ "` in vsvim, then the enter key is not recorded. If I do the same in Vim it is - if I paste the recorded macro in Vim I get this output:

9lf,a"**^M**\+ "**^[**

In vsvim the same macro is pasted like this:

9lf,a"+ "

When I execute the macro, the newline is missing as well.

**Comment by neeasade** [comment]
Also seeing backspace not working in macros.

**Comment by jaredpar** [comment]
This should be fixed in the next version of VsVim (release early next week).  There is a new setting that causes VsVim to have much stricter macro recording.  That will fix issues like this.

**Comment by neeasade** [comment]
Awesome, thanks!

**Comment by ricksladkey** [comment]
Fixed by the "Clean Macro Recording" setting.
