### ISSUE TITLE
Search for Pattern with sub pattern twice while using 'n'

### ISSUE THREAD

**Issue by MartinL0815** [VsVim/VsVim#986]
I have the pattern `\(ABC\)\?DEF``.

If I search my text with the pattern the whole matching string (`ABCDEF`) is selected (as expected).
If I press `n` to step further, than suddenly the cursor stops at the beginning of the `DEF`.

**Comment by ricksladkey** [comment]
This bug is fixed at the head of VsVim master. A search now begins at the end of the previous match and so this issue can be closed.
